### ISSUE TITLE
Portable version with external profile

### ISSUE THREAD

**Issue by Virgus** [Feodor2/Mypal#10]
Hello I just discovered Mypal and want first to thank you for this wonderful work.

I installed it both in portable mode and custom mode because with portable mode I can only access the profile folder inside the main directory.

So now I'm currently not using the portable mode and I can launch correctly the batch:
START "" "PATH\mypal.exe" -profile "OTHERPATH\profile"

Is the -profile parameter disabled intentionally in the portable setup or there's a way to use it?
I like to keep the profile folder separate from the app folder even with portable versions, to be able to switch amongst different profiles.

Thanks!
Virgus

**Comment by Feodor2** [comment]
In the protable -profile parameter is used, and it is identical to **START "" "PATH\mypal.exe" -profile profile -no-remote**. If you want another path of the profile install no portable.

**Comment by Virgus** [comment]
Thanks, have a nice weekend.
