### ISSUE TITLE
Можете ли создать отдельную "энерго-сберегающую" сборку?

### ISSUE THREAD

**Issue by iyuter** [Feodor2/Mypal#101]
Современные браузеры ускоряют процессорный таймер, чем как известно увеличивается энергопотребление на четверть, особенно нежелательное для ноутбуков. Заинтересованы ли вы создать отдельную "энерго-сберегающую" сборку, чтобы испытать? Для этого в исходном коде нужно убрать все вхождения "timeBeginPeriod()" и соответствующие "timeEndPeriod()", также NtSetTimerResolution.

https://bugzilla.mozilla.org/show_bug.cgi?id=676349
https://randomascii.wordpress.com/2013/07/08/windows-timer-resolution-megawatts-wasted/

Так делают чтобы ява-скрипт быстро выполнялся, и гладко проигрывалось видео, но Майкрософт и Интел отговаривают программистов от ускорения процессорного таймера:
http://download.microsoft.com/download/3/0/2/3027d574-c433-412a-a8b6-5e0a75d5b237/timer-resolution.docx
https://software.intel.com/en-us/articles/intel-power-gadget

**Comment by Feodor2** [comment]
Есть настройка да

**Comment by iyuter** [comment]
Если вы из приведеных статей поняли о каких вызовах речь, можете ли изменить исходник и скомпилировать такую тестовую сборку?
