### ISSUE TITLE
Can not open

### ISSUE THREAD

**Issue by Anbima** [Feodor2/Mypal#104]
Hello,
I can not open
It is a white screen.

**Comment by kitaro1** [comment]
Bug. http://prnt.sc/pnzevd

**Comment by Anbima** [comment]
Other Browsers works fine.
No error.

**Comment by Feodor2** [comment]
Site main page is obfuscated badly. When i shall have freetime and mood i do it.
Better ask site people if they obfucsted it for some reason.

**Comment by Anbima** [comment]
I do not know why they do that.
