### ISSUE TITLE
Не работает добавление блюда в корзину на новом сайте www.delivery-club.ru

### ISSUE THREAD

**Issue by djmbs** [Feodor2/Mypal#107]
Добрый день!
Проблема присутвует также в Centauri и Serpent, но почему-то отстутствует в сборках New Moon и Arctic Fox от Roytam1, а также в его сборке K-Meleon. В Хроме и отдалённо родственном ему Otter Browser проблемы также нет.

Если конкретно, то сайт просто не реагирует на нажатие кнопки В Корзину, хотя кнопка подсвечивается.

Может быть, у вас найдутся какие-то идеи по поводу того, почему это происходит и как это можно побороть?

P.S.
Пробовал эксперименты с юзерагентами, в т.ч. последний хром, последний фаерфокс, сафари и самсунг браузер в качестве агентов. Не помогло. Пробовал отключать все extensions. Не помогло.

**Comment by Feodor2** [comment]
У меня не работает полностью ни в одном браузере, может на выходные отключают, а я в интернете сейчас только на выходные :(

**Comment by djmbs** [comment]
Вроде они сами это починили, так что вопрос отпадает. Сайт новый, баги они сами вычищают видимо. До этого проблема была на браузерах с более новой версией Goanna.
