### ISSUE TITLE
Is there any forecast for update 28.7.2 to be released

### ISSUE THREAD

**Issue by ByRodrigoSoares** [Feodor2/Mypal#108]
### As of the 29th, this update is available on Pale Moon and it is expected that this update will also be available for MyPal.

**Comment by Feodor2** [comment]
Getting update now shall upload new release at tueseday.

**Comment by ByRodrigoSoares** [comment]
Thank you so much for your attention good work

**Comment by Feodor2** [comment]
I think we have v28.8 soon even 29, anyway before year ends.
