### ISSUE TITLE
Can I upgrade Mypal 28.7.0 with language pack?

### ISSUE THREAD

**Issue by BiNh0X** [Feodor2/Mypal#110]
First of all I want to thank you for the great work and thanks to you I have a decent browser on my old Windows XP laptop! :)

I have Mypal version 28.7.0 with Portuguese brazilian language pack (v28.7.0) and want to upgrade to Mypal version 28.7.2, I wonder if I can upgrade directly with this language pack or need to wait for a new version of it ? Thanks a lot.

**Comment by Anbima** [comment]
You can use the same language pack.

**Comment by BiNh0X** [comment]
> You can use the same language pack.

Thank you for your help! I updated and everything was fine. The language pack really kept working.
