### ISSUE TITLE
could not  change the value of general.useragent.locale

### ISSUE THREAD

**Issue by xuiv** [Feodor2/Mypal#111]
how to do?

**Comment by Feodor2** [comment]
Type about:config in the address field and there general.useragent.locale, change to and restart. It will changed right if you install correct language and it match the value you set.

**Comment by xuiv** [comment]
couldn't change.

**Comment by Feodor2** [comment]
![lang1](https://user-images.githubusercontent.com/19492771/70135775-63e24c00-1693-11ea-9023-ce5643f80a6a.jpg)
![lang2](https://user-images.githubusercontent.com/19492771/70135777-647ae280-1693-11ea-836f-8b6b6784f424.jpg)
![lang3](https://user-images.githubusercontent.com/19492771/70135780-647ae280-1693-11ea-8aeb-05a6202d4c96.jpg)
![lang4](https://user-images.githubusercontent.com/19492771/70135783-65137900-1693-11ea-8fdb-1f4849ddd410.jpg)
![lang5](https://user-images.githubusercontent.com/19492771/70135784-65137900-1693-11ea-8209-fedff2aaec07.jpg)
![lang6](https://user-images.githubusercontent.com/19492771/70135785-65137900-1693-11ea-8973-b22a2da0cf30.jpg)
![lang7](https://user-images.githubusercontent.com/19492771/70135786-65137900-1693-11ea-9260-4fc55e2fc2ff.jpg)
![lang8](https://user-images.githubusercontent.com/19492771/70135788-65ac0f80-1693-11ea-97f6-5f1603343c67.jpg)

**Comment by xuiv** [comment]
please test zh-CN

**Comment by Feodor2** [comment]
![изображение](https://user-images.githubusercontent.com/19492771/70147273-8fbdfb80-16ac-11ea-9ba2-fbaec5a06878.png)

**Comment by xuiv** [comment]
thank you.
