### ISSUE TITLE
What happend to http://legacycollector.org/firefox-addons/ !!!!

### ISSUE THREAD

**Issue by joeturnes** [Feodor2/Mypal#112]
Off all the web pages to disappear, this one HAD an INCREDIBLE # of addons/extensions for Mypal !
Has it moved somewhere else?
Good thing i backed up the .xpi s  that i use!

**Comment by rereser** [comment]
site is permanently closed.
all files may be downloaded with this link.
magnet:?xt=urn:btih:2332zbsojxkxt36szehrjnck5nn4pxf4&dn=legacycollector.org.tar.xz 
open in you torrent client and enable dht.
file size is 8 gb.

**Comment by rereser** [comment]
other option and info.
http://web.archive.org/web/20191110173006/http://legacycollector.org/firefox-addons/index.html
http://web.archive.org/web/20191110172733/https://legacycollector.org/

**Comment by joeturnes** [comment]
Thanks.
