### ISSUE TITLE
Mypal 28.7.2.win32 does not import the bookmarks

### ISSUE THREAD

**Issue by visionhelp** [Feodor2/Mypal#115]
Mypal 28.7.2.win32 does not import the bookmarks as the version of Mypal in the install-folder 28.3.1 did before. 
(From other installed palemoon (in other install-folder; which worked for the bookmarks import before), or (from) the installation before.)

**Comment by Feodor2** [comment]
It imports through import, but in the recently bookmarked. So close the browser and copy plain the file **places.sqlite** from the old profile to the new profile.

**Comment by visionhelp** [comment]
Thanks. 
Sorry. 
I have three versions of PM, in three folders. 
I switch between them, depending on what is not working in one but in an other still. 
As Mypal 28.3.1 before did it alone automatically, now the 28.7.2 does not. 

With copying the file places.sqlite - from any of this two others - to the folder ´28.7.2´ this solves this problem ?

**Comment by visionhelp** [comment]
Thanks. 
Sorry. 
I have three versions of PM, in three folders. 
I switch between them, depending on what is not working in one but in an other still. 
As Mypal 28.3.1 before did it alone automatically, now the 28.7.2 does not. 

With copying the file places.sqlite - from any of this two other folders - to the folder ´28.7.2´ this solves this problem ?

**Comment by visionhelp** [comment]
Thanks.
Sorry.
I have three versions of PM, in three folders.
I switch between them, depending on what is not working in one but in an other still.
As Mypal 28.3.1 before did it alone automatically, now the 28.7.2 does not.

With copying the file places.sqlite - from any of this two other folders - to the folder ´28.7.2´ this solves this problem ? 

Thanks a lot.

**Comment by visionhelp** [comment]
Thanks.
Sorry.
I have three versions of PM, in three folders.
I ´switch´ between them, depending on what is not working in one but in an other still.
As Mypal 28.3.1 before did it alone automatically, now the 28.7.2 does not.

With copying the file places.sqlite - from any of this two other folders - to the folder ´28.7.2´ this solves this problem ?

Thanks a lot.

**Comment by visionhelp** [comment]
I cannot find this file in both folders. 
(Hidden files are shown, system-files are shown.)

**Comment by visionhelp** [comment]
There are 5 in - documents and setting - user-data. 
1 in Mypal / Profiles - Date 9.12.2019 
3 in Mozilla / Firefox / Profiles. 1 - the third - places.sqlite.corrupt 
 the first both 13.12.2019, the 3rd 2.5.2013 
1 in Moonchild Productions / Pale Moon / Profiles - Date 14.12.2019

**Comment by Feodor2** [comment]
You may copy whatever you want, assuming your want the most recent. Copy only **places.sqlite** do not forget to close browser before.

**Comment by foxstroot** [comment]
Try this for import links, can use it betwen chrome too https://atkinsio.com/bookmarks-html-generator/
