### ISSUE TITLE
New Release 28.8.0

### ISSUE THREAD

**Issue by Anbima** [Feodor2/Mypal#116]
Hello Feodor,
do you already know when you will make the update to 28.8.0?

**Comment by Feodor2** [comment]
A week, i was doing the update earlier, and have done some things.

**Comment by ByRodrigoSoares** [comment]
Any prediction when this update will be available on MyPal

**Comment by Feodor2** [comment]
Put into shape github code it is remained to, and add few new strings into langpacks. But i very busy i hope to do all before this week end.

**Comment by Anbima** [comment]
Hello Feodor2,
da you need german translation?

**Comment by PF94** [comment]
i guess mypal 28.8.0 will be a christmas present 😛 

i prefer this more than new moon, as while mypal has a installer, new moon has none of that.

**Comment by Feodor2** [comment]
I got injured, and could not publish update earlier.
