### ISSUE TITLE
Twitter videos stopped playing (v27.8.1)

### ISSUE THREAD

**Issue by letmeindude** [Feodor2/Mypal#12]
After upgrading to v27.8.1 I can't play Twitter videos anymore. It seems that integrated ffmpeg avcodec has some bugs? Version 27.7.2 plays everything.

**Comment by Feodor2** [comment]
Article with integrated ffmpeg has proven bad for now. Shall rebuild on old scheme and republish

**Comment by Feodor2** [comment]
Please get fixed article there
https://mega.nz/#!EeYFkToR!jlQTvpOYKNxWJgy7yuTNFA3DQVDiOaOnW3SGcMSnsIg

**Comment by letmeindude** [comment]
Thank you for your work.

**Comment by Feodor2** [comment]
Resolved
