### ISSUE TITLE
problem with wordpress gutenberg editor

### ISSUE THREAD

**Issue by sebigbos61** [Feodor2/Mypal#120]
Hi,

I´m working with wordpress, newest version, using mypal. In the standard editor there is the problem that if I edit  text, for example I assign a hyperlink to a word, something erases all text after this word.

I thougt first that this would be a wordpress/gutenberg-Problem, but it only appears if I use mypal, not with other browsers.

I use the  ematrix script-blocker-plugin but it is deactivated for this site.  Any idea?
thanks for reading,
sebastian

**Comment by Feodor2** [comment]
I was working on wordpress year ago, and with mypal. No error was.
I can uprise my wordpress setup and look.
Sure it may be the new version after a year, i try it then

**Comment by sebigbos61** [comment]
I just tried the new version 28.8.0. Still the same here.

Thanks for looking.

Besides of the wordpress bug: mypal is really great, I love it!

**Comment by sebigbos61** [comment]
Hi,

I don´t know if you already had time to check the Gutenberg problem. I just want to inform you that the problem still exists with the new version 28.8.1

Thanks for mypal and kind regards,
sebastian
  ----- Original Message -----

**Comment by Feodor2** [comment]
I turned on my wordpress, but forgot the password and where it stored too. And yet had no time and mood to search where wordpress password is stored.
Advise please about this

**Comment by sebigbos61** [comment]
I see. Maybe I can make some tests for you...;). It´s like this:
  a.. pressing "enter" in a block deletes the whole block leaving only the letter after the last cursor position 
  b.. pressing "shift+enter" in a block deletes the whole block 
  c.. "CTRL + V" for inserting something deletes a big part of the block, more or less independent of the cursor position in the block.  The cursor then is located at the beginning of the rest of the block
This happens in Gutenberg editor (wordpress standard) only. Using the plugin "classic editor" there is no problem.

I tried older versions: mypal 28.5.2 is the last version to work fine with wordpress and the gutenberg editor, also all versions before. mypal 28.6.0 is the first version with the bug.

I downgraded to 28.5.2 on both of my computers now and this is a good workaround. It´s only because I get al little bit nervous not using the newest version of a browser....;)

thanks for maypal,
kind regards,
sebastian

  ----- Original Message -----

**Comment by Feodor2** [comment]
Well, eventually i shall check some things between 28.5.2 and 28.6.0.
Meanwhile original palemoon has the error too, so you can ask palemoon developers may be they will fix quickly.
Details:
```
Метка времени: 27.01.2020 14:31:51
Ошибка: TypeError: event is undefined
Источник: http://192.168.192.100/wp-includes/js/dist/rich-text.min.js?ver=3.7.2
Строка: 4141
```
```
key: "onInput",
    value: function onInput(event) {
      // For Input Method Editor (IME), used in Chinese, Japanese, and Korean
      // (CJK), do not trigger a change if characters are being composed.
      // Browsers setting `isComposing` to `true` will usually emit a final
      // `input` event when the characters are composed.
      if (event && event.nativeEvent && event.nativeEvent.isComposing) {
        // Also don't update any selection.
        document.removeEventListener('selectionchange', this.onSelectionChange);
        return;
      }

      var inputType;

      if (event) {
        inputType = event.inputType;
      }

      if (!inputType) {
        inputType = event.nativeEvent.inputType;
      } // The browser formatted something or tried to insert HTML.
      // Overwrite it. It will be handled later by the format library if
      // needed.


```

**Comment by sebigbos61** [comment]
palemoon people just sent me the release notes to version 28.6.0: http://www.palemoon.org/releasenotes-archived.shtml#v28.6.0
That says: just fix it yourself.....;).
I run 2 versions now, the newest mypal for all purpose and the 28.5.2 for wordpress/gutenberg. Works.

**Comment by sebigbos61** [comment]
Hello,

thanks for releasing new paypal 28.9.0

Some news from the wordpress front:
  a.. with mypal 28.9.0 and the versions before there is no possibility to see blocks in gutenberg. maypal doesn´t show the visual editor/code editor switch and therefore only shows code. This bug exists also in version 28.5.2 which didn´t show the press-enter-deletes-content-bug.
  b.. the bug appears from one day to the other. I didn´t change anything in the configuration of the browsers and nothing in the configuration of my different wordpress installations. This concerns two different xp machines. I´m just reporting!
  c.. new palemoon 28.9.0.2, installed on a win-10-machine, doesn´t show any bug in wordpress and works fine
That´s it. Hope you can help,
kind regards,
sebastian
  ----- Original Message -----

**Comment by sebigbos61** [comment]
I uninstalled mypal. Cleaned all up, hard drives and registry. Now the new version 28.9.0 works in gutenberg editor. Shows the visual editor and doesn´t delete blocks when "enter" is pressed. So, I don´t know....
Problem solved.
