### ISSUE TITLE
Javascript bug in MyPal 28.8.0

### ISSUE THREAD

**Issue by letmeindude** [Feodor2/Mypal#122]
After upgrading to MyPal 28.8.0 there are issues with javascript on some sites. For example, here on GitHub I can't preview this message I am writing or I can't make this text bold or I can't edit this message after posting it.

Or another example, on this page try to click on "Show 7 newer tags"
https://github.com/blackwinter/keyword-expansion/releases

It should expand, but it doesn't.

In summary:
MyPal 28.8.0 doesn't work.
Pale Moon 28.8.0 works.
MyPal 28.7.2 works.

**Comment by rereser** [comment]
in about:config create new string.
general.useragent.override.github.com
value.
Mozilla/5.0 (Windows NT 5.1; rv:60.9) Gecko/20100101 Goanna/4.4 Firefox/60.9 Mypal/28.8.0

**Comment by letmeindude** [comment]
Thank you, it works now.
Good to know if there is a problem I should first test with the different user agent.

**Comment by PF94** [comment]
GitHub is now broken

**Comment by PF94** [comment]
Problem: Javascript broke itself again,

Ethier GitHub is doing a heavy anti-pale moon marketing crap or whatnot.

**Comment by esyede** [comment]
Is this issue still persist? I also had same problem with an annoying `unsupported browser` notice. For workaround, i just use ublock origin filter to _zap_ that annoyance.
My (workaround) filter:
```
github.com##.unsupported-browser
```

Is there any better solution?
