### ISSUE TITLE
Does not support WebExstension

### ISSUE THREAD

**Issue by FuerteFalox** [Feodor2/Mypal#123]
When i put roboform plugin with drag and drop, Mypal not install the firefox plugin with reply "not support web extension".. fix this please

**Comment by rereser** [comment]
there is nothing to fix.
no web extensions in mypal.
try this one.
https://www.roboform.com/dist/roboform-firefox.xpi

**Comment by Feodor2** [comment]
You may try centaury which has partial support.

**Comment by foxstroot** [comment]
Use Classic Addons Archive https://github.com/JustOff/ca-archive/releases
