### ISSUE TITLE
Version 28.8.1 has just been released by Palemoon Security and Stability

### ISSUE THREAD

**Issue by ByRodrigoSoares** [Feodor2/Mypal#124]
Palemoon has just released v28.8.1 security and stability release when this security fix will also be available in Mypal

**Comment by rocky7717** [comment]
This problem has been declared CRITICAL,and users have been told to update NOW!!!!

HOPE this will be addressed SOON>>>

**Comment by Feodor2** [comment]
I do not observe critical error things. What is happened?
I started to do update stuff already, but first i shall update centaury, wait a few days

**Comment by Anbima** [comment]
Hello Feodor2,
you also do the centaury browser?
Can you send me the link?

**Comment by ByRodrigoSoares** [comment]
Here is the link
https://github.com/Feodor2/Centaury

**Comment by Anbima** [comment]
Is there a german language-pack for centaury?

@Feodor2
Please update MyPal asap to 28.8.1.
It is a serious security issue.

**Comment by Feodor2** [comment]
No german language for centaury, look for basilisk languages but not at the palemoon forum, i can adapt it for centaury then.

28.8.1 will be on the following mon or tue
