### ISSUE TITLE
Problems with MyPal 28.8.0

### ISSUE THREAD

**Issue by lordpeluca** [Feodor2/Mypal#125]
I had the same problems described in this thread:

https://github.com/Feodor2/Mypal/issues/122

I did everything that's written there and it worked, but from this morning the exact same problems came back. 

I haven't moved anything, I haven't installed anything... it just stopped working and the exact same problems that are detailed in the above mentioned thread came back.

What could have happened?

Greetings.

**Comment by FakelsHub** [comment]
Микрософт уже затрахал обновлять свой GitHub! постоянно приходится обновлять браузер.

**Comment by PF94** [comment]
Yep, it went back into this mess, broken javascript.

> Mozilla/5.0 (Windows NT 5.1; rv:60.9) Gecko/20100101 Goanna/4.4 Firefox/60.9 Mypal/28.8.0


i tried replacing the "60.9" with "71", with no result, and even tried changing it to this

> Mozilla/5.0 (Windows NT 11.0; WOW64; rv:56.0) Gecko/20100101 Firefox/70

nope, no such result. @github, have you realized you have people that don't want to switch to Windows 8.1 or Windows 10? and now you've decided to make javascript broken, instand of saying a few hours ago, it just says the full date. like jan 15 2020.

**Comment by PF94** [comment]
(double post since edit requires javascript)

> Microsoft has already started updating its GitHub! constantly have to update the browser.

oh, i guess micro$oft made that move, does this affect people using windows 7? as this devilish update came out 1 DAY after the EOL of Windows 7.

**Comment by lordpeluca** [comment]
Well, too bad... Let's hope there's a solution.

Thank you for responding.

Greetings

**Comment by FakelsHub** [comment]
Что там, подвижки в почике идут? а то совсем как-то плохо без ленты активности.
Кстати на Win7 все ок, работате, на WinXP постоянные проблемы с этим "ГовноGитХабом".

**Comment by Feodor2** [comment]
Что вы хотите гитхаб ожидает участь скайпа, Ну можно помолится ещё, может кто-то хороший освободит гитхаб от мелкософта пока они его не уничтожили полностью.

Эту конкретную ошибку ещё можно исправить, странно что на васильке соответствующем 28.8 она не проявляется. Пока проблема отформатировать нормально скрипт чтобы разобраться, и задерживать выпуск 28.8.1 не буду который планирую в пн-вт.


What do you expect. Pray someone right will free github from microsoft before they destroy it completely.

This particular bug is possible to fix, and i shall try but do not delay publish 28.8.1 release on following mon or tue.

**Comment by FakelsHub** [comment]
> странно что на васильке соответствующем 28.8 она не проявляется.

вася под XP?

**Comment by FakelsHub** [comment]
Попробовал Ваилька на win7-x32 v2020.01.12 там тоже не работают плюшки гитхаба.

**Comment by FakelsHub** [comment]
И в оффициальном palemoon работает, если переключить юзер агент на native, вместо firefox.
Может у вас тут что-то с опцией?

**Comment by Feodor2** [comment]
Я проверил на оригинале 28.8.1 то же самое если стоит совместимостсь с лисой.
То есть гитхаб специально для лисы подсовывает отдельную хрень, а пельмень в том числе и оригинал не может это правильно обработать, мелкомягкие так сделали и на своем сайте, смотрите #66 
Итого нужно отказываться от совместимсти с лисой, включать её в виде исключения только где нужно. После 28.8.1 наверное я и вырублю.

Pele moon 28.8.1 affected too, that's because firefox compatibility and microsoft. So i suggest disable it (set native) and use only where needed. Upon next release after 28.8.1 i shall set it disabled by default.

**Comment by FakelsHub** [comment]
Та на Лиcе все рабоатет, или это какой-то рудимент от старой лисы остался, с котрым гит не рабатает?

**Comment by FakelsHub** [comment]
Так на Лиcе все работает, или это какой-то рудимент от старой лисы остался, с которым гит не работает?

**Comment by FakelsHub** [comment]
> Итого нужно отказываться от совместимсти с лисой, включать её в виде исключения только где нужно. После 28.8.1 наверное я и вырублю.

Скажите где надо вырубить я вырублю, очень надо, прямо очень нужно это исправление. Все остальное вторично. И я так понимаю нужно ждать 1-2 месяца? (до след исправления)
Если так, то легче уж ХП снести и не мучаться больше со старым браузерами.

**Comment by Feodor2** [comment]
![Буфер обмена02](https://user-images.githubusercontent.com/19492771/73127901-0eaa2300-3fd0-11ea-9cb1-17030b8ba908.jpg)

**Comment by FakelsHub** [comment]
Это не работате! оно и так выставллено в "Собственный"
Вот я испрашиваю может у вас опция кирдыкнулась.

**Comment by FakelsHub** [comment]
И у вас это рабоатте под ХП? (если переключено)

**Comment by FakelsHub** [comment]
И у вас это работает под ХП? (если переключено в собственный)

**Comment by Feodor2** [comment]
Работает

**Comment by FakelsHub** [comment]
Сделал uninstall + ручное удаление оставжегося мусора и заного установил, теперь все заработало. Спасибо.

**Comment by PF94** [comment]
i'm on 28.8.0, seems that issues have disappeared,

I think this was likely just a mistake, as i got a simillar problem on Chrome on a modern-day school iPad.

**Comment by lordpeluca** [comment]
Apparently, now everything is working again. 

My version is 28.8.1
