### ISSUE TITLE
Error in automatic updates in this new version 28.8.1

### ISSUE THREAD

**Issue by ByRodrigoSoares** [Feodor2/Mypal#128]
Even if I don't like updates I always prefer to update manually I must report the error when I check the automatic update of the error

**Comment by ByRodrigoSoares** [comment]
displays this error message There were problems checking, downloading or installing this update. Mypal cannot be updated because:

Update XML file not found (404)

**Comment by ByRodrigoSoares** [comment]
I imagine the correct message would be no new updates. I believe it is necessary to correct this error in a new version or recompile with this bug fixed

**Comment by Feodor2** [comment]
I have made files, but not sure about x64, confirm please if you can.

**Comment by ByRodrigoSoares** [comment]
This error occurs on my xp x32 do not know if the same occurs on the x64 version

**Comment by ByRodrigoSoares** [comment]
Now the error message is gone good job now just wait for the next version to actually see if the automatic updates work well

**Comment by ByRodrigoSoares** [comment]
good job now the error has been solved now the message appears correctly "No Update Found"
Não há atualizações Disponiveis,Por favor,Verifique mais tarde ou Habilite a Verificação automática de atualizações do MyPal

**Comment by ByRodrigoSoares** [comment]
I will wait for the next version to see if the automatic updates really work for the time being the error has been resolved thanks to the MyPal team
