### ISSUE TITLE
Проблемы с локализацией Mypal версии 28.8.1

### ISSUE THREAD

**Issue by Tameo510** [Feodor2/Mypal#130]
Здравствуйте, Федор!
Осваиваю Mypal, проблема: после установки языкового пакета (ru) и соответствующих изменений в about:config после перезапуска на полсекунды появляется окно "Ошибка синтаксического анализа XML : неопределенная сущность ...(дальше не видно); адрес: chrome://brower/content/browser.xul  Строка 347, символ 7"
После запуска все изменения в конфиге слетают на en-US. Поиск в компе показал, что файла browser.xul вообще не существует!

**Comment by Feodor2** [comment]
Откуда пакет?
Для каждой нулевой версии идёт новый
ссылка для текущей https://github.com/Feodor2/Mypal/releases/tag/28.8.0

**Comment by Tameo510** [comment]
Спасибо, все в порядке. Действительно, не тот пакет.
Удачи, Федор
