### ISSUE TITLE
New update Version 28.8.2 when it will be available for MyPal

### ISSUE THREAD

**Issue by ByRodrigoSoares** [Feodor2/Mypal#131]
**Could you inform me if the update made in Palemoon in version 28.8.2 will apply in MyPal**

**Comment by PF94** [comment]
28.8.1 just came out a few days ago

**Comment by ByRodrigoSoares** [comment]
Yes, but another update has already been made in Palemoon, I imagine that this update will be done also on MyPal to correct any errors

**Comment by Anbima** [comment]
It's not a security update.
Let's give Feodor some time, he is doing a very good job.

**Comment by Feodor2** [comment]
i shall make an update next week.

**Comment by ByRodrigoSoares** [comment]
Thank you very much MyPal good job

**Comment by cyceron88** [comment]
Hi guys, the browser is working great ! I really appreciate the effort put into it. 
Youtube popos up with the message "We’ll stop supporting this browser soon". 
Do we need to worry ? 
Best regards.

**Comment by ByRodrigoSoares** [comment]
I believe that we should not worry because Palemoon has already released a version with a solution. I think this solution is also compatible with MyPal so I hope that in the next update there will already be a solution
