### ISSUE TITLE
Mypal appreciation.

### ISSUE THREAD

**Issue by Fierelier** [Feodor2/Mypal#133]
Not sure where else I should post this, but... Thank you for passionably working on this browser. I love the single-process nature of goanna-based browsers and the more native addons. You are really breathing some new life into XP, and I appreciate that a lot.

I hope that the issues not related to Mypal, and some of the people who are unsatisfied do not discourage you or stress you out, you are doing really fantastic work.

Thank you!

**Comment by Feodor2** [comment]
You are welcome.
