### ISSUE TITLE
Тормоз контекстного меню

### ISSUE THREAD

**Issue by FakelsHub** [Feodor2/Mypal#134]
С установленным русским словарем при попытке исправить слово, всплывающее контекстное меню думает 2-3 секунды перед тем как показать варианты исправления.
С энглиш словарем такого тормоза нет.

**Comment by Feodor2** [comment]
Может потому что слов в русском больше, откуда словарь?

**Comment by FakelsHub** [comment]
с оффа ставил, там где все словари лежат.

**Comment by Feodor2** [comment]
Да дело в количестве, тормозит если много слов, проверял на других словарях тоже.
https://addons.mozilla.org/ru/firefox/addon/russian-spellchecking-dic-3703/
Вот словарик не тормозящий, если устраивает что слов меньше. Расширние не станет нормально, файлы словря можно извлекать как из зип арзива и кинуть в dictionaries

**Comment by Feodor2** [comment]
Хотя нет, количество не причём, я пользуюсь двойным словарем russian-english где больше слов и он не тормозит так. Может оптимизация какето или ещё чего, пока не знаю, словарь состоит из двух файлов aff и dic, я заметил что тормозит тот словать где файл aff большой.

**Comment by FakelsHub** [comment]
А где скачать двойной?

**Comment by Feodor2** [comment]
https://forum.mozilla-russia.org/viewtopic.php?id=15316
