### ISSUE TITLE
Netflix

### ISSUE THREAD

**Issue by TheElf01** [Feodor2/Mypal#135]
Hi, sorry, i did a search for "netflix" but no issues.   Is there any way to watch netflix in mypal? it works on firefox, but drm issues in mypal

thanks

**Comment by Feodor2** [comment]
Not likely drm stuff still runs in winxp, which version of firefox and what os?
Ny the way you may want to try centaury browser where drm system is present.

**Comment by TheElf01** [comment]
> 
> 
> Not likely drm stuff still runs in winxp, which version of firefox and what os?
> Ny the way you may want to try centaury browser where drm system is present.

Hi, sorry delay to answer, i was pretty bussy

Sadly i tested centaury but same drm problem

netflix in xp work great in latest firefox and chrome (52esr and 49)

**Comment by Feodor2** [comment]
What addons plugins do you have installed on the firefox 52

**Comment by TheElf01** [comment]
> 
> 
> What addons plugins do you have installed on the firefox 52

Silverlight only

In fact i use firefox just  for netflix, i dont have any other addon

**Comment by Feodor2** [comment]
Silverlight still should works
Read https://forum.palemoon.org/viewtopic.php?f=3&t=22056

**Comment by TheElf01** [comment]
> 
> 
> Silverlight still should works
> Read https://forum.palemoon.org/viewtopic.php?f=3&t=22056

Hi, finally i made it to work!

> tools>preferences> Enable strict transport security

I just uncheck, and netrflix start working

I  set a custom user agent in about:config too

thanks
