### ISSUE TITLE
Pornhub

### ISSUE THREAD

**Issue by hue4** [Feodor2/Mypal#136]
Will not load any video.  

Video area is grayed out. 

Doesn't work in Firefox.   Flash version 32.0.0.330.

**Comment by hue4** [comment]
Works in safe mode.  Same problem in Firefox but not chrome.

**Comment by FuerteFalox** [comment]
I have fixed Pornhub with this Fix:

about:config
Create a new string named "general.useragent.override.pornhub.com" with the contents "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko".

**Comment by FuerteFalox** [comment]
Audio don't work correctly on PornHun but the video it's ok!

**Comment by Giferns** [comment]
general.useragent.override.pornhub.com
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0 PaleMoon/28.8.1

work fo me, audio and video both are fine

**Comment by hue4** [comment]
> 
> 
> general.useragent.override.pornhub.com
> Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0 PaleMoon/28.8.1
> 
> work fo me, audio and video both are fine

works now, ty.
