### ISSUE TITLE
PaleMoon 28.8.3 is out

### ISSUE THREAD

**Issue by rocky7717** [Feodor2/Mypal#137]
Quote:..This is a security and bugfix release.

https://forum.palemoon.org/viewtopic.php?f=1&t=23851&sid=b11f7028fb58add1a0288d27cffb2382

**Comment by Feodor2** [comment]
I going to publish update next week, but today i have old winxp machine at my service and mingw, try to build there.

**Comment by Feodor2** [comment]
It works!  #126
