### ISSUE TITLE
Version that doesn't require a CPU with SSE2 support?

### ISSUE THREAD

**Issue by suleske** [Feodor2/Mypal#138]
Trying to get a browser working on a laptop with an Athlon4 processor and 1GB RAM under Windows XP. Tried the latest Win32 installer and received a message indicating it won't work without a CPU with SSE2 support.

**Comment by rocky7717** [comment]
Here you go...4th post down....https://msfn.org/board/topic/180462-my-browser-builds-part-2/page/57/

**Comment by suleske** [comment]
I see it. Thanks so much!

**Comment by suleske** [comment]
In the future, I should search for "noSSE" it appears.  Thanks again!
