### ISSUE TITLE
Not works on omegle and in tinychat

### ISSUE THREAD

**Issue by StefCraps** [Feodor2/Mypal#139]
Camera not turnning on in omegle and tinychat tells me that this browser is not supported

**Comment by Feodor2** [comment]
This stuff wont run on mypal and palemoon either.
But when i shall build next version of the Centaury i enable webrtc feature.

**Comment by StefCraps** [comment]
OK thanks

**Comment by StefCraps** [comment]
Oh so this websites need webrtc?

**Comment by Feodor2** [comment]
Yes i think.

**Comment by StefCraps** [comment]
When will u build Centaury version? and what means centaury

**Comment by Feodor2** [comment]
Update will be upon next week
Centaury is a fork of the Basilisk https://github.com/Feodor2/Centaury

**Comment by StefCraps** [comment]
Cool but what about plugins? i wanted to install mozilla plugins on ur mypal browser but its not supported, so can u make so it would be supported?

**Comment by Feodor2** [comment]
Update is almost done i shall publish it tonight
As about plugins, only old ones are supported, look look them on special sites #112.
Centaury supports some new extension though.

**Comment by StefCraps** [comment]
privet feodor a gde novi brauzer centaury? vipuskal uje?

**Comment by StefCraps** [comment]
xachu instaliravat na maiom staram windows xp

**Comment by Feodor2** [comment]
Ссылка выше

**Comment by StefCraps** [comment]
a kak zagruzits? how to download

**Comment by Feodor2** [comment]
Клацнуть **8 releases** поледняя версия сверху - assets открыты, русский файл языковой если нужно в версии 0.0.7 в **assets** тоже.

**Comment by StefCraps** [comment]
Spasiba instaliriuiu i skaju moi mnenie

**Comment by StefCraps** [comment]
instaliraval i vso rabotaiet klasna kak u staram vmozile versia u moi mozile iest 52.0.2. a ti mojesh tak sdelat shtobi na centaury mojna bi instaliravat noviee addoni ia pitalsa instaliravat novi addon no vishla error i pakrasnelsa, ia znaiu shto neabxadima novi mozilla shtobi instaliravat noviii addoni no mojet kakta nibud instaliravat na staram vmozxile? mojesh eta delat? i isho adin prozba eta sviazna s mypalam xachu shtobi omegle i tinychat saiti rabotali na mypal mojesh vkinut vmypal webgl? ia pitalsa avkluchit webgl na mypal no ne vishla

**Comment by StefCraps** [comment]
mojesh ti eta delat ili niet?

**Comment by StefCraps** [comment]
Atvechai bratan

**Comment by Feodor2** [comment]
Нет и нет

**Comment by StefCraps** [comment]
Shto niet

**Comment by StefCraps** [comment]
Ti tolka mozilu kapiravat mojesh a delat tak shto novie addoni instaliravat na staram mozile ne mojesh?

**Comment by L3P3** [comment]
Privet, my parusski is still horrible so I don't understand your conversation.
I am using Mypal on Windows XP, very very happy for that I can use modern Web apps on old Netbook again. But Webcam does not work with it. How is the progress? This is the first (and maybe only) browser for XP that runs Slack web app but I need to do business meeting video calls with it, the only thing missing to use this device for normal work. Cpaciba

**Comment by Feodor2** [comment]
Nothing was changed, these thing wont work, look post #2

**Comment by StefCraps** [comment]
@L3P3
I wanted the same but not works in omegle and in tinychat sp feodor do something about that implement webrtc in mypal please

**Comment by Feodor2** [comment]
It is implemented already but i wont built it into binary, centaury otherwise has it enabled and build that's all. No any changes will be at visible future.
