### ISSUE TITLE
Some English typos

### ISSUE THREAD

**Issue by Montclair** [Feodor2/Mypal#14]
Trying to be helpful. Please don't be offended.

Help->About

"windows xp" should be "**W**indows **XP**"
"Adap**d**ed" should be "Adap**t**ed"
"gihub" should be "**G**i**tH**ub"

I'd be happy to re-write the readme.md for you as well.

**Comment by Feodor2** [comment]
Rewrite please readme.md and i shall rewrite about help.
Thanks for the report.

**Comment by Montclair** [comment]
### Mypal

Mypal is a web browser based on Moonchild Productions' Pale Moon code.  The goal of Mypal is to provide a secure and reliable web browser for Windows XP.  Mypal operates identically to Pale Moon with some minor exceptions.  Portable modes are not available and certain settings including unused legacy Mozilla code have been removed.

### [Download](https://github.com/Feodor2/Mypal/releases)

### Support or Contact

Having trouble with Mypal? Check out our [documentation](https://github.com/Feodor2/Mypal/wiki) or [ask questions](https://github.com/Feodor2/Mypal/issues) and we’ll help you sort it out.

Please do not request support from Moonchild Productions or in Pale Moon forums.  Support is provided by me on GitHub.  Please be patient with your support requests.  You can also review existing issues and resolutions on GitHub before requesting support.

**Comment by Feodor2** [comment]
Thanks, changed about portable though. 
It available otherwise, you may want to read https://github.com/Feodor2/Mypal/wiki/Portable

**Comment by Montclair** [comment]
Noted.  I was just trying to translate what you were trying to say in the original readme about portable. Glad you have that implemented.  Glad I could be of some minor help and thanks for maintaining this project!
