### ISSUE TITLE
5 Copies Of MyPal 68 opens when you run the exe.

### ISSUE THREAD

**Issue by Kasper222Gold** [Feodor2/Mypal#140]
I've been using the old version of MyPal and recently upgraded to 68.13.7b 32 bit and I noticed that each time I launch the brower's exe, I have 5 copies running. Not sure why this is happening but I wanted to mention it. Otherwise, it's working daily for me without any issues. Thanks for making this available. I really appreciate your efforts.

**Comment by Kasper222Gold** [comment]
PS: I don't get 5 browsers opening, but I'm seeing 5 copies of mypal.exe in my task manager. Sorry I wasn't more specific.

**Comment by Thyristor-Chopper** [comment]
It's a multiprocess feature. It makes a *visual* performance boost but causes some stability issues on XP with low RAM. If you don't want it then go to about:config and double click `browser.tabs.remote.autostart` to make it `false`. This may make the entire browser freeze when just one tab freezes.

**Comment by Kasper222Gold** [comment]
bluedragon-cairo, thank you for explaining this and offering a fix.I like stability a lot more, so I'll leave it alone but I do appreciate your reply. Peace!
