### ISSUE TITLE
Browser screen position

### ISSUE THREAD

**Issue by TheElf01** [Feodor2/Mypal#140]
Hi, is not a bug, but a request, is posible to add browser position in the command line? Like width and height is working now,  something like  posx and posy

I search for a addon that do this without luck

another question, is possible to build mypal in mingw in XP?  if yes, i will try to add this command line options myself.  Im sure not, it need VS... just ask

thanks

**Comment by Feodor2** [comment]
Hi, look #126 mingw build is useable now but to be polished and polished

**Comment by TheElf01** [comment]
> 
> 
> Hi, look #126 mingw build is useable now but to be polished and polished

Hi, at the end, i solve with a script in autohotkey


`SetWorkArea(0,0,1200,768)
exitapp

SetWorkArea(left,top,right,bottom) 
{
   VarSetCapacity(area,16)
   NumPut(left,  area, 0) 
   NumPut(top,   area, 4) 
   NumPut(right, area, 8) 
   NumPut(bottom,area,12)
   DllCall("SystemParametersInfo", UInt,0x2F, UInt,0, UInt,&area, UInt,0) ; SPI_SETWORKAREA
}

`
It was important for me, because i dont use tabs, and i need to open a new window every time, and mypal did not position well, now everything is at my taste

![mypal](https://user-images.githubusercontent.com/16392474/75547973-63f0ae80-5a2c-11ea-85e9-b8157799935b.gif)

**Comment by Feodor2** [comment]
You are welcome.
