### ISSUE TITLE
Pale Moon 28.8.4 is Out!!

### ISSUE THREAD

**Issue by rocky7717** [Feodor2/Mypal#142]
Just when I DL,d 28.8.3 & installed, now 28.8.4 comes out!!...(sigh)

https://forum.palemoon.org/viewtopic.php?f=1&t=23930

**Comment by ByRodrigoSoares** [comment]
28.8.4 Another security update has been released on the palemoon I hope it will be applied soon on MyPal

**Comment by Feodor2** [comment]
Next week i shall publish update for the centaury first then mypal. An now i am at the xp machine try do further polish mingw build.
