### ISSUE TITLE
Error when in https://pixlr.com/x/

### ISSUE THREAD

**Issue by Saltor66** [Feodor2/Mypal#143]
Hello!

I use Windows XP Professional Version 2002 SP 3.
When in https://pixlr.com/x/ i have the following message and I can't use the site anymore:

"Old browser!
To be able to use the pixlr x photo editor you need a modern browser, just download a fresh one, such as Chrome, Edge, Safari or Firefox!

(Error: Could not create webgl context or use promise) "

Many thanks for your job.
Regards
Salvatore

**Comment by kitaro1** [comment]
Mypal - about config:
webgl.disabled  false

**Comment by Saltor66** [comment]
> 
> 
> Mypal - about config:
> webgl.disabled false

It was

Mypal - about:config
webgl.force-enabled true

Thank you so much! You made my day!
