### ISSUE TITLE
Problem with language pack

### ISSUE THREAD

**Issue by Raphael46100** [Feodor2/Mypal#147]
First of all  like others already says : Many thanks for your work ... It's great to find a maintained browser for XP ... (sorry for bad English)
there a problem when i try to change language to fr. 
Download and install language pack from pale moon it's ok 
but when i change the 'general.useragent.local' key from en-US to fr and restart Mypal
there an error ... 
![pb local fr 01](https://user-images.githubusercontent.com/62228217/76720682-c7255500-673d-11ea-890c-c5bdb6be0378.jpg)
this appear quickly and Mypal restart with en-US parameter ... 
Is it possible to fix that ?
I use Mypal 28.8.4 (32 bit) and 
Français (FR) Language Pack 28.8.4 ...

**Comment by kitaro1** [comment]
Open forum Mypal 28.8.0 
 mypal-lang-fr-28.8.0.xpi

**Comment by Raphael46100** [comment]
Many thanks .... i was thinking about that but can't find the right place ... thanks for quick answer

**Comment by ByRodrigoSoares** [comment]
**The Palemoo Language Pack does not work on MyPal the link below should work**

https://github.com/Feodor2/Mypal/releases/download/28.8.0/mypal-lang-fr-28.8.0.xpi

**Comment by Raphael46100** [comment]
Thanks a lot that works fine now with mypal-lang-fr-28.8.0.xpi ....
