### ISSUE TITLE
Problem with MSFN

### ISSUE THREAD

**Issue by noles22** [Feodor2/Mypal#148]
When I visit a forum topic on the following web site: https://msfn.org/board/topic/177946-beware-of-office-2010-updates/page/15/. The forum goes blank and never loads if I click the next button to go the next page on the forum. This happens with both Mypal 28.8.4 and Firefox ESR 52.9.0. However, the page works just fine in Chrome so I believe this is an old Firefox based bug that has carried over to Mypal. I am using Windows XP Professional SP3.

**Comment by noles22** [comment]
![Issue with MSFN](https://user-images.githubusercontent.com/43044816/76862731-e652de00-6834-11ea-809f-252778ebe887.JPG)

**Comment by Feodor2** [comment]
Dif not confirmed, it loads normally and this is the last page, i did prev and next and first - they all fine.
Checked Firefox ESR 52.9.0 and its ok too.
Try in the safe mode.

**Comment by EdePC** [comment]
I have not problem in me WinXP SP3 with MyPAL 28.8.4 32-bit, if too safe mode not working use HardReset MyPAL deleting folder: %AppData%\Mypal

BEFORE backup passwords, bookmarks, extensions, etc.
