### ISSUE TITLE
Bookmark All Tabs: empty title if tab unloaded and don't exist in history

### ISSUE THREAD

**Issue by Grishanenko** [Feodor2/Mypal#149]
1. Open any sites in several tabs
2. Clear history
3. Restart browser
Previous session unloaded, but every tab have title.
4. Bookmark All Tabs
Added bookmarks don't have titles.
Problem resolved here: https://bugzilla.mozilla.org/show_bug.cgi?id=754623

**Comment by Feodor2** [comment]
New version does not have the bug, and 28.8.4 put address instead of name, it is fixed already seems.

**Comment by Grishanenko** [comment]
MyPal 28.9.0 Portable installation with new profile - problem don't fixed. Yes, URLs in title, but title field have to contain a title.

**Comment by Feodor2** [comment]
I do not have a bug on 28.9, i did check with 5 tabs.

**Comment by Grishanenko** [comment]
Я увидел в соседней теме что здесь можно на русском.
Вот, записал видео (10 МБ):
ljd-02-3v02.narod.ru/video1/20200409_1425_15.avi

**Comment by Feodor2** [comment]
Ещё повторил как на видио на 5 разных сайтов - все названия сохраняються.
В безопасный режими или чистый профиль, дальше можно найти что мешает, дополнение или ещё чего.

**Comment by Grishanenko** [comment]
Это тестовая портабельная установка в отдельную директорию и только для проверки этой проблемы. Никаких плагинов не установлено. Профиль совсем пустой. Удаление директории Profile и безопасный режим не помогли.
Выяснилась еще одна зависимость. Группа добавляемых вкладок/страниц не должна существовать не только в истории, но и в закладках. Если они уже есть в закладках в других папках (ведь по сути история и закладки -  одна база?) то заголовки добавляются без проблем.

**Comment by Feodor2** [comment]
Да, если сайтов нет в закладуах названия не сохраняються.
Буду чинить в следующем выпуске уже
