### ISSUE TITLE
[Bug] Mypal Help page link from the GUI is a 404. 

### ISSUE THREAD

**Issue by Atavic** [Feodor2/Mypal#15]
From the GUI: *Help* > *Mypal Help* goes to a non-existent page:
https://github.com/Feodor2/Mypal/firefox-help

...giving a *404 Page not found*.

**Comment by windowsxpforever** [comment]
I think it was suppose to be a firefox help but it doesnt work hmm

**Comment by Feodor2** [comment]
Fixed
