### ISSUE TITLE
Discord stopped working on 27.8.2

### ISSUE THREAD

**Issue by setsumi** [Feodor2/Mypal#15]
On Mypal 27.8.2 (32-bit) Discord web app became a dead loop of login screen. Clearing cache and cookies didn't help. Reverted back to 27.8.1 (32-bit) and everything is fine.

**Comment by Feodor2** [comment]
Please take the 27.8.3 version
https://mega.nz/#!1PY1iLBA!kd_QiwKtbJWG0aqr9vW4SHpNxsCJApYq9C2hPecBeCM
Likely it is fixed there

**Comment by setsumi** [comment]
Works indeed. Thank you!
