### ISSUE TITLE
Unusual observation while using YouTube

### ISSUE THREAD

**Issue by Anish21864** [Feodor2/Mypal#150]
While using Google Chrome (before I switched over to MyPal Browser), whenever a video is right-clicked and opened in a new tab (without the new tab displaying, i.e., opening it in the background), the video doesn't play by itself unless that new tab is switched over to. 

But in MyPal Browser, it is not so and it starts playing the video without having to switch-over to that tab. Is there any way to load and start playing that video only when the corresponding tab is switched over to?

**Comment by Feodor2** [comment]
I did not make text yet, got sickness. Now is coming better i returned for work.

**Comment by Anish21864** [comment]
Yes Sir, I was unaware of this. Please take your time and address the issue
that I had opened regarding the browser

**Comment by Anish21864** [comment]
Could you please reply me whether the issue could be understood or not? If
not then I would try to elaborate it further

**Comment by joeturnes** [comment]
Try this experimental extension. I use a lot of tabs & it ALONE allows me to keep using a 17  year old slow desktop!
https://web.archive.org/web/20130705130737/https://addons.mozilla.org/en-US/firefox/addon/suspend-background-tabs/
Odd i don't see it here
http://web.archive.org/web/20191110173006/http://legacycollector.org/firefox-addons/index.html

Unrelated, custom tab width is another fantastic extension,  if u use a lot of tabs ... 
http://web.archive.org/web/20191029181333/https://legacycollector.org/firefox-addons/221515/index.html

**Comment by Anish21864** [comment]
Madam/Sir, I regret that the download of the add-on you suggested failed due to a connection failure with their web server.

![capture(39)](https://user-images.githubusercontent.com/62549298/78892193-8c85b280-7a86-11ea-95c0-a94c7b96e40f.png)

 Is this connection failure experienced by you?

**Comment by Anish21864** [comment]
Madam/Sir, I regret that the add-on you suggested couldn't be installed due to a connection failure as shown below.
![capture(40)](https://user-images.githubusercontent.com/62549298/78892381-e38b8780-7a86-11ea-8717-6828dde21f82.png)
Is this experienced by you? Please let me know if this is temporary/permanent issue, and also that if any other alternate solution is available to the issue I had posted originally.

**Comment by joeturnes** [comment]
In http://adblockplus.org/forum/viewtopic.php?f=13&t=10072
scroll down to smileypete & right click on his 2nd link(which is an xpi link) & save it to your desktop. Then in mypal, do a control-shift-a & click on extensions.
In the upper right to the left of the search field, click on the box which is a dropdown & pick
install "Install addon from file" & pick the suspendbackgroundtabs-1.0.1.xpi file you just added to your desktop.
& install it, restart mypal & see if it works(suspends tabs until you click on them) - you should see spinning progress circles on suspended tab(s) that never stop spinning until you click on one! lol
That xpi file on your desktop is 3.25 kb, but the xpi file i have been using is 12.1 kb.
If if does not work, supply your email address, so i can email you my xpi file i got a long time ago.
Oddly, i can not attach my xpi file here, unless the author(s) of this forum will allow that/make change(s) here.

**Comment by Anish21864** [comment]
I went ahead as per your instructions, but it seems that the add-on is corrupt.
![capture(41)](https://user-images.githubusercontent.com/62549298/78960774-b08bd700-7b0c-11ea-8036-2d6c1188172a.png)

**Comment by joeturnes** [comment]
Ok - in this email i attached Suspendbackgroundtabs{1.0.1}.xpi
Try installing this one in your mypal.
That is the same exact extension i've been using for years.
I also attached pics of my mypal general & tab preferences.

Regards,
Rich



     On Thursday, April 9, 2020, 11:52:22 PM EDT, Anish21864 <notifications@github.com> wrote:  
 
 


I went ahead as per your instructions, but it seems that the add-on is corrupt.

**Comment by Anish21864** [comment]
Sorry but I could find no attachment with your reply. I searched Gmail with "has:attachment" tag but couldn't find yours in it.

**Comment by joeturnes** [comment]
Reply to this with an alternative/another email address you use & i'll try sending the attachments there instead.



     On Saturday, April 11, 2020, 01:08:45 AM EDT, Anish21864 <notifications@github.com> wrote:  
 
 


Sorry but I could find no attachment with your reply. I searched Gmail with "has:attachment" tag but couldn't find yours in it.

**Comment by Anish21864** [comment]
anishsurren@gmail.com

This is my Gmail account.
OR

anishsurren@yahoo.com
This is my Yahoo account.
