### ISSUE TITLE
Firefox->Mypal tab groups migration question

### ISSUE THREAD

**Issue by somejerk** [Feodor2/Mypal#152]
My apologies in advance if this isn't the right forum for a support request (I couldn't see any other); I already made the mistake of asking this question in the Pale Moon forum and was firmly redirected.

I've been running Firefox 52.9.0 with Tab Groups 2.1.4 since about forever, but the machine it's on is dying on its feet and I've just set up a new one (also under xp) to replace it. I want to move my many tabs+groups to the new system, Mypal 28.8.4 w/ Tab Groups 0.4 .

I'd assumed I'd just do it via Mozilla's sync (passwords, bookmarks, tabs, the lot), but it appears that Pale Moon does sync the way Firefox used to but no longer does (?).

What's the right way to accomplish this?

Thanks much.

**Comment by kitaro1** [comment]
Install mypal portable. This option is available in the first window of the Mypal installer.
Create a Mypal folder wherever you want. In the installer, you will select this folder to install and install mypal there. The installer will extract all Mypal folders and files.
Use for health. On a pen drive, second disk, another computer, transfer to the second computer - whatever you want. The browser in this song keeps the appdata and local appdata folders. Bookmarks, logged pages and no settings are lost.
I recommend Mypal for banking.
You can always have your Mypal with you, or on the second partition of a third computer.

**Comment by Feodor2** [comment]
Copy profile files for backup and i suggest not rely on sync for this.
