### ISSUE TITLE
Не работает, руссификатор на 28.8.4 

### ISSUE THREAD

**Issue by TanRat** [Feodor2/Mypal#155]
Пробывал скачать из palemoon от 28.8.4 она загрузилась подошла, но сам панель и весь браузер ничего не поменялся. Пробывал language pack на Enable поставить из default а так же about:config прописать на useragent.local ru-RU но увы, при каждом перезапуске браузера ставится на defaul-тный режим мало того что он еще и не работает.

**Comment by kitaro1** [comment]
https://github.com/Feodor2/Mypal/releases/download/28.8.0/mypal-lang-ru-28.8.0.xpi

**Comment by Feodor2** [comment]
Таки это дублирует #147
