### ISSUE TITLE
Tabs from Restored Session 28.9

### ISSUE THREAD

**Issue by Culexamaxa** [Feodor2/Mypal#158]
Selecting some tabs in a restored session with v28.9 x32 appears to wipe the tab, making it blank.

**Comment by Feodor2** [comment]
How to reproduce?

**Comment by Culexamaxa** [comment]
I typically have open 3 windows.  If you have your settings set to save a session and reload a session automatically as I do, then it should manifest.  It can manifest with a closure and subsequent opening of MyPal, or with a restart of the browser.

Three windows with several tabs open.  A few are usually active before terminating session, and others are inactive (have not been accessed) during a session. 

If a tab is not the active tab when doing an exit or a browser restart, when you select one of these tabs on the next load, instead of loading it returns blank page and URL clears from address bar.

**Comment by Feodor2** [comment]
No i do not have this. Try in safe mode or vanilla profile

**Comment by Culexamaxa** [comment]
I restarted in safe mode and this was not an issue.

I disabled a few addons with returning from Safemode.

Addons I disabled were: 
User agent switcher 0.7.3
Block Site 1.1.8
Better privacy 1.77
Classic Addons 2.0.1


Tabs appear to be functioning normally.

**Comment by Culexamaxa** [comment]
Interestingly, all it took was disabling addons, restarting, enabling them and restarting again.

All my usual addons are disabled/enabled manually.
