### ISSUE TITLE
general.useragent.locale;en-US cannot be changed

### ISSUE THREAD

**Issue by sebigbos61** [Feodor2/Mypal#159]
I installed the german language pack and wanted to switch language with general.useragent.locale;en-US to general.useragent.locale;de

But mypal sets the value back to en-US on restart. Same with the plugin local switcher

**Comment by Feodor2** [comment]
It is you did something wrong, i checked de once more it is fine.
![image](https://user-images.githubusercontent.com/19492771/79050463-e88d3a00-7c32-11ea-821a-e059ea15dcfe.png)

**Comment by Anbima** [comment]
You must use de-DE

**Comment by sebigbos61** [comment]
maybe I do something wrong. The language pack (DE 28.9.0) works I think. If I change to de or de-DE the preferences-window is german and other windows also. Only the main menu stays english because this needs a restart. But after restarting general.useragent.locale is back to en-US

**Comment by Feodor2** [comment]
**de-DE** is not required, simple **de** is enough, may be you get corrupt file

Check **langpack-de@mypal.org.xpi** is 413 864 bytes

**Comment by sebigbos61** [comment]
I tried other language packs, french, spanish, it´s all the same.

I have this in the install.log:
** ERROR Registering: D:\Internet\mypal\AccessibleMarshal.dll **

**Comment by Culexamaxa** [comment]
In #158, I isolated the issue I was having to being "User agent switcher 0.7.3." addon.  Could the issues be related since this involves "general.useragent.locale?"

**Comment by Feodor2** [comment]
The error is not related to this at all. But i shall try to fix it.
Did you check xpi file?

**Comment by sebigbos61** [comment]
I downloaded the xpi again, 2 times, the version from the language addon site and the latest one from the archive. Both have 474284 byte but I am quite sure that win xp never shows the correct size of files.
And: other language packs have the same problem, I´m not able to switch.

Then I restart mypal after switching to de I get a little window with yellow content but I can´t read, it´s just for the tenth of a second

**Comment by sebigbos61** [comment]
I got the start window as a screenshot:
![mypalstartwindowafterlocalswitch](https://user-images.githubusercontent.com/56233681/79197469-0eccf880-7e32-11ea-8c54-b2d09d5fca6c.jpg)

**Comment by sebigbos61** [comment]
uuuhhhh..... you were right. My fault. Wrong language pack.

Sorry and thanks.
