### ISSUE TITLE
Complete source tarball?

### ISSUE THREAD

**Issue by rn10950** [Feodor2/Mypal#16]
Is there a way you could either upload the full source (with the patches applied) to the master branch or provide it with releases? I need to work out an issue specific to my CPU configuration (2 x Xeon E5-2670) that prevents me from upgrading to any Gecko 52.x browser (including Firefox 52esr).

**Comment by Atavic** [comment]
Palemoon Source: https://github.com/MoonchildProductions/Pale-Moon

**Comment by rn10950** [comment]
I downloaded the PM source at 28.0.1, and tried applying winxp.patch, and nearly every patched failed, using git apply --ignore-whitespace <FILE>

**Comment by Feodor2** [comment]
Yes 28.0.1 winxp patch is failing on 28.1.0 and i done update. But if you want 28.0.1 exactly take older patch, do **git head-1** command on mypal. Notice the winxp_a.patch makes new file, witch git do handle with add. command, it is to be applied once. 

Uploading the whole 1gb is annoyance, all the more it almost duplicates original palemoon source, let we try resolve another way. What problem with the xeon do you have?
