### ISSUE TITLE
Facebook....

### ISSUE THREAD

**Issue by bushy555** [Feodor2/Mypal#165]
Hi,

Absolutely brilliant this entire project. Can't thank the team enough for continuuing support for old XP.

My quick problem : Dumb Facebook.
Is Facebook just totally bloated crap that is going to fail on all browers? As in, open up a few tabs showing different FB pages, and Task Manager shows that MyPal (And PaleMoon and Firefox) all hits the 1 to 1.2 gig of RAM mark, and everything slows down incredibly. Creating a reply, or even swapping tabs can take upwards of 30 seconds before an response. And, yes, this does happen on all three browsers. There is near to zero disk activity during this time, so there is no pageswapping, and the different computer(s) that I run and try this on, (All are XP) show that the O/S is indicating that it is occupying all maximum of 3.6 gig available to XP, out of the physical 4 gig RAM installed. (RUN: WINVER) 
So, it is probably just a quick question : Is Facebook just bloated crap that could be "Oh! It could be so much better written in an optimised way, but the Facebook team are just incredibly lazy to do"

...Or is there a problem with the underlying core of the Mozilla engine ?

....If Im complaining only about dumb Facebook, I really don't have anything to complain about do I?
Keep up the fabulous work with MyPal !

**Comment by Feodor2** [comment]
I can possible look into this but i need an account. Create dummy account for me

**Comment by bushy555** [comment]
Please see memory usage comment in #189.
Cheers.
