### ISSUE TITLE
mypal - "ваш браузер устарел"...((

### ISSUE THREAD

**Issue by saboteur1000** [Feodor2/Mypal#166]
Здравствуйте.
Стоит последняя версия 28.9.1
Сегодня яндекс музыка (https://music.yandex.ru/) выдала следующую надпись:
"Ваш браузер устарел, поэтому Музыка не может быть открыта."
Это всё, да? Конец? Только на 7-ку переходить?
Чат рулеты, кстати, тоже давно уже не поддерживаются.
Ну и Myspace до кучи - музыка также не играет.

**Comment by eugen1962** [comment]
> 
> 
> Здравствуйте.
> Стоит последняя версия 28.9.1
> Сегодня яндекс музыка (https://music.yandex.ru/) выдала следующую надпись:
> "Ваш браузер устарел, поэтому Музыка не может быть открыта."
> Это всё, да? Конец? Только на 7-ку переходить?
> Чат рулеты, кстати, тоже давно уже не поддерживаются.
> Ну и Myspace до кучи - музыка также не играет.

Музыка действительно блокируется, Да и на некоторых других российских сайтах ещё и видео блокируется. Режим "самоизоляции", наверно. ;) 
Но никаких "Ваш браузер устарел" отродясь не видал даже в Рунете.
А на нормальных сайтах и через броузер, и со сбросом на плеер всё воспроизводится.

**Comment by saboteur1000** [comment]
> 
> 
> > Здравствуйте.
> > Стоит последняя версия 28.9.1
> > Сегодня яндекс музыка (https://music.yandex.ru/) выдала следующую надпись:
> > "Ваш браузер устарел, поэтому Музыка не может быть открыта."
> > Это всё, да? Конец? Только на 7-ку переходить?
> > Чат рулеты, кстати, тоже давно уже не поддерживаются.
> > Ну и Myspace до кучи - музыка также не играет.
> 
> Музыка действительно блокируется, Да и на некоторых других российских сайтах ещё и видео блокируется. Режим "самоизоляции", наверно. ;)
> Но никаких "Ваш браузер устарел" отродясь не видал даже в Рунете.
> А на нормальных сайтах и через броузер, и со сбросом на плеер всё воспроизводится.
Спасибо за отклик. Действительно, яндекс музыка опять заработала. Мистика какая-то... Надо было скриншот сделать.
А скажите пожалуйста, на каких нормальных сайтах и всё остальное, что вы написали, можно прослушать либо скачать вот это: https://myspace.com/nochieprogulki/music/albums
И ещё, на платформе чат рулетов постоянно проводятся интересные вебинары, но работает только чат, звука и видео нет. Как сделать, чтобы заработало? Примеры подобных чатов: https://chatroulette.com/             https://camki.com/

**Comment by Feodor2** [comment]
"Броузер устарел" это в порядке вещей с пельменем, буде часто где. Хозяева таких сайтов жадные, за копейки нанимают для рзрботки сайтов тупых людей - их подход в том что если ваш броузер не хром то он устарел.  Яндекс если прогнулся под гугел то ожидать можно всего.

**Comment by saboteur1000** [comment]
А причём здесь Хром, если проблема в XP? Если я поставлю тот же Хром или Оперу, или Лису, которые поддерживают XP, эти сайты всё равно работать не будут. Ответ везде будет один - ваш браузер устарел, а новый установить невозможно, потому что ваш XP тоже устарел.

**Comment by eugen1962** [comment]
> 
> 
> > Музыка действительно блокируется, Да и на некоторых других российских сайтах ещё и
> > видео блокируется. Режим "самоизоляции", наверно. ;)
> > Но никаких "Ваш браузер устарел" отродясь не видал даже в Рунете.
> > А на нормальных сайтах и через броузер, и со сбросом на плеер всё воспроизводится.
> 
> Спасибо за отклик. Действительно, яндекс музыка опять заработала. Мистика какая-то... Надо было скриншот сделать.
> А скажите пожалуйста, на каких нормальных сайтах и всё остальное, что вы написали, можно прослушать либо скачать вот это: https://myspace.com/nochieprogulki/music/albums
> И ещё, на платформе чат рулетов постоянно проводятся интересные вебинары, но работает только чат, звука и видео нет. Как сделать, чтобы заработало? Примеры подобных чатов: https://chatroulette.com/ https://camki.com/

Право, мне как-то непривычно в роли диджея, но раз уж "зацепились", то не проблема музыку в сети найти. Я эту психоделику (кстати, приятные композиции, в основном), что по линку Майспейс, вот тут и послушал, и скачал тестово:
https://ru357.iplayer.info/artist/8698560-Nochnye_Progulki/
https://www.last.fm/music/%D0%9D%D0%BE%D1%87%D0%BD%D1%8B%D0%B5+%D0%9F%D1%80%D0%BE%D0%B3%D1%83%D0%BB%D0%BA%D0%B8
Но линков (по грепу, не по Яндексу) выскочило много больше, разумеется.
Ну а ту страниуц, что вы порекомендовали, Майспейс у меня ничего не берёт. Ни броузеры, ни что другое. Даже Youtube-dl у меня в ПЕРВЫЙ раз оплошал. Надо будет разработчикам написать, они бахвалятся, что нет таких музыкальных сайтов, чтобы их Youtube-dl не раскусил.
Так что спасибо сударь, что такой интересный линк подогнали.
Майспейс круче и OK.RU, и Яндекс Музыки оказался.

А, вообще, я тезисы Уважаемого хозяина ресурса поддерживаю. Нанимают майспейсеры, яндексы и др. всяких... и не только глупых, но и придумковатых шибко. Из тех, что разные новомодные фитчи куда ни попая втютюхивают. И радуются, аки дети, что такого ни у кого больше нет.

**Comment by saboteur1000** [comment]
**eugen1962**, на last.fm этого альбома нет, там только его описание. Найти и скачать этот альбом невозможно нигде, кроме Myspace. Раньше, когда Myspace поддерживал XP, я слушал там этот альбом, но скачать не додумался и теперь просто потерял к нему доступ, потому что Myspace прекратил поддержку XP.

**Comment by Feodor2** [comment]
Проверте пельмень на win7, уверен что "Броузер устарел" не исчезает.
Хотя https://myspace.com/ не пишет это, причина совсем в другом эту конкртную музыку возможно удалили _Service Temporarily Unavailable_. Другие песни работают на winxp в том числе, но ещё должна стоять network.jar.block-remote-files;false

**Comment by eugen1962** [comment]
> 
> 
> Проверте пельмень на win7, уверен что "Броузер устарел" не исчезает.
> Хотя https://myspace.com/ не пишет это, причина совсем в другом эту конкртную музыку возможно удалили _Service Temporarily Unavailable_. Другие песни работают на winxp в том числе, но ещё должна стоять network.jar.block-remote-files;false

"Броузер устарел", хотите верьте, хотите - нет, но на Ваш Mypal у меня ещё сайты не реагировали. Я почему с таким энтузиазмом и воспринял этот Ваш проект для ХР. 
Я на разных ОС тестировал, разумеется. Причем Юзер Агента не менял. Это "другие" развлекаются, те, что UXP. Они по дефолту и от ХP до Win10 выставляют на разных своих моделях. И, что более интересно (ядро же), начали применять разные вариации движка: и Гечо+Гоанна, и чисто Гоанна. Но всё-равно тесты примерно одинаковые показатели выдают.
Касаемо музыки с Майспейс. Я же не только броузером пробовал её там зацепить. И сорс их страниц наизучался, чтобы крюка найти, и  Youtube-dl - это же кроссплатформенный скрипт. Очень мощный, не врут разработчики. Так что наверно Вы правы, ролики или удалили, или это локальная проблема сайта. Устранят - заиграет, как и на Яндексе было.
Спасибо за совет по ключу about:config. А то я намаялся, перебирая методом "тыка", когда с WebGL разбирался. Очень интересны такие штуки. У Вас же авторский продукт, как ни крути. Хотя Вы и написали ранее, что всё как у "Большого Пельменя". 
В порядке дискуссии: может, если время найдётся, заведёте страничку Wiki с перечнем актуальных ключей about:config в Mypal, а? Ну и комментарий коротенько по каждому. Уверен, что народ оценит позитивно

**Comment by saboteur1000** [comment]
**eugen1962**, вы с кем говорите? Как вам удалось "послушать и тестово скачать" альбом с last.fm? Вы так этого и не сказали. Это какая-то секретная информация? Расскажите, как это сделать, пожалуйста.
**Feodor2**, спасибо за отклик. WIndows 7 у меня, к сожалению, не стоит. В противном случае я бы и не нашёл ваш браузер. Я всё целяюсь за XP (в основном из-за звуковой платы), поэтому и вынужден был искать хоть какой-то действующий браузер. Спасибо вам за него. Продлили, так сказать, агонию.
Похоже, и на Myspace, этого альбома больше нет, вы правы.
Видео чаты, наверное, из той же оперы что и Skype и на XP их заставить работать уже нельзя, верно?

**Comment by Feodor2** [comment]
Видеочат это скорее всего webrtc которое в пельмене отключено в исходном коде и я не собираюсь включать его. НО есть василёк https://github.com/Feodor2/Centaury.

**Comment by saboteur1000** [comment]
**Feodor2**, например такой чат сайт: https://pruffme.com/
Был оплачен онлайн курс, а когда он начался, ни фига не работало. Повезло, что под рукой есть планшет с андроидом.
Спасибо за наводку с **Centaury**, но, увы, он тоже не работает. Попробовал его в нескольких чатах и везде одно и то же - после коннекта идёт сообщение об ошибке с последующим вылетом браузера:
[URL=http://imglink.ru/show-image.php?id=fe5345fa9fccaea38c5b9b3c4ebeb9d3] [IMG]http://imglink.ru/thumbnails/30-04-20/02b078b5b0ad165065fde0b1b5f2e4ce.jpg[/IMG][/URL]

**Comment by eugen1962** [comment]
> **eugen1962**, вы с кем говорите? Как вам удалось "послушать и тестово скачать" альбом с last.fm? Вы так этого и не сказали. Это какая-то секретная информация? Расскажите, как это сделать, пожалуйста.

Я со всеми говорю, причем достаточно дружелюбно. Я же 2 ссылки дал, но сайтов много больше, где есть эта музыка. И что вы так именно за Ласт ФМ ухватились? Там плеер "выскакивает" поп-апом, там я только слушал, И оценивал (лайки, как и другие юзеры, кстати). Чем скачивал - пояснил выше, сходите на сайт, там море инфы и по программе, и по скачиванию с разных сайтов.

**Comment by saboteur1000** [comment]
>  Я же 2 ссылки дал, но сайтов много больше, где есть эта музыка.
По первой ссылке только два трэка. Есть, кстати, и на Youtube один видеоклип.
>   И что вы так именно за Ласт ФМ ухватились?
Да просто вы прихвастнули - этого альбома нет нигде, включая last.fm. Там тоже только его описание, как и на Myspace, а самих трэков нет. И послушать его там вы не могли.
Трэков и кнопок плеера нет:
http://imglink.ru/pictures/01-05-20/59558b94f3d05524e3430c38367a140c.jpg
А вот пример, когда трэки и кнопки плеера есть:
http://imglink.ru/pictures/01-05-20/345c3fa1751b4be7878fabc8f0c60713.jpg
> Я со всеми говорю, причем достаточно дружелюбно.
 Так зачем же врать? Вас кто-то заставляет это делать? Соврали, а когда вас уличили, делаете вид, что не слышите. Не хорошо.

**Comment by eugen1962** [comment]
> 
> 
> > Я же 2 ссылки дал, но сайтов много больше, где есть эта музыка.
> 
> По первой ссылке только два трэка. Есть, кстати, и на Youtube один видеоклип.
> 
> > И что вы так именно за Ласт ФМ ухватились?
> 
> Да просто вы прихвастнули - этого альбома нет нигде, включая last.fm. Там тоже только его описание, как и на Myspace, а самих трэков нет. И послушать его там вы не могли.
> Трэков и кнопок плеера нет:
> http://imglink.ru/pictures/01-05-20/59558b94f3d05524e3430c38367a140c.jpg
> А вот пример, когда трэки и кнопки плеера есть:
> http://imglink.ru/pictures/01-05-20/345c3fa1751b4be7878fabc8f0c60713.jpg
> 
> > Я со всеми говорю, причем достаточно дружелюбно.
> 
> Так зачем же врать? Вас кто-то заставляет это делать? Соврали, а когда вас уличили, делаете вид, что не слышите. Не хорошо.

Так у вас и на Яндексе точно также ничего не играло, и песен этих в сети как не было, так и нет.  Хотя это не так.
Слушал и скачивал эти "Ночные прогулки" я отсюда:
https://ru357.iplayer.info/artist/8698560-Nochnye_Progulki/
На ЛастФМ слушал. Почему  у вас там не видно плеера я не знаю. Наверно потому, что этот сайт опознаёт ваш компьютер как Windows XP станцию. А не только броузер идентифицирует. Это известная проблема (в основном на сайтах банков) и это лечится,. Но в вашем конфликтном ключе я    что-либо дальше обсуждать не намерен. Всего вам наилучшего

**Comment by saboteur1000** [comment]
> На ЛастФМ слушал. Почему у вас там не видно плеера я не знаю.
Там есть плеер везде, где есть музыка. При чём тут XP? Через Андроид этой музыки там тоже нет. Связался со знакомым программистом, у которого и 10-ка, и Мак, он подтвердил, что этого альбома там нет.
Зачем вы врёте? Зачем вам это надо? Вы больной?

**Comment by miken236** [comment]
Кто разработчик mypal? Как долго этот браузер будет поддерживаться на xp? Какие есть еще альтернативы? По поводу браузера: нет расширения text mode, еще когда останавливаешь загрузку он все равно продолжает загружать сайт и жрет интернет. Что можно сделать?

**Comment by miken236** [comment]
Как долго mypal будет поддерживаться на xp?

**Comment by Feodor2** [comment]
Бесконечно долго - это первопрична появления майпала. Не нужна бы была хр пользовал бы  оригинальный палемун.

**Comment by miken236** [comment]
В принципе неплохой браузер, но есть одна проблема. Открываешь сайт вк к примеру и он начинает грузить все что там есть, нажимаешь стоп никакой реакции, продолжает жрать инет. Можно ли как то отключить загрузку страницы, может программа какая нибудь с кнопкой временного отключения/включения инета? 
А для линукса не существует поддерживаемого браузера для старых версий ubuntu? Очень тяжело переустанавливать систему каждый год. Тоже самое для андроид 2.1?  Пока на анроиде кое как работает браузер но чувствую скоро тоже отрубят поддержку, будет не зайти в почту и тд.

**Comment by miken236** [comment]
Feodor2 есть какие нибудь способы остановить загрузку страницы? Траффик вылетает как в трубу, зашел на несколько сайтов - минус 40 мб, он постояннго чтото подгружает, это при том что у меня 2g. На 3g 10 гб можно потратить за день!

**Comment by Grishanenko** [comment]
[b]miken236[/b]
1. меню "File - Work Offline" проблему решает?
2. Ставьте eMatrix https://addons.palemoon.org/addon/ematrix/ и режьте все лишнее. Вероятно, путем потери части функционала сайтов.

**Comment by Feodor2** [comment]
Нормальные страницы не должны ничего подгружать, дайте ссылку я помотрю.

**Comment by miken236** [comment]
Я имею ввиду вк фотографии например заходишь, допустим там 200 фотографий, загрузились первые несколько, нажимаю стоп, а он продолжает дальше грузить.

**Comment by Feodor2** [comment]
Так ссылку дайте, нету у меня 200 фото - не пользуюсь вк.
А вообще предлагаю установить носкрипт или уматрикс, на носкрипт пелменевские разрабы катят бочку что ломает сайты, возможно ломает два с половиной сайта неспорю, ну и что, польза значиельно больше вреда,о вашу проблему он решит думаю.

**Comment by miken236** [comment]
Он так себя ведет с любой страницей, откройте просто любую странику в соцсети; непрекращающаяся загрузка; даже на этом сайте как я пишу я вижу как он поджирает трафик 15-20 кб, в сообщениях допустим в вк, ничего не происходит, он время от времени загружает чтото. Расширениями я не понимаю как пользоваться, но нужно не это, а просто чтобы кнопка стоп работала, нажал стоп и больше на этом сайте ничего не грузилось; оффлайн это делает, но все время нажимать неудобно.

**Comment by Grishanenko** [comment]
**miken236**, надеюсь, вы понимаете что не все люди сидят в соцсетях и не все люди даже зарегистрированы во вконтакте? Дайте точные ссылки на сайты за пределами этой соцсети, где такое происходит и с картинками и с лишним трафиком. А по поводу сообщений: чтобы вы увидели новое сообщение, должен происходит периодический обмен пакетами информации. Если поймете суть настройки eMatrix - сможете отключить определенные скрипты (методом тыка). Тогда не будет лишнего трафика, но и новое сообщение не появится, пока не обновите страницу вручную.

**Comment by miken236** [comment]
Почему на ютубе исчезло разрешение 144p? Только 360.

**Comment by miken236** [comment]
Теперь на всех видео так.. ну что за па**длы.

**Comment by miken236** [comment]
Есть китайский браузер 360 вы не знаете как долго он будет поддерживаться? Для андроид 2.1 eclair есть что нибудь? Сейчас опера работает на андроиде, но мне кажется это случайность, или они там забыли отрубить поддержку.

**Comment by Feodor2** [comment]
>Есть китайский браузер 360 вы не знаете как долго он будет поддерживаться?

Откуда я могу это знать, спрашивайте у них.

>Теперь на всех видео так..

Непрада есть все виды от 144 для 1080 и 2044 даже

**Comment by miken236** [comment]
У меня нет! 360 и 720. Missing options? и дальше он посылает установите нормальный браузер.

**Comment by Feodor2** [comment]
давай ссылку на конкретный ролик посмотрим.

**Comment by miken236** [comment]
Любой ролик. Может у меня версия не та 28.9.1 32 бит?
А для андроида нельзя сделать подобное? Для  2.1 ничего нет, все только от 4.1. На 2.1 невозможно зайти в гоогле драйв, ввести капча и тд.

**Comment by Feodor2** [comment]
Чего застряли на 28.9.1? 
Специально на этой версии проверил - всё нормально. В безопасном пробовали?

**Comment by miken236** [comment]
А что нужно чтобы сделать такой же браузер для андроид 1+? Как вы делаете совместимость с xp, где можно это почитать?

**Comment by miken236** [comment]
Как удалить полностью и переустановить программу заново? Удалил несколько сертификатов, после этого стало появляться предупреждение о небезопасности, добавления сайта в исключения. Когда я удаляю программу и устанавливаю снова, история и все остальное остается, также остается и проблема с сертификатами.

**Comment by miken236** [comment]
Да, действительно на ютубе разрешения есть, для этого нужно было удалить вручную из programfiles  и appdata и переустановить.

**Comment by miken236** [comment]
Могли бы вы  сделать такой же браузер для андроид ? Г.ны заставляют меня припереться в магазин, отсчитать 20к руб и купить смартфон с анроид 20 а старый выбросить на помойку, чего я делать никогда не буду.

**Comment by miken236** [comment]
В palemoon для андроид можно добавить поддержку ранних версий?

**Comment by Feodor2** [comment]
Не втему совсем, ну я не занимаюсь палемуном и андройдом - хватит,
