### ISSUE TITLE
Translation Service for Changing a Language to Another

### ISSUE THREAD

**Issue by Anish21864** [Feodor2/Mypal#167]
It seems that Mypal Browser doesn't have translation services in order to translate a web page's contents from a particular language to, for example, English. Could it be included in this browser? Or if there is any service available in the browser itself, where would it be found to activate? 

If no, then is any add-on required to be installed?

**Comment by Grishanenko** [comment]
https://addons.palemoon.org/addon/translatethis/

**Comment by Anish21864** [comment]
Thanks a lot for your help
