### ISSUE TITLE
v28.9.2 This is a small update for stability and compatibility Launched in Palemoon

### ISSUE THREAD

**Issue by ByRodrigoSoares** [Feodor2/Mypal#169]
**This is a minor update for stability and compatibility.

    Re-based the 28.9 version of browsers on a separate development branch that excludes the extensive work being done for Google WebComponents, to avoid potential performance and stability issues caused by as-of-yet incomplete and in-progress code for the new milestone.
    Enabled DOM High Resolution timestamps for compatibility with websites that strictly rely on them for operation.
    Added a preference to allow copying the unescaped URL from the address bar (especially useful for internationalized domain names and paths).
    To enable this, set browser.urlbar.decodeURLsOnCopy to true in about:config
    Fixed several application crashes (thanks, Fysac!)**

**Comment by ByRodrigoSoares** [comment]
> 
> 
> **This is a minor update for stability and compatibility.
> 
> ```
> Re-based the 28.9 version of browsers on a separate development branch that excludes the extensive work being done for Google WebComponents, to avoid potential performance and stability issues caused by as-of-yet incomplete and in-progress code for the new milestone.
> Enabled DOM High Resolution timestamps for compatibility with websites that strictly rely on them for operation.
> Added a preference to allow copying the unescaped URL from the address bar (especially useful for internationalized domain names and paths).
> To enable this, set browser.urlbar.decodeURLsOnCopy to true in about:config
> Fixed several application crashes (thanks, Fysac!)**
> ```

**These security and compatibility updates will be applied to MyPal or not any deadline for this update to be made on MyPAL**

**Comment by Feodor2** [comment]
Mingw build has been made, and will be upoladed soon.
Regular update will be made upon monday, when i reach my main machine.

**Comment by ByRodrigoSoares** [comment]
**Thank you for your attention, good work, thank you for your efforts to maintain support for old XP**
