### ISSUE TITLE
Building a New Browser based On Backported Webkit or Blink

### ISSUE THREAD

**Issue by SaranSDS008** [Feodor2/Mypal#17]
Hey @Feodor2 
I'm really sorry to hear that your Awesome Browser MyPal had to be shut down forcefully. I'm an Avid user of your Awesome Browser Mypal in my Windows XP Machines btw, and this disappoints me a lot. I kinda been eyeing on Apple Webkit and Chromium Blink Engine for a while though, and that seems a really good sort of Codebase. Many People nowadays use Chrome Based Browsers and there are a lot of Extensions available for Chrome though. Also, it is possible to have Chromium and Webkit based Browsers as Proprietary, despite the Engines themselves are Open source (Like Take for eg: Google Chrome, Apple Safari, Opera, Vivaldi, etc. They are based on Open Source, but the Browser themselves are Proprietary/Closed Source). Also, Chromium and Webkit Engines does support a Lot of Modern technologies like WebRTC, JavaScript, HTML 5, Java, Flash & Silverlight (If managed to hack that into the Codebase), etc. Also, Backporting with a Team of Members is much easier compared to Building your own Engine (Like for Eg: Presto in case of Opera Classic). So, I request you to take a look at the codebases respectively, and if possible, build a Proprietary browser based on Backported version Chromium or Webkit Engine (It is possible to backport it using a Team of Members though).
Regards,
SaranSDS008

**Comment by Anbima** [comment]
Feodor2,
are you planning a new browser for Windows XP, or may we not make any hopes?

**Comment by SaranSDS008** [comment]
> Feodor2,
> are you planning a new browser for Windows XP, or may we not make any hopes?

Yeah, same question here @Feodor2 . Are you planning to build any new browser/work on existing?

**Comment by E-System33** [comment]
Let's let him rest first

**Comment by E-System33** [comment]
He really needs it

**Comment by NEO-SPECTRUMAN** [comment]
>Let's let him rest first

+1
in other hand
we losing the "race" with newer browsers/stupid site coders
now many sites not work at all...

**Comment by Feodor2** [comment]
There is already https://msfn.org/board/topic/182876-360-extreme-explorer-modified-version/
And i better like firefoxes.

**Comment by gdl-blue** [comment]
is there progress about backporting newer Firefox such as v78 ESR?

**Comment by SaranSDS008** [comment]
> There is already https://msfn.org/board/topic/182876-360-extreme-explorer-modified-version/
> And i better like firefoxes.

Or why not try Backporting a newer version of Firefox ESR using a team of members if possible, provided if you don't mind the MPL 2.0 restrictions? Also, Having a Chinese Browser in our PCs is definitely not a good Idea tbh.

**Comment by ByRodrigoSoares** [comment]
> > Já existe https://msfn.org/board/topic/182876-360-extreme-explorer-modified-version/ 
> > E eu gosto melhor do firefoxes.
> 
> Ou por que não tentar fazer o backport de uma versão mais recente do Firefox ESR usando uma equipe de membros, se possível, desde que você não se importe com as restrições do MPL 2.0? Além disso, ter um navegador chinês em nossos PCs definitivamente não é uma boa ideia tbh.

**@Feodor2 solution is to use base from other browsers such as Tor.seamokey**

**Comment by gdl-blue** [comment]
Mypal browser has less lag on Windows 7 than Windows XP. For example, when logging in to Discord, it prompts hCaptcha. on Windows 7, it works fine on Mypal, but on Windows XP, the browser freezes for like 30 seconds. It is the same version-28.4.0, but it acts differently   
other various sites that makes Mypal freeze on Windows XP does not freeze on Windows 7.
@Feodor2 is there a technical problem in XP that makes the browser slow? Faking Windows version to 7 does not help really

**Comment by ROBERT-MCDOWELL** [comment]
discord uses WASM

**Comment by gdl-blue** [comment]
Also this  login site, it does not freeze on Windows 7 Mypal but on XP. - https://nid.naver.com/nidlogin.login

this site freezes on XP even if webassembly is off

**Comment by ghost** [comment]
The problem is video acceleration.

**Comment by gdl-blue** [comment]
> 
> 
> The problem is video acceleration.

Hmm, I previously installed Windows 7 on a VM(host is my XP) excluding video driver and 3D acceleration, but it was still faster than XP with less(or no) freezing, with Mypal or Centaury.

(my PC is fast enough to run Windows 7, but please don't say to use Windows 7 because I have another computer that Windows 7 runs slow)

**Comment by gdl-888** [comment]
@artenaki

**Comment by gdl-blue** [comment]
> 
> 
> The problem is video acceleration.

Wait, you're actually correct!? I disabled WebGL(webgl.disabled;true) on XP's Mypal and it is not freezing anymore. Thanks.

**Comment by gdl-blue** [comment]
A few weeks ago, I tried Mypal on a Windows 10 computer somewhere, and it was very fast, not as fast as Chrome, but still much faster than running the same version of Mypal on Windows XP, like YouTube video page loads little(not "*a* little") slower than Chrome, while XP loads completely after like 30 seconds to a minute with a browser freezing. Faking the Windows version to Windows 7/10 doesn't work(also, why does the tab change to an ugly square style if I do that?). (the RAM capacity was similar.)

**Comment by ghost** [comment]
1. You should compare your internet speed between XP and Win10 with speedtest.net Because of MTU and TTL restrictions on XP (at least for me) the speed is limited to 60 kbytes/s on 3G modem. What is your internet connection?
2. Do you have hardware acceleration enabled in your browser? It works better in Win10.
3. MyPal uses the built-in ffmpeg libraries to decode avc/vp9 video, but maybe Win10 also uses hardware accelerated decoding.
4. The browser may be using some OS features that XP doesn't have.

Try Serpent browser with multiprocessing enabled. Desktop YouTube is a very heavy site, even for modern browsers like Firefox Quantum. Switch to the mobile version (by editing user agent) or try alternative lightweight Invidious interface.

By the way, in speedtest you can specify to use multiple connections or single connection. A single connection is always slower.
