### ISSUE TITLE
Problems with UouTube

### ISSUE THREAD

**Issue by kitaro1** [Feodor2/Mypal#172]
I already have 28.9.2 mypal and a serious matter. On YouTube, it prompts you:
We will stop supporting this browser soon. To get the best experience, update it.
In Mypal 28.9.1 it does not display a warning. I stay at mypal 28.9.1.

**Comment by ByRodrigoSoares** [comment]
![cats](https://user-images.githubusercontent.com/50956690/81367095-a2f14f00-90c2-11ea-9ce6-e27128ce05cd.jpg)
**We will no longer support this browser soon. To improve your experience, update your browser.**

**Comment by Feodor2** [comment]
The fail in 28.9.2 update, i am making next update asap,
