### ISSUE TITLE
28.9.2. Bookmarks toolbar, FireFTP addon

### ISSUE THREAD

**Issue by us66mo** [Feodor2/Mypal#173]
Hi, with new update I have to reload the bookmarks toolbar every time I start the browser, also the FireFTP addon no longer works. Went back to version 28.9.1 temporarily.

**Comment by lordpeluca** [comment]
too.

Also the extensions "Advanced Night Mode 1.0.9" and "Google Traslator for Pale Moon 2.0.0" stopped working.

Both worked perfectly in Mypal 28.9.1.

At the moment I am back to version 28.9.1.

Anyway, thanks a lot for the update.

**Comment by ByRodrigoSoares** [comment]
I was disappointed with this update, the bookmarks disappear every time I restart the browser

**Comment by ByRodrigoSoares** [comment]
The menu bar is buggy there are times when it doesn't work

**Comment by ByRodrigoSoares** [comment]
Returning to version 28.9.1, version 28.9.2 didn't work out many bugs

**Comment by Feodor2** [comment]
The update is a fail indeed, and i check mingw build only.
