### ISSUE TITLE
updata

### ISSUE THREAD

**Issue by JWOLemmon** [Feodor2/Mypal#174]
Hi, Bookmark bar is not displayed after updating to 28.9.2.
I tried to fix it manually, but the same symptom occurs when I reboot.
Also, all the passwords I remembered in 28.9.1 have disappeared.
(Win10 x64 Mypal 28.9.1_32bit → 28.9.2_32bit)

**Comment by ByRodrigoSoares** [comment]
The Menu Bar is also having problems, as the browser to return to normal

**Comment by JWOLemmon** [comment]
>restart the browser

Thanks  for your reply.
I'm using Pale Moon 28.9.3 on Win7 and Win10, but my beloved XP and Vista requires Mypal.
I hope that MayPal will be healed and well.

**Comment by Feodor2** [comment]
The fail in 28.9.2 update, i am making next update asap,

**Comment by JWOLemmon** [comment]
> Closed #174.

I understood and Immediately I upgraded to v28.9.3 and all issues were 
resolved.

I appreciate it very much.
