### ISSUE TITLE
v28.9.2 can not restore opened tabs after restart

### ISSUE THREAD

**Issue by Grishanenko** [Feodor2/Mypal#176]
XP SP2/SP3. Распаковка в отдельную директорию. Портабельность файлом browser/pmprt.mod
1. File - Restart...
2. Tools - Preferences - General: When mypal starts - show my windows and tabs from last time
3. Закрыть mypal. Запустить mypal. History - Restore previous session.
Все 3 способа не сохраняют вкладки.

**Comment by Feodor2** [comment]
The fail in 28.9.2 update, i am making next update asap,
