### ISSUE TITLE
28.9.2 not web.whatsapp.com compatible

### ISSUE THREAD

**Issue by tolengo** [Feodor2/Mypal#177]
28.9.2 not web.whatsapp.com compatible

**greetings from Buenos  #Aires!**
![esteee](https://user-images.githubusercontent.com/65049831/81456810-30d44500-916a-11ea-803a-b7f5fa0120af.png)

**Comment by ByRodrigoSoares** [comment]
**The MyPal Developer has already said that this update has failed and that he will make another update correcting all serious flaws in this released version.**

**Comment by ByRodrigoSoares** [comment]
It is best to return to using the previous version until all problems are fixed in a patch version. I returned to Mypal 28.9.1****
