### ISSUE TITLE
All versions. Facebook Videochat problem

### ISSUE THREAD

**Issue by tolengo** [Feodor2/Mypal#179]
Hi. 
Cant use facebook videochat. 

Under "permissions" there are no microphone and camera settings.

Thanks for your time.

![1](https://user-images.githubusercontent.com/65049831/81755331-e109bc80-948e-11ea-8f89-249f6b8ab545.png)
![2](https://user-images.githubusercontent.com/65049831/81755342-e6670700-948e-11ea-9141-744e3ea9b1da.png)

**Comment by Feodor2** [comment]
Mypal is not suitable for videochat and wont be, use centaury or other software. Actually i do not know is it will work in the cenatury, there is no way to check things on the facepuke without account which i do not have.

**Comment by AroKol78** [comment]
https://github.com/Feodor2/Mypal/issues/294#issuecomment-728908776

**Comment by Feodor2** [comment]
And https://github.com/Feodor2/Mypal/wiki/Vidochat-and-conference-stuff too
