### ISSUE TITLE
Include in ReactOS Applicantions Manager/repository

### ISSUE THREAD

**Issue by dapgo** [Feodor2/Mypal#18]
ReactOS has an app to install free software from a repository. 
At the moment, in the repository there are Firefox (v48, v28, v3.6) and K-meleon 75.1.
As Mypal/Newmoon works fine in reactOS, i understand that it should be included in order to make it available to more users.

**Comment by dapgo** [comment]
the installer is still the same, in fact this flavor of "respository" only contains links to files to be downloaded.

Information about steps to include your browser in the repository:
https://github.com/reactos/reactos/tree/master/base/applications/rapps
https://reactos.org/wiki/RAPPS

If you agree but you are busy let us know ;)


 the person who manages it  should be contacted.

**Comment by JoachimHenze** [comment]
I will take care of that today and add
https://github.com/Feodor2/Mypal/releases/download/27.9.3/mypal-27.9.3.win32.installer.exe
to rapps. Thank you for maintaining this great browser for the Windows XP community.
I hope MyPal will gain some popularity by that. Best regards!

**Comment by JoachimHenze** [comment]
![mypal27 9 3_running_on_reactos_0 4 9-rc-35-g3eb03ef](https://user-images.githubusercontent.com/33393466/42111185-cf4c5324-7be3-11e8-9072-03fb5544d69f.png)
Now it can be installed in reactOS with a single click! This issue can be resolved as fixed.

**Comment by Mouvedia** [comment]
reactos/rapps-db@ba36ba7

**Comment by Feodor2** [comment]
you are welcome
