### ISSUE TITLE
28.9.3 update erases bookmarks and preferences

### ISSUE THREAD

**Issue by cageeksquad** [Feodor2/Mypal#181]
I installed version 28.9.3 over version 28.9.1
as i did with the previous versions updates
the bookmarks and settings preferences (prefs.js file)
were written over.
Fortunately I kept backups
for those, I reinstalled version 28.9.1
IMY 28.9.3 is a buggy one.

**Comment by Feodor2** [comment]
Not confirmed, i checked update and install over no bookmarks and settings was deleted.
So tell how to reproduce this bug

**Comment by cageeksquad** [comment]
I downloaded and installed 28.9.3 again today,
as you say, bookmarks and settings are not affected
by updating from 28.9.1 to 28.9.3

So I was unable to reproduce the behavior I posted before.
