### ISSUE TITLE
Compatibility with Google Meet

### ISSUE THREAD

**Issue by Anish21864** [Feodor2/Mypal#183]
Tried to use Google Meet on Mypal Browser and it says that it doesn't work on this browser. 

![image](https://user-images.githubusercontent.com/62549298/82028632-88ffcf80-96b3-11ea-8385-f7677db9a078.png)

May I please know if this browser could access Google Meet in the future?

**Comment by kitaro1** [comment]
Tried to use Google Meet on Mypal Browser and it says that it doesn't work on this browser?
http://prnt.sc/sh8glq
Elegance...

**Comment by Anish21864** [comment]
Sorry Madam/Sir, but the version I have is 28.9.3 on x64 Operating System. I think x64 version is not compatible but I am not sure..

**Comment by kitaro1** [comment]
Old man.
No problem. http://prnt.sc/sh9mw8
I always install the portable version - I use the first installer window option.  I have a mypal on the second partition and has a USB stick - always logged in.

**Comment by Feodor2** [comment]
Mypal is not supposed to be compatible with this and ever wont.
Try centaury browser
https://github.com/Feodor2/Centaury
