### ISSUE TITLE
Maps.yandex.ru zoom bug

### ISSUE THREAD

**Issue by UJIbU4** [Feodor2/Mypal#185]
Hello. Mypal 32bit latest version. On windows XP when using city panorama feature at website maps.yandex.ru only 2 zoom levels are available - max zoom in or max zoom out, unlike stepping zoom on windows 7.

**Comment by Feodor2** [comment]
Not confirmed - have checked on winxp and win8, no difference noticed, zoom was stepping normally.

**Comment by UJIbU4** [comment]
It has normal stepping only when image is blurry and not fully loaded. Checked on real machine with windows XP + on official vmware image "IE8 Windows XP SP3" published by Microsoft. Maybe it requires something other than vcredist 2008 (included by default in vmware image) to be installed to work?

**Comment by UJIbU4** [comment]
Closed - looks like site-side bug.
