### ISSUE TITLE
Mozilla folder is created by Mypal  and Centaury

### ISSUE THREAD

**Issue by 444nonymous** [Feodor2/Mypal#19]
it's created at program startup and it's empty: "C:\Documents and Settings\user\Program Files\Mozilla\Extensions" No firefox installed, using Centaury with a new and clean profile.

Very good work, XP with x264 support integrated. Please consider using a better icon, why not keep the default HD firefox or palemoon icon? This is just a fork.

Thanks!

**Comment by Feodor2** [comment]
The first is the bug indeed i shall fix that, but the second may be not i am going to research.

**Comment by Feodor2** [comment]
fixed
