### ISSUE TITLE
New Reddit no longer working properly in MyPal

### ISSUE THREAD

**Issue by djmbs** [Feodor2/Mypal#190]
Issue reported by redditors here, rather detailed: https://www.reddit.com/r/bugs/comments/gtajo6/so_many_parts_of_the_new_reddit_doesnt_work_for_me/
Btw, it's exactly the same for old Chrome as can be seen here: https://www.reddit.com/r/bugs/comments/gt2rit/reddit_is_not_working_properly_with_old_chrome/

**Comment by Feodor2** [comment]
They insert into the script thing that is not supported on older browsers, who knows why they done it, is it ignorance of cheap labor or intended for drive away you from old hardware.
At least i say that it works fine on 360chrome 12 on winxp.
https://mathiasbynens.be/notes/globalthis
Shall think out, but i do not use reddit so for me personally this is not very important.

**Comment by djmbs** [comment]
Thanks! I hope they change it themselves, some users are getting angry.

**Comment by djmbs** [comment]
Found a working userscript solution: Here's the script:
// ==UserScript==  
// @name         reddit globalThis fix  
// @match        https://www.reddit.com/*  
// ==/UserScript==  
unsafeWindow.globalThis = window;

**Comment by Feodor2** [comment]
28.10.0 already fixed the issue.

**Comment by djmbs** [comment]
Awesome!
