### ISSUE TITLE
как отключить очистку кеша?

### ISSUE THREAD

**Issue by iyuter** [Feodor2/Mypal#192]
Подскажите пожалуйста, как отключить очистку кеша загруженых страниц и рисунков?
Она происходит при открытом браузере. Увеличение предельных значений в  browser.cache.* не помогло

**Comment by Grishanenko** [comment]
Самое смешное что я сам вчера обратил внимание что история полностью очищается ровно каждые 60 минут. Совпадение. И только 5 мин назад нашел причину.
uMatrix установлен?
chrome://ematrix/content/dashboard.html
Settings
Clear browser cache every __ minutes.

**Comment by iyuter** [comment]
Спасибо!!! я бы и не догадался, что причина в этом.
