### ISSUE TITLE
window not updating until resized (windows xp 64-bit)

### ISSUE THREAD

**Issue by flyod** [Feodor2/Mypal#193]
everything seems to work fine for the first few seconds but then any buttons pressed or anything typed wont refresh the display until the window has been resized. i already turned off hardware acceleration, it's a fresh install with no plugins. as far as i know, everything on the machine is as up-to-date as possible. the problem is not exclusive to mypal, firefox newer than 17 does the same thing, and the last builds of palemoon for xp do too, so im guessing its a problem on my end, but i've tried all i can think of.

**Comment by Feodor2** [comment]
Provide more details from open in the browser menu-help-Troubleshooting Information and general specs of the machine.

**Comment by flyod** [comment]
here are screenshots of the troubleshooting page, the browser renders pages fine, as you can see, but to take them i had to blindly scroll down the page, resize then maximize the window.
![001](https://user-images.githubusercontent.com/66396392/83786359-9845bd80-a660-11ea-8df4-a6b5b8fd9c5f.PNG)
![002](https://user-images.githubusercontent.com/66396392/83786362-9976ea80-a660-11ea-9186-c7707c602a3c.PNG)
![003](https://user-images.githubusercontent.com/66396392/83786369-9a0f8100-a660-11ea-8a33-f626f98ad4d5.PNG)
![004](https://user-images.githubusercontent.com/66396392/83786370-9b40ae00-a660-11ea-9779-378158de4b9c.PNG)
![005](https://user-images.githubusercontent.com/66396392/83786375-9bd94480-a660-11ea-9315-2a588a22545a.PNG)
![006](https://user-images.githubusercontent.com/66396392/83786379-9c71db00-a660-11ea-910c-85ae7633aa49.PNG)
the computer is an intel i5, 3.5ghz 8gb of ram amd radeon r7 video. the whole machine is technicaly too new to be able to run xp 64-bit, but i someone released an updated acpi.sys so that xp64 can run on newer computers, and pretty much all my hardware had drivers for xp still. i'm willing to accept that there may be some weird hardware incompatibility that means this will never work, but i'll try everything i can before i give up.

**Comment by Feodor2** [comment]
I had little business with i5s and no ever try use winxp there why
So try another videocard drivers and check if you have directx installed.

**Comment by flyod** [comment]
i've got directx fully up-to-date, and had the same problems with the default xp video driver. im willing to accept that it might just not work, but if you have any more ideas i'll try them. thanks for your help tho, i'll keep poking around and see if i can fix it myself.

**Comment by Culexamaxa** [comment]
I am running MyPal 28.91 32-bit on XP64.  I have not noticed this issue.

I am using a 990FX motherboard with AMD 8-core FX-8320 cpu and Nvidia GTX 750 TI graphics and 32GB DDR3 ram.

I have no clue as to why you'd be experiencing this, as I am not seeing anything similar.  I have PM 26 and 27 installed (v27 for xp), all 32-bit programs.  No issues such as this.  Additionally, firefox ESR 47 and esr 52, no similar issues.

Would be interested in knowing what this acpi.sys is.

**Comment by flyod** [comment]
the acpi.sys is here: https://retrosystemsrevival.blogspot.com/2019/10/updated-windows-xp-acpisys.html i doubt that could be the cause of the problem tho. 
i also noticed that just clicking on the menu bar will force the screen to redraw sometimes. it's just weird, especially since everything seems to work fine the first few seconds after you open the browser. when i get more time im going to see what it does with just my computer's onboard graphics.

**Comment by Feodor2** [comment]
Do you mean basic windows supervga driver?
Then try settings gfx.canvas.azure.backends;cairo

**Comment by flyod** [comment]
hmm. that changed things slightly, the page will redraw on it's own now, if you leave it for 20-30 seconds, but the tab bar still never changes.

**Comment by flyod** [comment]
finally figured out what the problem was on my xp64 machine. i talked to the person who did the updated acpi.sys and apparently i needed an updated hal.dll to go along with it, there is a timing issue in windows xp on the recent intel chipsets, he sent me the new hal.dll and all the browsers work perfectly now. thought id mention it again here in case anyone else has the problem in the future. guess ill close the issue too, since it wasn't a problem with mypal itself.
