### ISSUE TITLE
MSFN javascript error: instance is null

### ISSUE THREAD

**Issue by roytam1** [Feodor2/Mypal#2]
22:29:02.595 TypeError: instance is null
http://www.msfn.org/board/uploads/javascript_global/root_library.js.b81e42a4aedce2a07ccdb92a42198ea9.js?v=8c63769e95
Line 632:66

This doesn't happen in official build.

**Comment by roytam1** [comment]
So there is 2 lines missing in browser\branding\unofficial\pref\palemoon-branding.js:

```
// Enable Firefox compatmode by default.
pref("general.useragent.compatMode", 2);
```

**Comment by Feodor2** [comment]
Noticed
It is changed easy by the options - advanced - general - useragent mode.
