### ISSUE TITLE
Proposition

### ISSUE THREAD

**Issue by E-System33** [Feodor2/Mypal#20]
If Palemoon causes so many problems, Abandon It. It only creates problems. Plus their browser is slow and old. 
Why not try chromium or Firefox itself or others? 

You can cooperate with other coders. There are plenty of them who would like to help you make a new Mypal (or another name) 

Mypal should not die like this.

I use it even on Windows 10.

Don't hesitate to open a donation system. You deserve it. 

I advise you to take a break to think about it. 

You deserve it with all the stress. 

I hope Mypal will survive for all XP users and thanks again. 

The others don't hesitate to make suggestions or to correct me below ;)

**Comment by SaranSDS008** [comment]
Yeah, same here, Mypal should not die like this. There are better engines out there, which is open source, easy to backport, can have the browser as proprietary, etc. Palemoon is not the only browser out there. Also, there are many ppl to help you build a new browser @Feodor2 . If you need, you can take a break think on this though. If you don't have resources, try to open a Donation system, or Patreon or something similar. Also, You can reach out to many dev folks out there to have in the browser development.

**Comment by rubyFeedback** [comment]
"You can cooperate with other coders."

You mean you can "cooperate" with Google?

I am sure they are enthusiastic about listening to your "cooperation" ... :>

It's not as if Firefox has dwindled in a downwards spiral or something ...

"There are better engines out there"

Like ... which ones? The Google-based variants? No de-facto monopoly?

**Comment by NEO-SPECTRUMAN** [comment]
chromium is fc**n shit
only gecko firefox is good enough

**Comment by ByRodrigoSoares** [comment]
There is a possibility that @Feodor2 will continue with updates on the Mypal website http://www.mypal-browser.org/ or Palemoon may take down

**Comment by SaranSDS008** [comment]
> chromium is fc**n shit
> only gecko firefox is good enough

Nah, it's the Google's one, not the Core Browser/Engine. He could use Webkit Alternatively.

**Comment by Feodor2** [comment]
I told that already, personally shall not do any work with palemoon anymore, i think to take firefox directly.

Though anybody can take the mypal and continue the work, with or without my help. Only watch that rogue mypals may be infected with malware.

**Comment by Anbima** [comment]
@Feodor2
Do you mean that it works with Firefox.
Of course that would be very great.

**Comment by ByRodrigoSoares** [comment]
> 
> 
> I told that already, personally shall not do any work with palemoon anymore, i think to take firefox directly.
> 
> Though anybody can take the mypal and continue the work, with or without my help. Only watch that rogue mypals may be infected with malware.

Feodor@ Someone you trust could continue your project with your supervision without the Palemon knowing

**Comment by ROBERT-MCDOWELL** [comment]
I Know so many developers whom got back to XP since windows 10 is an absolute waste of time and waste!!!
many privacy laws are broken in win10 spying every move and click of the user, updating constantly, they should could windows orwell for the next version.

**Comment by Sen-nin** [comment]
Hello, Feodor2.

> I told that already, personally shall not do any work with palemoon anymore, i think to take firefox directly.

I think it is a great idea. A few days ago I installed Windows 7 SP1 on one of my Windows XP computers, ThinkPad T43 (Type 1871-39J) with Pentium M 1.73 GHz and 1.5 GB of RAM, to see how fast Firefox 92.0 was. Firefox 92.0 was twice faster than Firefox 52.9.0. Firefox 92.0 took only 145 seconds to open five websites on different tabs at the same time while Firefox 52.9.0 took 300 seconds to do the same job. I have a feeling that 92.0 may even work faster on XP.

**Comment by gdl-blue** [comment]
yeah. newer firefox uses multiprocesses and have faster JavaScript engine(Centaury and FF52 also supports too but you need to enable them by yourself, and it is still slower than FF92 because the JavaScript engine is slower)
