### ISSUE TITLE
Missing DLL on 27.9.1

### ISSUE THREAD

**Issue by esyede** [Feodor2/Mypal#20]
Hello.
I just installing Mypal 27.9.1 on windows xp professional 32bit but found a missing dll error as shown on [this image](https://prnt.sc/jfrboo)

But when I click the OK button the installer works just fine ([image](http://prntscr.com/jfrhgp)).
Mypal 27.9.0 works just fine. No dll error.

Is this a bug on this Mypal version? or,
 it's just my machine didn't have that dll file?

By the way, thanks for this awesome project!

**Comment by Feodor2** [comment]
There is no such dll, it is something wrong on your end. Check for rootkits, possible malware, trojans. And other shitware can cause this bug.

https://prnt.sc/jfscbu.

**Comment by esyede** [comment]
Oh, thank's!
