### ISSUE TITLE
Kiosk Mode

### ISSUE THREAD

**Issue by josh4680** [Feodor2/Mypal#203]
Hello, this is a great browser, I am trying to find out if it is possible to launch in kiosk mode (or equivalent, similar to  mozilla -kiosk switch) so that the user may not have access to any toolbars or functions.  Or disable the green MyPal menu?
Thank you

**Comment by Feodor2** [comment]
You did not tell what you found
So here a link for another one
https://superuser.com/questions/977912/firefox-hide-everything-except-content-area-of-the-browser
