### ISSUE TITLE
Не работает Keyscrambler

### ISSUE THREAD

**Issue by fastnetcom** [Feodor2/Mypal#206]
Не работает Keyscrambler.

**Comment by Feodor2** [comment]
Вообще не знаю что это такое.
Поэтому распишите пошагово конкретно
1. версии системы и браузера
2. какая конкретно ошибка
3. пример как воспроизвести.
4. пример как оно должно работать

**Comment by fastnetcom** [comment]
Программа Keyscrambler https://www.qfxsoftware.com/
Версия XP SP3, последняя версия браузера MyPal
Иконка программы в трее становится зеленой, когда активно окно браузера, что говорит что программа работает. Можно это проверить в любом из браузеров.
В данном случае иконка остается желтой, что говорит что программа не функционирует.

**Comment by Feodor2** [comment]
вот может это поможет
https://mega.nz/file/tbwRGAqA#v6DF5jTShej_LKZOtJYJqPhjvA1imfNf97Ssp0s4csY
оно подделает имя программы как фаерфокс

**Comment by fastnetcom** [comment]
К сожалению, это не помогло. Может быть можно обратиться к авторам программы чтобы узнать как это исправить...

**Comment by Feodor2** [comment]
тогда переименуйте сам файл программы mypal.exe

**Comment by fastnetcom** [comment]
Спасибо, так работает.

**Comment by fastnetcom** [comment]
Но почему-то перестали работать ссылки из почтового клиента...
Раньше при нажатии они открывались в браузере.

**Comment by Feodor2** [comment]
в HKEY_CLASSES_ROOT реестре переименовать все mypal.exe по поиску.

**Comment by fastnetcom** [comment]
Спасибо.

**Comment by fastnetcom** [comment]
> вот может это поможет
> https://mega.nz/file/tbwRGAqA#v6DF5jTShej_LKZOtJYJqPhjvA1imfNf97Ssp0s4csY
> оно подделает имя программы как фаерфокс

Можно ли сделать, чтобы браузер подделывал также и версию виндоус, вместо XP писал виндоус 7, например по кнопке, если сайт блокирует работу с XP?

**Comment by Feodor2** [comment]
в about:config сделать запись general.useragent.override.<сайт> смотрите как по другим сайтам сделано или дополнгения типа useragent switcher.
