### ISSUE TITLE
NEWmoon browser has problems, but ...

### ISSUE THREAD

**Issue by joeturnes** [Feodor2/Mypal#21]
I think i'm going to TRY to use NEWmoon on my very old 32 bit XP desktop for shopping & banking - it is updated each week!(I wonder why! Kind of insane, almost.) Hopefully those websites will work in NEWmoon ... 
http://o.rthost.win/palemoon/?sort=date&order=desc
& use Mypal for the rest of my browsing until at least ebay is selling cheap windows 11 desktops. None yet.
I was gonna get a cheap $60!!! windows 10 desktop, but good old MS recently decided to stop supporting W10 in about 4 years! & there's a 50/50 chance that one's current W10 machine will NOT be able to aceept the W11 upgrade! I can't WAIT to hear the uproar on dat! lol
I was not able to install PALEmoon on my 32 bit XP machine.
& NEWmoon has problems that MYpal does not ... 
1. youtube videos don't work! (solution?)
2. can not install   deduplicate-tabs  25.1.0 addon  (solution?)
3. can install Suspend background tabs 1.01 BUT IT DOESN'T WORK! - ESSENTIAL IF YOU DEAL WITH A LOT OF TABS & YOU HAVE A VERY OLD MACHINE lol (solution? i guess use a lot less tabs lol)

**Comment by rubyFeedback** [comment]
Dude, is there any structure in the text above? That was painful to read ...

**Comment by l29ah** [comment]
Consider GNU/Linux.

**Comment by chermany4ever** [comment]
Linux still have problems with lots of drivers for lots of different hardware that even win98 supported. It may work if you have some very generic standard basic hardware and you accept half working hardware with some workaround malfunctions. Other option is selling your good ol' hardware and buying only Linux well supported one.

**Comment by gdl-blue** [comment]
offtopic from this issue, but does anyone have Mypal version 28.3.1 installer?

**Comment by chermany4ever** [comment]
I was testing NEWmoon and it stinks. A lot of sites fail to load and has way too many bugs. Don't even bother. Not worthy.

**Comment by ByRodrigoSoares** [comment]
Newmoon is already way behind Mypal if we use this browser it would be a big step backwards as there are many incompatibilities

**Comment by chermany4ever** [comment]
After further testing I've found this NEWmoon version:

https://retrosystemsrevival.blogspot.com/2019/08/pale-moon-28-xp.html

It seems to be working OK and addons compatible.

**Comment by Feodor2** [comment]
If roytam will be careful, they will not able to do anything bad.
Go to his form for any further questions.
https://msfn.org/board/topic/182647-my-browser-builds-part-3/
