### ISSUE TITLE
browser.tabs.insertAllAfterCurrent not implemented in Mypal 28.11.0

### ISSUE THREAD

**Issue by letmeindude** [Feodor2/Mypal#212]
It seems that **browser.tabs.insertAllAfterCurrent** is not implemented in Mypal 28.11.0 like in Pale Moon 28.11.0?

**Comment by Feodor2** [comment]
Uh yes i missed, - next time then, meanwhile you can try implement it yourself, write manually the setting and put true.

**Comment by letmeindude** [comment]
I did, but it doesn't work. Nothing changes. I tested this on a clean profile.

**Comment by Feodor2** [comment]
Well, then elaborate what you expected. I poked the setting in the original palemoon too and did not notice changes.

**Comment by letmeindude** [comment]
You are right, I expected all new tabs, even from bookmarks, to be opened after the current tab, but maybe that's not the by design.

**Comment by kitaro1** [comment]
Palemoon 28.11.0 browser.tabs.insertAllAfterCurrent the default is false. Setting it to true does not show changes.
Redundant setting for now.

**Comment by letmeindude** [comment]
https://forum.palemoon.org/viewtopic.php?t=24802&p=194510#p194510

**Comment by letmeindude** [comment]
Final results, with proof:

Pale Moon (works) https://postimg.cc/hfcK1tfv
Mypal (doesn't work) https://postimg.cc/yDNB2phz

Tested using clean profiles.

**Comment by Feodor2** [comment]
Did you manually set the setting to true?

**Comment by letmeindude** [comment]
Yes.

**Comment by Feodor2** [comment]
Then i do not know, because when i set the setting to true it works same as on the Pale Moon.

**Comment by letmeindude** [comment]
Thank you, Feodor2. I'm very sorry for wasting your time. It seems that I didn't choose **boolean** when creating browser.tabs.insertAllAfterCurrent. So after deleting it and creating it again, browser.tabs.insertAllAfterCurrent works as expected.
