### ISSUE TITLE
"Sandboxing is not allowed" ?

### ISSUE THREAD

**Issue by hue4** [Feodor2/Mypal#215]
I'm unable to stream anything from familiar sites like livetotal.net.  Instead I'm receiving the message "Sandboxing is not allowed" and am about ready to cry.

How do I get rid of this so-called 'sandboxing'?  I don't know what it is, but it is screwing up my life!  PLEASE, Help!

**Comment by Feodor2** [comment]
I don't get this error, how to reproduce?

**Comment by hue4** [comment]
http://www.livetotal.tv/c/baseball/south-korea-kbo-league/23-07-2020/lg-twins-vs-kt-wiz/1/ 

----  'Link 1'  is doing it as I'm typing, 6:21 EDT

**Comment by Feodor2** [comment]
No this error too, though i block all evil nasty domains which are not red in the picture, red means they unblocked.
![image](https://user-images.githubusercontent.com/19492771/88293970-59e58a00-cd04-11ea-9094-fb963dd26635.png)

**Comment by hue4** [comment]
I've found different sources for video on that site, so it hasn't bothered me since then, but I still get the "Sandboxing is not allowed" message on this and a few other sites.  

What is Sandboxing?
