### ISSUE TITLE
Releases Page

### ISSUE THREAD

**Issue by smaragdus** [Feodor2/Mypal#22]
@Feodor2 
Why don't you publish binaries to [Mypal releases page](https://github.com/Feodor2/Mypal/releases). Most of the GitHub projects I follow use "releases" page not only for source code but for binaries as well.

**Comment by Feodor2** [comment]
Yes i would like to to put binaries here, i can enable automatic update feature then, but github not accept it - too big size. It may possible in the github.io but do not know how, no free time to do inquire as well.

**Comment by smaragdus** [comment]
@Feodor2 

> Yes i would like to to put binaries here, i can enable automatic update feature then, but github not accept it - too big size.

Are you sure? For example [ONLYOFFICE](https://github.com/ONLYOFFICE/DesktopEditors/releases), [Toxygen](https://github.com/toxygen-project/toxygen/releases), [VNote](https://github.com/tamlok/vnote/releases) releases pages host files far bigger than [Mypal](https://github.com/Feodor2/Mypal/releases).

**Comment by Feodor2** [comment]
Now i could upload without error! Thank you for point this!
