### ISSUE TITLE
Somewhat annoying CAPTCHA screen when signing into LMCU.org (3% checking!!)

### ISSUE THREAD

**Issue by joeturnes** [Feodor2/Mypal#221]
In  www.LMCU.org   i click "Online Banking Login" & then enter my userid & click "Login".
& a CAPCHA screen comes up that says ...
"Lake Michigan Credit Union has deployed this CAPTCHA in an attempt to verify that this is a valid
user requesting access to Online Banking. Please fill in the field below with the information contained
within the image."
This captcha screen can be duplicated if you are not a member of LMCU by just putting in any characters for the userid.
I, as a member, can however sign in after i enter the captcha characters. & if i do enuf things inside the website, the somewhat annoying captcha screen will come up again & again - even when signing off. lol
LMCU says this is for security purposes because i am using window XP & an "outdated" browser.
Can anything be done to Mypal(or do i need to change my mypal setting(s)?) - if not, i'll just put up with the above - it's worth it. Why? --> 
3(THREE!)% checking!!  Rate has not changed since 2012!
http://www.lmcu.org/personal/banking/checking-accounts/max-checking

**Comment by Feodor2** [comment]
Try set useragent for newer windows
**general.useragent.lmcu.org;Mozilla/5.0 (Windows NT 6.1; WOW64; rv:78.0) Gecko/20100101 Firefox/78.0**

**Comment by joeturnes** [comment]
Your suggested change to about:config made no difference. 
I do NOT get the CAPCHA screen when i try to sign on lmcu.org with the last version of firefox esr browser, but i sure don't want to use THAT OLD browser for banking for LMCU or any institution!
When was it last updated?! lol
I have a 32 bit xp machine, btw.

**Comment by joeturnes** [comment]
The last version of FIREFOX released for windows XP was 52.9.0esr.
https://www.mozilla.org/en-US/firefox/enterprise/#download
One does NOT want to use that browser - especially for banking - very old!!

Again, in Mypal i went into    about:config

& created your suggested new string
general.useragent.override.lmcu.org

with your suggested value of 
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:78.0) Gecko/20100101 Firefox/78.0

I restarted the browser & still get the annoying capcha screen as soon i try to sign into lmcu.org

**Comment by Feodor2** [comment]
Then the value is to be about firefox 52
Mozilla/5.0 (Windows NT 5.1; rv:52.0) Gecko/20100101 Firefox/52.0

**Comment by joeturnes** [comment]
Thanks - that worked - no more captcha screens! 
Tho i wonder if this mypal override with firefox 52.0 is as SECURE as WITHOUT such an override & me having to satisfy the capcha screens earlier.

**Comment by Feodor2** [comment]
Its by site design and in not related to the security at all,
