### ISSUE TITLE
Sites not working

### ISSUE THREAD

**Issue by mypalpal** [Feodor2/Mypal#222]
github signup at github.com/join would not work, kept on looping at verification captcha page despite correct responses
accuweather site radar does not working at all, only shows blank screen: accuweather.com/en/gb/national/weather-radar
scrolling menus not working for coronavirus.data.gov.uk/cases (working in chrome 49)
nationwide.co.uk does not pass final verification loggin (works in firefox 49)

mypal is otherwise solid so far and fast!!

**Comment by mypalpal** [comment]
Thanks for the fast response, I'm trying to work out what the setting could be that allows my old firefox to load these pages but somehow blocks mypal?? Do you have any ideas based on the content you saw I was having difficulty with? Only extension I can think of that might break them is ublock?? Do my about:config settings in firefox also effect maypal? hmmm??

**Comment by Feodor2** [comment]
Do not use settings from the firefox, launch with the vanilla profile to check. The begin apply settings one by one.
