### ISSUE TITLE
расширение

### ISSUE THREAD

**Issue by agt007** [Feodor2/Mypal#224]
где можной найти ублок для версии 28.12.0

**Comment by agt007** [comment]
PDF Viewer
uBlock Origin
Browsec pm-fixed

**Comment by agt007** [comment]
> 
> 
> где можной найти ублок для версии 28.12.0
PDF Viewer
uBlock Origin
Browsec pm-fixed

**Comment by kitaro1** [comment]
https://github.com/gorhill/uBlock-for-firefox-legacy/releases/download/firefox-legacy-1.16.4.24/uBlock0_1.16.4.24.firefox-legacy.xpi

**Comment by agt007** [comment]
> 
> 
> https://github.com/gorhill/uBlock-for-firefox-legacy/releases/download/firefox-legacy-1.16.4.24/uBlock0_1.16.4.24.firefox-legacy.xpi

спасибо огромное
