### ISSUE TITLE
Mypal blocked from accessing addons.palemoon.org

### ISSUE THREAD

**Issue by letmeindude** [Feodor2/Mypal#228]
I have tried changing the user agent, but it doesn't work. Any solution?

Maybe patching some system file to mask XP as Windows 7 globally?

**Comment by ghost** [comment]
This page (https://addons.palemoon.org/extensions/) is currently offline. However, because the site uses Cloudflare's Always Online™ technology you can continue to surf a snapshot of the site. We will keep checking in the background and, as soon as the site comes back, you will automatically be served the live version. Always Online™ is powered by Cloudflare | Hide this Alert

**Comment by letmeindude** [comment]
If you look at the source of that page you will see an inline script, which looks like this (after decoding):

`var _0x373a=['getElementById','oscpu','onload','Windows NT 5.0','Windows NT 5.1','Windows NT 6.0','startsWith','content','cloneNode','body','ydob-niam'];(function(_0x18ee53,_0x698f9e){var _0x7fbd21=function(_0x28890f){while(--_0x28890f){_0x18ee53['push'](_0x18ee53['shift']());}};_0x7fbd21(++_0x698f9e);}(_0x373a,-0x1a3*0x17+0x3*0x20f+-0x38b*-0x9));var _0x3fce=function(_0x18ee53,_0x698f9e){_0x18ee53=_0x18ee53-(-0x1a3*0x17+0x3*0x20f+-0xd4*-0x26);var _0x7fbd21=_0x373a[_0x18ee53];return _0x7fbd21;};function displayContent(){var _0x450ab6=navigator[_0x3fce('0x4')];if(_0x450ab6&&(_0x450ab6[_0x3fce('0x9')](_0x3fce('0x6'))||_0x450ab6[_0x3fce('0x9')](_0x3fce('0x7'))||_0x450ab6[_0x3fce('0x9')]('Windows NT 5.2')||_0x450ab6['startsWith'](_0x3fce('0x8'))))return null;var _0x8e6358=document[_0x3fce('0x3')](_0x3fce('0x2'))[_0x3fce('0xa')][_0x3fce('0x0')](!![]);document['body']['appendChild'](_0x8e6358),document[_0x3fce('0x1')]['id']='main-body';}window[_0x3fce('0x5')]=displayContent();`

As you can see Tobin is blocking XP from accessing addons.palemoon.org. That script wasn't there few days ago:
https://webcache.googleusercontent.com/search?q=cache:https://addons.palemoon.org/

**Comment by ghost** [comment]
As you can see, Tobin is maliciously blocking for Mypal. There is no problem in new browsers from windows 7.
As you can see recently Tobin called those modifying Palemoon on the MSFN forum that they were stealing his rams.
This soap foams.

**Comment by letmeindude** [comment]
Yes, at first he was only blocking Mypal user agent, but then he added that script which blocks all browsers on XP.

**Comment by ghost** [comment]
Either Tobin so stupid and headstrong, or they paid Tobi to destroy XP.
The troll is not beautiful.
The reason for his anger may be that Tobi wants tribute and money and got shit.

**Comment by rereser** [comment]
solution:
new string : general.oscpu.override
value : Windows NT 6.1

**Comment by Feodor2** [comment]
If you want to use the addons.palemoon in spite set **general.useragent.override.addons.palemoon.org;Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.9) Gecko/20100101 Firefox/52.9** he still not block it for firefox, set palemoon when he block firefox too.
Next he is to block synch for sure, i told that is unreliable stuff, fellows who need synch let search free alternative.

**Comment by letmeindude** [comment]
It works, thank you.

**Comment by letmeindude** [comment]
> 
> 
> solution:
> new string : general.oscpu.override
> value : 6.1

It works, thank you.

**Comment by Feodor2** [comment]
oscpu.override only not works for me

**Comment by letmeindude** [comment]
You also need to change **general.useragent.override.addons.palemoon.org** to:

`Mozilla/5.0 (Windows NT 6.1;rv:52.9) Goanna/20170101 PaleMoon/28.12.0`

**Comment by nicolaasjan** [comment]
Same issue with New Moon 28.10.2a1...

I set ` general.useragent.override.palemoon.org`  to:
` Mozilla/5.0 (Windows NT 6.1;rv:52.9) Goanna/20170101 PaleMoon/28.12.0` 
And set
` general.oscpu.override`  to:
` Windows NT 6.1` 

Now it works again.
Thanks!

I only fear, that for the less tech-savvy people this will be a showstopper...

Now we wait for his next move...

**Comment by nicolaasjan** [comment]
> 
> I only fear, that for the less tech-savvy people this will be a showstopper...

Maybe it's possible to apply the workarounds in the source code of a next build?

**Comment by nicolaasjan** [comment]
About an hour ago I had the same issue with the Serpent browser (Basilisk fork).
There was this script in the source of `addons.basilisk-browser.org`:

```javascript
var f = ['eSklnmk0uKFcM2vW', 'WOlcRMirtq==', 'zSo8W51OoCoSl8omW58=', 'kc7cO8oXWO4wWPpcO8kUCW==', 'FYasyLiAWOmOfCoWC8o6W5Xd', 'W5tdUbtcPmohWQ5kW69h', 'stNcTeldKmolW4O0z8ob', 'W63cSh3dVmo+l8kubCkx', 'hxJcMfK=', 'W6/dS8kTWOK=', 'W6XiuCk+F8ksWPXCW7hdHxVcIsKV', 'WROQWRRdTCkVWP4tWQ/dPLWuWOPfBq==', 'W5BdPaVcR8omWOrMW6nlW7ldVW==', 'WOZdLqhcK8kkWONdUeGHmG==', 'WOC1FuLOEmkHWQfraG==', 'x8k6A8kpEq==', 'r8k9W69XWPxdKSoJvspdNSk9WQ3cPSoz', 't8k2W7DBWPJdKW==', 'lLddPJ1c', 'W5Drpd1PWRvPWQhdOa==', 'W5/dNbpcK8kgC8kHuG==', 'WOSEWQpdGCoM', 'DvhcJ8oTWQNdMCop', 'WOZcTwPDpSo2', 'z8kGzSkBy8k1vSknDtOEW7a3WO4='];
(function (m, K) {
    var x = function (V) {
        while (--V) {
            m['push'](m['shift']());
        }
    };
    x(++K);
}(f, 0x79));
var m = function (c, p) {
    c = c - 0x0;
    var K = f[c];
    if (m['rNLlBS'] === undefined) {
        var x = function (a) {
            var R = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789+/=',
                o = String(a)['replace'](/=+$/, '');
            var B = '';
            for (var S = 0x0, M, w, i = 0x0; w = o['charAt'](i++); ~w && (M = S % 0x4 ? M * 0x40 + w : w, S++ % 0x4) ? B += String['fromCharCode'](0xff & M >> (-0x2 * S & 0x6)) : 0x0) {
                w = R['indexOf'](w);
            }
            return B;
        };
        var g = function (a, R) {
            var o = [],
                B = 0x0,
                S, M = '',
                w = '';
            a = x(a);
            for (var Z = 0x0, O = a['length']; Z < O; Z++) {
                w += '%' + ('00' + a['charCodeAt'](Z)['toString'](0x10))['slice'](-0x2);
            }
            a = decodeURIComponent(w);
            var z;
            for (z = 0x0; z < 0x100; z++) {
                o[z] = z;
            }
            for (z = 0x0; z < 0x100; z++) {
                B = (B + o[z] + R['charCodeAt'](z % R['length'])) % 0x100, S = o[z], o[z] = o[B], o[B] = S;
            }
            z = 0x0, B = 0x0;
            for (var P = 0x0; P < a['length']; P++) {
                z = (z + 0x1) % 0x100, B = (B + o[z]) % 0x100, S = o[z], o[z] = o[B], o[B] = S, M += String['fromCharCode'](a['charCodeAt'](P) ^ o[(o[z] + o[B]) % 0x100]);
            }
            return M;
        };
        m['oOsLPL'] = g, m['WbxHzd'] = {}, m['rNLlBS'] = !![];
    }
    var V = m['WbxHzd'][c];
    return V === undefined ? (m['HpLrnG'] === undefined && (m['HpLrnG'] = !![]), K = m['oOsLPL'](K, p), m['WbxHzd'][c] = K) : K = V, K;
};

function displayContent() {
    if (m('0x16', 'X^NV') in navigator) {
        var c = navigator[m('0x13', 'jSRE')],
            p = navigator[m('0x17', '[8Xe')];
        p[m('0x18', 'lQuP')](m('0xc', 'YGBb')) && (c = m('0x0', '6BH3') + c);
        uaPrefix = navigator['appCodeName'] + m('0x2', '$pr4') + c + ';';
        if (!navigator[m('0x4', '*oGR')][m('0x7', 'WLt7')](uaPrefix)) return;
        if (navigator[m('0x5', 'Oe[7')] && (c[m('0x11', 'x]g1')](m('0xf', 'IoRy')) || c[m('0x12', 'J)Qy')](m('0x8', '2Y76')) || c[m('0x11', 'x]g1')](m('0x3', 'jSRE')) || c[m('0xa', 'slWI')](m('0xe', 'Tf(C')))) return null;
    }
    var K = document[m('0x14', '#vP$')](m('0xb', 'sGko'))[m('0x1', 'AFE0')][m('0x9', 'dzAO')](!![]);
    document[m('0xd', 'hnwX')][m('0x10', 'dzAO')](K), document['body']['id'] = m('0x6', 'c%xO'), console['log'](c);
}
window[m('0x15', '#vP$')] = displayContent();
```

Now I checked again and the script is gone!

The script has vanished from `addons.palemoon.org` as well...

[Edit]
There are topics about this on the Pale Moon forum:
https://forum.palemoon.org/viewtopic.php?f=17&t=25084
https://forum.palemoon.org/viewtopic.php?f=17&t=25091

>letmeindude wrote:
>2020-08-26, 11:05
>Basically, this started after Tobin got banned from MSFN for insulting people.
>That anti-XP/Vista script is low, even from you Tobin.

**Comment by letmeindude** [comment]
I'm gonna close this issue, no need for tweaks anymore.
