### ISSUE TITLE
Order of patches?  Build fails at undefined "InitializeSRWlock"

### ISSUE THREAD

**Issue by Tony0945** [Feodor2/Mypal#23]
I applied the winxp patch, then the winxp_a patch to the Palemoon 28.2.1 sources and it failed with the above error.  Do the patches all affect independent files? Or is the order of patching important?

I had built Pale Moon 28.2.1 successfully and tested it. Then I applied the patches as I said, ran ./mach clobber and ./mach build and encountered the above error. Details to folow.

**Comment by Tony0945** [comment]
b:\PM28.2.1_Release\media\ffvpx\compat/w32pthreads.h(103): error C4013: 'InitializeSRWLock' undefined; assuming extern returning int
 1:55.44 
b:\PM28.2.1_Release\media\ffvpx\compat/w32pthreads.h(113): error C4013: 'AcquireSRWLockExclusive' undefined; assuming extern returning int
 1:55.44 
b:\PM28.2.1_Release\media\ffvpx\compat/w32pthreads.h(118): error C4013: 'ReleaseSRWLockExclusive' undefined; assuming extern returning int
 1:55.44 
b:\PM28.2.1_Release\media\ffvpx\compat/w32pthreads.h(128): error C4013: 'InitOnceBeginInitialize' undefined; assuming extern returning int
 1:55.44 
b:\PM28.2.1_Release\media\ffvpx\compat/w32pthreads.h(131): error C4013: 'InitOnceComplete' undefined; assuming extern returning int
 1:55.44 
b:\PM28.2.1_Release\media\ffvpx\compat/w32pthreads.h(137): error C4013: 'InitializeConditionVariable' undefined; assuming extern returning int
 1:55.44 
b:\PM28.2.1_Release\media\ffvpx\compat/w32pthreads.h(149): error C4013: 'WakeAllConditionVariable' undefined; assuming extern returning int
 1:55.44 
b:\PM28.2.1_Release\media\ffvpx\compat/w32pthreads.h(155): error C4013: 'SleepConditionVariableSRW' undefined; assuming extern returning int
 1:55.44 
b:\PM28.2.1_Release\media\ffvpx\compat/w32pthreads.h(161): error C4013: 'WakeConditionVariable' undefined; assuming extern returning int
 1:55.45 
 1:55.50

I had not applied the ffvpx patch, because the target processor is a Phenom II that does not support the 
AVX2 instruction.

**Comment by Feodor2** [comment]
> I had not applied the ffvpx patch

Thats why you have the error. If you want use ffvpx, which is ffmpeg libraries for video playback on winxp, their patch is required too.

Soon i shall write the howto page about building from source and patching

**Comment by Tony0945** [comment]
By inspection I see that the patch order doesn't matter because they patch different files.

**Comment by Feodor2** [comment]
This is became not actual so closed.
