### ISSUE TITLE
ffmpeg update

### ISSUE THREAD

**Issue by AroKol78** [Feodor2/Mypal#232]
Please update ffmpeg (media/ffvpx),roytam1 has ffmpeg 3.4.8

**Comment by Feodor2** [comment]
I try update in the next mingw build to look if it will be better.

**Comment by AroKol78** [comment]
Mypal update from WINNT_x86-msvc/en-US/mypal.win32.complete.mar not mingw WINNT_x86-gcc3/en-US/mypal.mingw32.complete.mar

win32=mingw32 or win32<>mingw32 ?

**Comment by Feodor2** [comment]
Actually they both win32, mingw32s only for naming distinct.
A see ffmpeg 3.4.8 is old too, most recent version is 4.3.

**Comment by AroKol78** [comment]
Version 4.3 may have high hardware requirements (winxp only d3d9).
Find version 4.0 "Dropped support for building for Windows XP" [https://github.com/FFmpeg/FFmpeg/blob/master/Changelog](url)

**Comment by Feodor2** [comment]
> Version 4.3 may have high hardware requirements

I do not think so, did you know that original palemoon also "Dropped support for building for Windows XP".

**Comment by AroKol78** [comment]
- original palemoon for win7+ = ffmpeg  4.0.2 https://github.com/MoonchildProductions/UXP/blob/release/media/ffvpx/README_MCP#L3
- mypal for winxp = ffmpeg 3.4.2 https://github.com/Feodor2/Mypal/blob/Mypal_Release/media/ffvpx/README_MCP#L3
- roytam1 for winxp = ffmpeg 3.4.8 https://github.com/roytam1/UXP/blob/custom/media/ffvpx/README_MCP#L3
- ffmpeg 4.0 Dropped support for building for Windows XP https://github.com/FFmpeg/FFmpeg/blob/master/Changelog#L211

**Comment by Feodor2** [comment]
I have another questions
why it duplicates vp8 vp9 decoders, which have another media libs.
can play hevc but it is not enabled, does hevc used in the web today.

**Comment by AroKol78** [comment]
hevc is older, use mobile phone hw accelerate 140p-360p 
youtube for computer use v9: 480p 720p+
if prefere hevc only size video 140p-360p on youtube
google search vp9 vs hevc
https://blog.programster.org/comparing-vp9-and-x265-hevc
https://blogs.gnome.org/rbultje/2015/09/28/vp9-encodingdecoding-performance-vs-hevch-264/
https://bitmovin.com/vp9-vs-hevc-h265/

**Comment by AroKol78** [comment]
my gpu (NVIDIA GeForce 8600 GT 512MB) support Hardware hevc H264 Decoding
it doesn't matter for winxp (not support winxp)
firefox use ffvpx
ffvpx faster,better (about:config    media.ffvpx.enabled=true)
libvpx vs ffvpx
https://forum.palemoon.org/viewtopic.php?t=13086
https://bbs.archlinux.org/viewtopic.php?id=215108

**Comment by AroKol78** [comment]
win32=mingw32 or win32<>mingw32 ?
win32<>mingw32 true
win32 cpu SSE2
mingw32 cpu SSE

**Comment by Feodor2** [comment]
Finally i have updated, though disabled vp8-9 there, tried to make hevc playing but failed, https://tools.woolyss.com/html5-audio-video-tester/ lights them green but no video only sound. What i missed er? VLC player plays hevc fine on winxp.

Also it turned out that ffmpeg also responsible for playing mp3, if ffvpx disabled mp3 is not played, so i had to add mp3 decoder. 

If ffmpegs vpx decoders better, then i shall enable them again and disable old ones. Now we are to check if updated ffmpegs is better then old at all, next i can update default release.
Updated files in the mingw build #126.

mingw32 is win32 bit not the same
And mingw built without sse2, but i did not check if it works, yet no non see2 machines around.

**Comment by AroKol78** [comment]
Intel Core 2 Duo E6550 2333 MHz mmx sse see2 sse3 ssse3 em64t vt-x
NVIDIA GeForce 8600 GT 512MB
winxp3sp 2gb

basilisk52 and mypal28.12 and Mypal-28.13.0-mingw32
 - not play video and sound all > AV1 (if enable media.av1.enabled in Basilisk52 problematic play and cpu 90%)
 - not play video and sound     > H.264/AVC High@L4
 - not play video and sound     > H.263 BaseLine@1.0
 - not play video                  all > H.265 (sound play)
 - not play video and sound     > MPEG-4 Visual Advanced Simple@L5
 - not play video and sound     > MPEG-4 Visual Advanced Simple@L3 (green !?)
 - not play video and sound     > sample.amr
 - all format sound play ok

things I noticed
- general same Mypal-28.13.0-mingw32 a little more use cpu
- problem MIME type or not format support
  - play ok H.264/AVC Baseline@L3.0
  - not play H.264/AVC High@L4
  - H.265 only sound play
  - green and not play MPEG-4 Visual Advanced Simple@L3

Mypal-28.13.0-mingw32 serious problem with sound NASA tv: https://www.nasa.gov/multimedia/nasatv/index.html#public

**Comment by AroKol78** [comment]
- VLC links to source codecs at the bottom of the page https://www.videolan.org/projects/ All Projects
- LAVFiltersXP https://github.com/3dyd/LAVFiltersXP
  -0.70.2 last for xp
  -0.74.1.9 for xp unfinished project

**Comment by Feodor2** [comment]
Look new mingw build of centaury.
The updated ffmeg plays fine all the same, it may be can play m2ts and qt as hevc too, but its never made to be played in the browser side, there code in dom/media also to be updated. 
libvpx is used by encoders, these are needed only for webrtc i try disable it in mypal next.

**Comment by AroKol78** [comment]
- all off plugins ,centaury-20200918214808.mingw32 , basilisk52 and mypal28.12 same work https://tools.woolyss.com/html5-audio-video-tester/ ( not play m2ts and qt)
- mypal28.12,centaury-0.11.0,centaury-20200918214808.mingw32 not sound error on NASA tv (only sound error in Mypal-28.13.0-mingw32)
- media.mediasource.webm.enabled switch codecks on youtube avc1<>v9 (avc1 lack 1440p)

**Comment by AroKol78** [comment]
centaury-20200918214808.mingw32 switch to true
general.useragent.compatMode.gecko
general.useragent.compatMode.firefox

**Comment by Feodor2** [comment]
Ah thats such a weird. Set firefox compat in the mypal and sound will be played good there too. 
We are to update browser code for playing more formats, shall look on new firefox code.

**Comment by AroKol78** [comment]
centaury-20200918214808.mingw32 sometimes mistakes (Basilisk52 no error in the same settings)
- Invalid draw target type specified: 3

firefox code:
- https://github.com/mozilla/gecko-dev
- https://hg.mozilla.org/
- https://searchfox.org/mozilla-central/source/

**Comment by Feodor2** [comment]
>Invalid draw target type specified: 3

Please give details

**Comment by AroKol78** [comment]
GPU Accelerated Windows	1/1 Direct3D 9 (OMTC)
Basilisk52 no error in the same settings
about:support    failures log "[GFX1-]: Invalid draw target type specified: 3"
a few movies that i watched fullscreen https://www.nasa.gov/multimedia/videogallery/index.html and https://eol.jsc.nasa.gov/ESRS/HDEV/

**Comment by AroKol78** [comment]
Mypal 28.14.1 is work ok. keep track of update https://github.com/FFmpeg/FFmpeg
