### ISSUE TITLE
look open file

### ISSUE THREAD

**Issue by AroKol78** [Feodor2/Mypal#233]
look open/save file is old on winxp luna-silver-theme, download settings theme from the system

**Comment by Feodor2** [comment]
Do you mean open file window?

**Comment by AroKol78** [comment]
yes

**Comment by Feodor2** [comment]
The window works normally on luna-silver-theme,

**Comment by AroKol78** [comment]
theme - old
![old](https://user-images.githubusercontent.com/70756447/92627202-51084200-f2cb-11ea-957e-fe66287136d5.JPG)
theme - luna-silver
![new](https://user-images.githubusercontent.com/70756447/92627261-654c3f00-f2cb-11ea-9f54-355c9f8c50ec.JPG)

**Comment by Feodor2** [comment]
So do you want second theme? i can try something to do before new release.

**Comment by AroKol78** [comment]
yes.
my system and other app use 2.
only mypal use 1.

**Comment by Feodor2** [comment]
I failed to do this quickly before new release, i continue investigating.

**Comment by AroKol78** [comment]
maybe it will help
https://learnwpf.com/post/2007/01/05/Why-does-the-OpenFileDialog-in-WPF-look-so-e2809c1999e2809d-and-how-can-I-fix-it.aspx
https://stackoverflow.com/questions/6764100/does-application-enablevisualstyles-do-anything
http://msdn.microsoft.com/en-us/library/system.windows.forms.application.enablevisualstyles.aspx
http://www.nbdtech.com/Blog/archive/2008/05/28/Why-am-I-Getting-Old-Style-File-Dialogs-and-Message.aspx
http://www.nbdtech.com/Blog/archive/2008/06/08/Will-Setting-a-Manifest-Solve-My-WPF-Message-Box-Style.aspx
http://www.nbdtech.com/Blog/archive/2008/06/16/The-Application-Manifest-Needed-for-XP-and-Vista-Style-File.aspx
http://www.nbdtech.com/Blog/archive/2008/07/15/Vista-style-open-and-save-dialogs-with-WPF-without-using.aspx

**Comment by Feodor2** [comment]
Thanks, it will be fixed next release, until that you can take the manifest file rename it then put along the exe.

**Comment by AroKol78** [comment]
centaury-20200918214808.mingw32 is ok (new icons and gadgets)

**Comment by AroKol78** [comment]
mypal-28.12.0 update to 28.13.1 ,old icons ?
centaury is ok new icons.

**Comment by Feodor2** [comment]
This is not the next release actually, just repacked old with useragents override fix

**Comment by AroKol78** [comment]
great job, all ok. Thanks.
