### ISSUE TITLE
thanks for making mypal!

### ISSUE THREAD

**Issue by TobyAdd** [Feodor2/Mypal#24]
Feodor2 thanks for creating the best browser for windows xp. You are the best man who made a soft for unsupported system. But unfortunately it's over, rip mypal.

**Comment by felix-22** [comment]
Why duplicating: https://github.com/Feodor2/Mypal/issues/4.

**Comment by ghost** [comment]
Don't forget that there are Chinese builds on the modern Chromium engine, which works on XP. The interface is partly in English, the installer is Chinese.
https://browser.kfsafe.cn/
https://browser.360.cn/ee/

**Comment by NEO-SPECTRUMAN** [comment]
chromium is shit
only OLD firefox is usable

**Comment by NEO-SPECTRUMAN** [comment]
also firefox's addons are irreplaceable...
therefore firefox >52 is f$##n shit!

**Comment by Feodor2** [comment]
You are welcome but duplicating is unwanted.

**Comment by ghost** [comment]
> Don't forget that there are Chinese builds on the modern Chromium engine, which works on XP. The interface is partly in English, the installer is Chinese.
> https://browser.kfsafe.cn/
> https://browser.360.cn/ee/

Great dude I'm so happy to use random Chinaware, sounds legt
This is the dumbest ******* thing and I find the palemoon devs act like manchildren. Never again using anything from them

**Comment by ghost** [comment]
I think if you are Russian, American or European, you don't need to be afraid of Chinese probes. And a Chinese patriot too, I guess. I would be much more afraid of Microsoft Windows.
Well, let's say: Chinese can steal your money, Microsoft can't. But things change if you are Snowden, for example.
Manchild ≠ Moonchild
