### ISSUE TITLE
Video on Youtube quality is 360p. Can't install any ad blocking extension

### ISSUE THREAD

**Issue by noteboor** [Feodor2/Mypal#24]
Thanks for that browser. It works really fast, but I can't install any ad blocking extension such as AdBlock or uBlock Origin (browser says that there's some problems with the WebExtensions "WebExtensions is not supported"). Also, quality of the videos on YouTube can't be higher than 360p. YouTube says that this browser is old.

**Comment by kitaro1** [comment]
You need to set YouTube.
https://images81.fotosik.pl/1097/f925fddc2b20757c.png
Windows XP is to have LAV Filters installed and x264vfw 
directx 9.29 redist, visual C ++ 2008, 2010, 2015.
57/5000
You download older versions of the addons running in mypal:
https://images82.fotosik.pl/1098/88f48330861ed729.png

**Comment by Feodor2** [comment]
For youtube higher than 360
read https://github.com/Feodor2/Mypal/wiki/H264-support
or simple install k-lite for winxp

Recent ublock is there
https://github.com/gorhill/uBlock/releases

but seek legacy word
https://github.com/gorhill/uBlock/releases/tag/firefox-legacy-1.16.4.1

**Comment by noteboor** [comment]
Thanks a lot guys. All is working now. I'm very appreciated
