### ISSUE TITLE
Mypal 28.13.0 no longer renders some websites properly

### ISSUE THREAD

**Issue by noles22** [Feodor2/Mypal#241]
In Mypal 28.12.0 or earlier I can access outlook with no problems, however, starting with 28.13.0 I get a blank text box when I try to sign in The site still works with all other browsers on my machines including Firefox 52.9.0.
![Outlook Mypal 28 13 0 issue](https://user-images.githubusercontent.com/43044816/92984368-a7b27f00-f477-11ea-90c4-55573ab7ccf3.JPG)

**Comment by Feodor2** [comment]
I cant say about palemoon now, you are to ask in their site.

**Comment by letmeindude** [comment]
Feodor, why did you remove default user agent overrides? Here is the list of the sites which could be broken:

`user_pref("general.useragent.override.addons.mozilla.org", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:4.6) Goanna/20170101 PaleMoon/28.13.0");
user_pref("general.useragent.override.altibox.dk", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:4.6) Goanna/20170101 PaleMoon/28.13.0");
user_pref("general.useragent.override.altibox.no", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:4.6) Goanna/20170101 PaleMoon/28.13.0");
user_pref("general.useragent.override.aol.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.9) Gecko/20100101 Firefox/52.9 (Pale Moon)");
user_pref("general.useragent.override.bing.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.9) Gecko/20100101 Firefox/52.9 (Pale Moon)");
user_pref("general.useragent.override.calendar.yahoo.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.9) Gecko/20100101 Firefox/52.9 (Pale Moon)");
user_pref("general.useragent.override.citi.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:57.0) Gecko/20100101 Firefox/57.0 (Pale Moon)");
user_pref("general.useragent.override.deviantart.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:4.6) Goanna/20170101 PaleMoon/28.13.0");
user_pref("general.useragent.override.deviantart.net", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:4.6) Goanna/20170101 PaleMoon/28.13.0");
user_pref("general.useragent.override.dropbox.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:99.9) Gecko/20100101 Firefox/99.9 (Pale Moon)");
user_pref("general.useragent.override.firefox.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:4.6) Goanna/20170101 PaleMoon/28.13.0");
user_pref("general.useragent.override.github.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:4.6) Goanna/20170101 PaleMoon/28.13.0");
user_pref("general.useragent.override.google.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:71.0) Gecko/20100101 Firefox/71.0 PaleMoon/28.13.0");
user_pref("general.useragent.override.googlevideos.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.9) Gecko/20100101 Goanna/4.6 Firefox/38.9 PaleMoon/28.13.0");
user_pref("general.useragent.override.gstatic.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:71.0) Gecko/20100101 Firefox/71.0 PaleMoon/28.13.0");
user_pref("general.useragent.override.humblebundle.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.9) Gecko/20100101 Firefox/52.9 (Pale Moon)");
user_pref("general.useragent.override.live.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.9) Gecko/20100101 Firefox/52.9 (Pale Moon)");
user_pref("general.useragent.override.mozilla.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:4.6) Goanna/20170101 PaleMoon/28.13.0");
user_pref("general.useragent.override.mozilla.org", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:4.6) Goanna/20170101 PaleMoon/28.13.0");
user_pref("general.useragent.override.msn.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.9) Gecko/20100101 Firefox/52.9 (Pale Moon)");
user_pref("general.useragent.override.outlook.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.9) Gecko/20100101 Firefox/52.9 (Pale Moon)");
user_pref("general.useragent.override.patientaccess.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:60.0) Gecko/20100101 Firefox/60.0 PaleMoon/28.13.0");
user_pref("general.useragent.override.soundcloud.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:4.6) Goanna/20170101 PaleMoon/28.13.0");
user_pref("general.useragent.override.web.de", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.9) Gecko/20100101 Firefox/52.9 (Pale Moon)");
user_pref("general.useragent.override.www.amazon.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.9) Gecko/20100101 Firefox/45.9 (Pale Moon)");
user_pref("general.useragent.override.yahoo.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:99.9) Gecko/20100101 Firefox/99.9 (Pale Moon)");
user_pref("general.useragent.override.youtube.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:60.0) Gecko/20100101 Firefox/60.0 PaleMoon/28.13.0");
user_pref("general.useragent.override.yuku.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.9) Gecko/20100101 Firefox/52.9 PaleMoon/28.13.0");
`

**Comment by letmeindude** [comment]
You could just replace Pale Moon/PaleMoon with Mypal.

**Comment by letmeindude** [comment]
Complete list of 37 user agents which are removed in Mypal 28.13:

> user_pref("general.useragent.override.addons.mozilla.org", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:4.6) Goanna/20170101 PaleMoon/28.13.0");
user_pref("general.useragent.override.altibox.dk", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:4.6) Goanna/20170101 PaleMoon/28.13.0");
user_pref("general.useragent.override.altibox.no", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:4.6) Goanna/20170101 PaleMoon/28.13.0");
user_pref("general.useragent.override.aol.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.9) Gecko/20100101 Firefox/52.9 (Pale Moon)");
user_pref("general.useragent.override.bing.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.9) Gecko/20100101 Firefox/52.9 (Pale Moon)");
user_pref("general.useragent.override.calendar.yahoo.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.9) Gecko/20100101 Firefox/52.9 (Pale Moon)");
user_pref("general.useragent.override.chase.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:79.0) Gecko/20100101 Firefox/79.0");
user_pref("general.useragent.override.citi.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:57.0) Gecko/20100101 Firefox/57.0 (Pale Moon)");
user_pref("general.useragent.override.dailymotion.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0");
user_pref("general.useragent.override.deviantart.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:4.6) Goanna/20170101 PaleMoon/28.13.0");
user_pref("general.useragent.override.deviantart.net", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:4.6) Goanna/20170101 PaleMoon/28.13.0");
user_pref("general.useragent.override.dropbox.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:99.9) Gecko/20100101 Firefox/99.9 (Pale Moon)");
user_pref("general.useragent.override.firefox.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:4.6) Goanna/20170101 PaleMoon/28.13.0");
user_pref("general.useragent.override.gaming.youtube.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0");
user_pref("general.useragent.override.github.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:4.6) Goanna/20170101 PaleMoon/28.13.0");
user_pref("general.useragent.override.google.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:71.0) Gecko/20100101 Firefox/71.0 PaleMoon/28.13.0");
user_pref("general.useragent.override.googlevideos.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.9) Gecko/20100101 Goanna/4.6 Firefox/38.9 PaleMoon/28.13.0");
user_pref("general.useragent.override.gstatic.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:71.0) Gecko/20100101 Firefox/71.0 PaleMoon/28.13.0");
user_pref("general.useragent.override.hitbox.tv", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.9) Gecko/20100101 Firefox/52.9");
user_pref("general.useragent.override.humblebundle.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.9) Gecko/20100101 Firefox/52.9 (Pale Moon)");
user_pref("general.useragent.override.live.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.9) Gecko/20100101 Firefox/52.9 (Pale Moon)");
user_pref("general.useragent.override.mozilla.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:4.6) Goanna/20170101 PaleMoon/28.13.0");
user_pref("general.useragent.override.mozilla.org", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:4.6) Goanna/20170101 PaleMoon/28.13.0");
user_pref("general.useragent.override.msn.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.9) Gecko/20100101 Firefox/52.9 (Pale Moon)");
user_pref("general.useragent.override.netflix.com", "Mozilla/5.0 (Windows NT 6.1; rv:45.9) Gecko/20100101 Firefox/45.9");
user_pref("general.useragent.override.netflximg.net", "Mozilla/5.0 (Windows NT 6.1; rv:45.9) Gecko/20100101 Firefox/45.9");
user_pref("general.useragent.override.outlook.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.9) Gecko/20100101 Firefox/52.9 (Pale Moon)");
user_pref("general.useragent.override.patientaccess.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:60.0) Gecko/20100101 Firefox/60.0 PaleMoon/28.13.0");
user_pref("general.useragent.override.players.brightcove.net", "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko");
user_pref("general.useragent.override.privat24.ua", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0");
user_pref("general.useragent.override.soundcloud.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:4.6) Goanna/20170101 PaleMoon/28.13.0");
user_pref("general.useragent.override.web.de", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.9) Gecko/20100101 Firefox/52.9 (Pale Moon)");
user_pref("general.useragent.override.web.whatsapp.com", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36");
user_pref("general.useragent.override.www.amazon.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.9) Gecko/20100101 Firefox/45.9 (Pale Moon)");
user_pref("general.useragent.override.yahoo.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:99.9) Gecko/20100101 Firefox/99.9 (Pale Moon)");
user_pref("general.useragent.override.youtube.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:60.0) Gecko/20100101 Firefox/60.0 PaleMoon/28.13.0");
user_pref("general.useragent.override.yuku.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.9) Gecko/20100101 Firefox/52.9 PaleMoon/28.13.0");

**Comment by Feodor2** [comment]
I intended to replace but commit an error. Anyway login for the outlook works normally in mypal.
To fix the error now replace the second omni.ja in the <browser>\browser, pay attention that is not in the root directory, make backup of the old one just in case.
[omni.zip](https://github.com/Feodor2/Mypal/files/5212675/omni.zip)

**Comment by letmeindude** [comment]
These 2 are still missing:
> user_pref("general.useragent.override.mozilla.com", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:4.6) Goanna/20170101 PaleMoon/28.13.0");
user_pref("general.useragent.override.mozilla.org", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:4.6) Goanna/20170101 PaleMoon/28.13.0");

**Comment by Feodor2** [comment]
why do you want override for mozilla.com\org?

**Comment by letmeindude** [comment]
I don't. I have just found those 2 in Pale Moon, too.

**Comment by Feodor2** [comment]
So if it is on in the Pale Moon you do want to copy blind? I opened both org and com mozillas fine without override.

**Comment by letmeindude** [comment]
No, I thought they are there for a reason. It doesn't matter.
