### ISSUE TITLE
Mypal now kinda sucks?

### ISSUE THREAD

**Issue by StefCraps** [Feodor2/Mypal#243]
So it means that i must stop using mypal? if browser can't render pages then why the hell i need browser like this and 1 more thing i asked u many may times to make cams to work in omegle and other chat sites but u not doing it. i asking u 1 more time to turm on web rtc or something plizz

**Comment by korick** [comment]
webrtc turn off by default, if u need cams work try github.com/Feodor2/Centaury

**Comment by Feodor2** [comment]
And i answered not that times, i do not impose this browser anyone, go use another if it not suits you.
