### ISSUE TITLE
Your Omni.ja Zip file for 28.13.0 My Pal

### ISSUE THREAD

**Issue by rocky7717** [Feodor2/Mypal#246]
I notice that the original omni.ja file that you say to remove,which is 6.58 Mb  and replace with your omni.zip package is 20.2 Mb...Is that correct???
Why such a large difference for those missing user agents you say you missed,doesn,t seem right!!

**Comment by Feodor2** [comment]
better compression, i used faster or like that

**Comment by Feodor2** [comment]
updated release
