### ISSUE TITLE
Whatsapp Web does not work in this version

### ISSUE THREAD

**Issue by ByRodrigoSoares** [Feodor2/Mypal#247]
The previous version worked perfectly but this new one spoiled a lot of things stopped working
![cats](https://user-images.githubusercontent.com/50956690/93274620-2b7aad00-f791-11ea-86b0-c4df2d4070d4.jpg)

**Comment by ByRodrigoSoares** [comment]
I suggest a compilation of this version with the updated agents

**Comment by Feodor2** [comment]
Sure

**Comment by Feodor2** [comment]
Done
