### ISSUE TITLE
Navigating on github requires explicit page refresh for the page to load

### ISSUE THREAD

**Issue by JoachimHenze** [Feodor2/Mypal#249]
I am using Mypal 2.8.11. A good browser. I love it. Still I have found a bug:
I use it on WinXP SP3.
Open the following website that shows a github pull request
https://github.com/reactos/reactos/pull/3211
Now click the link "File changed" to see the diff of the page.

Expected result:
the page should load

*Observed result*
The page does not load. But an explicit page refresh does properly show the page.

**Comment by Feodor2** [comment]
With version 28.13.1 page loads normally - update.

**Comment by JoachimHenze** [comment]
I retried with 28.13.1 and I do confirm that this issue is fixed in that newer version. Thank you!
Keep up the good work, Feodor2. Your browser fork is really a good one.It definitely outperforms its origin Palemoon and also FF52 for my use-cases which are Win-XP-centred. But I guess you already know that XP-support is one of the most unique features your loyal fan-base does appreciate most. You are creating something special here that will last.
