### ISSUE TITLE
Need assistance with Github and Noscript

### ISSUE THREAD

**Issue by JeanPaulLucien** [Feodor2/Mypal#25]
I forked NoScript addon repo, but I don't need 10 version and above. How to delete all changes that have been done?
https://github.com/JeanPaulLucien/noscript

**Comment by gdl-blue** [comment]
(offtopic with mypal but) maybe you may need to use git, which is a program that can manage your github(or any site that uses the git system) repositories

**Comment by Feodor2** [comment]
Irrelevant indeed.
