### ISSUE TITLE
Update, then launch mypal now

### ISSUE THREAD

**Issue by Culexamaxa** [Feodor2/Mypal#254]
After performing an update when running the install executable from windows (XP), I install into desired folder and once install finishes, last panel of the install asks if I want to open MyPal now.  I have the option clicked, then do next.  I am then told MyPal is already open.

I recently updatds from v28.8.3 to v28.9.2, which, side note, didn't open my previous session.  From what I can tell, the install/upgrade tells me MyPal is open when it is not.

I updated to v28.10, it was still happening.  I upgraded to v28.13.  Stands to reason, it's going to be there for all versions in between.

**Comment by Feodor2** [comment]
I cant tell about old versions, do not recall such bug , their update may be not good.
