### ISSUE TITLE
MyPal 28.14.1 shrinks program display

### ISSUE THREAD

**Issue by us66mo** [Feodor2/Mypal#264]
Up to version 28.13.0 the MyPal display on my Win10 64 notebook had larger icons and a larger website display, regardless of the website. After installing version 28.14.1, the icons and website display have shrunk to a size where I need reading glasses to see them / negotiate a website unless I manually zoom in. Any way to get the previous overall display back?

**Comment by Feodor2** [comment]
Sorry, i have no any win10 machine around, and never check mypal on win10. And this is for #252 too
But i want help to try.  So what you see if you restart in the safe mode.

**Comment by us66mo** [comment]
> 
> 
> Sorry, i have no any win10 machine around, and never check mypal on win10. And this is for #252 too
> But i want help to try. So what you see if you restart in the safe mode.

Thanks for responding! I tried Mypal in safe mode, no change. I think what happened is that the new version is not accepting my screen display modification of 150%, which the older version recognized.

**Comment by Feodor2** [comment]
Please describe the modification
