### ISSUE TITLE
Cosmetic Color changes to Tab and Status Bar

### ISSUE THREAD

**Issue by npprabhu** [Feodor2/Mypal#265]
@Feodor2 

 After the major changes done to Mypal 28.13.0, i have noticed that in its Default Theme the Tab and Status bar still continue to carry the color from the Old Mypal while the Menu and Navigation Toolbar carry Old Firefox Color. Well it looks a bit odd now, It would be nice to have all of them carry the same Color.. (old Firefox color doesn't matter). Just a kind suggestion...

**Comment by Anbima** [comment]
Go to the profile folder from MyPal and add a folder "chrome".
Add a file named "userChrome.css" as txt-file in this folder and write following in the file:

@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");
#toolbar-menubar, #TabsToolbar, #nav-bar {
background-color: #B4CEF7 !important;
}

**Comment by Feodor2** [comment]
I noticed already, seems it set explicitly too, while is to set regarding system colors.
