### ISSUE TITLE
i´m happy to re find and re use MP!!!!

### ISSUE THREAD

**Issue by jazei-AR** [Feodor2/Mypal#267]
just it: I'm very happy to Re-use MP... I used MP 2 months ago then in an update MP changes to PM and I  (¿thinked?) believed that MP had a new styled design... but NO Now I know that MP is not PM!!! I prefer MP. MP fixed 2 things that PM has (banner in tumblr.com and rotationing wheel of Win7 doing scrolling in a few pages of poringa.net). And I tell us that I could do the change to Spanish interface doing your steep by steep help in this forum to change languages. and plus I could do the change to spanish dictionary. Regard from Argentina.

**Comment by Feodor2** [comment]
Sure, look #40
