### ISSUE TITLE
Crash on video end

### ISSUE THREAD

**Issue by pachuco** [Feodor2/Mypal#270]
A certain video causes Mypal to crash, as video ends. Tried on v28.14.1, also with fresh profile. Happens 100% of time.
[test2.zip](https://github.com/Feodor2/Mypal/files/5357052/test2.zip)

Will try other versions and report back.

**Comment by pachuco** [comment]
Yeah, this does not happen with v28.13.1
So, tempting to blame ffmpeg update.

**Comment by pachuco** [comment]
On an unrelated note, v28.14.1 seems slower and more bloated overall compared to v28.13.1.
I'd need to check this thoroughly before I open an issue for it, though.

**Comment by Feodor2** [comment]
i shall made new update.
