### ISSUE TITLE
Last new

### ISSUE THREAD

**Issue by AroKol78** [Feodor2/Mypal#275]
Look  Feodor2 - MoonchildProductions moving to a new home
[ https://forum.palemoon.org/viewtopic.php?f=5&t=25461 ]
[ https://repo.palemoon.org/ ]
[ https://repo.palemoon.org/explore/repos ]

**Comment by Feodor2** [comment]
Is it possible to git clone from there, I am going to try via vpn

**Comment by AroKol78** [comment]
github  MoonchildProductions / UXP About "This is a GitHub **mirror** of the Unified XUL Platform."
github MoonchildProductions / Pale-Moon / Basilisk i did not find the same information but possible mirror.

**Comment by AroKol78** [comment]
:broken_heart: :skull_and_crossbones: only left on github  MoonchildProductions/UXP

**Comment by L3P3** [comment]
Hello, what does this mean and is it resolved? Greetings

**Comment by AroKol78** [comment]
They transferred the codes to their servers , only UXP remained (mirror) on the github.
Problems may arise - MoonchildProductions doesn't like Mypal, XP.
> ... and is it resolved?

depends on @Feodor2

**Comment by L3P3** [comment]
I donated MoonchildProductions for Mypal already. They should like it damnit!

**Comment by AroKol78** [comment]
> ... doesn't like Mypal, XP.

[ MoonchildProductions vs. Mypal
https://forum.palemoon.org/viewtopic.php?f=25&t=25476
https://forum.palemoon.org/viewtopic.php?f=40&t=25228
https://forum.palemoon.org/viewtopic.php?f=17&t=25084
they even blocked sites ]

**Comment by L3P3** [comment]
OK dear @Feodor2 I want to support this project officially. I donated to Palemoon already, I donated to Mozilla and I want to donate to this project somehow. I want to help to stop this unneccessary conflict.
To me, it is very important to keep supporting Windows XP. I have a netbook running XP and I love that device. It would break my hearth to abandon it since I cannot use it anymore for important tasks.
Is there any way I can make sure or at least help that modern Firefox on XP keeps working for the next years without any bogous stuff going on in the background?

**Comment by Feodor2** [comment]
Someone please download https://repo.palemoon.org/MoonchildProductions/Pale-Moon then upload somewhere, while i download myself and compare with others copy, to confirm that they provide the one identical stuff for different users.

**Comment by npprabhu** [comment]
.zip link : https://drive.google.com/file/d/1vJ8fjLGG0aiDvwKcP7ahDoytN7OPJiJD/view?usp=sharing

.tar.gz Link : https://drive.google.com/file/d/1P86OYeYGOYMD_khmvbcsbM9vDPz4YUIs/view?usp=sharing

**Comment by Feodor2** [comment]
Thanks, zip file was enough.

**Comment by AroKol78** [comment]
Google Drive Links Pale-Moon-28.15.0_Release.zip
https://drive.google.com/file/d/19GtZnXceCUz9c6z5TPANf8lHTx9ACA0B/view?usp=sharing
not too small file ?

**Comment by Feodor2** [comment]
thanks, this is enough not necessary to post every new file.

**Comment by AroKol78** [comment]
You prefer **release** or **master** or / and other (e.g. Basi...)

**Comment by AroKol78** [comment]
Localization
no more new on [ https://github.com/JustOff/pale-moon-localization ]
info [ https://forum.palemoon.org/viewtopic.php?f=30&t=25649 ]
for now they are here [ https://repo.palemoon.org/MoonchildProductions/pale-moon-localization ]
