### ISSUE TITLE
I can not see the options of the 3 points (...) of comments in posts here and I can not attach img from my PC here and preview too

### ISSUE THREAD

**Issue by jazei-AR** [Feodor2/Mypal#276]
I can not see the options of the 3 points (...) of comments in posts here so I can not quote, edit my comments.
in my post, I can do it well (I see ·edit·,etc) but in comments: NO
screenshot: [URL=https://imgbox.com/3f0vfCFE][IMG]https://images2.imgbox.com/e4/aa/3f0vfCFE_o.jpg[/IMG][/URL]
video-screenshots: comments: https://sendvid.com/d18jt0ay other (post&comments): https://sendvid.com/llsyobhv
attach and preview do not work

**Comment by jazei-AR** [comment]
plus I can not edit this post: if I click on "edit" it does not do nothing

**Comment by AroKol78** [comment]
login github.com
install or updadte github-wc-polyfill  https://github.com/JustOff/github-wc-polyfill/releases

**Comment by jazei-AR** [comment]
> 
> 
> login github.com
> install or updadte github-wc-polyfill https://github.com/JustOff/github-wc-polyfill/releases
> It works for me
> ![workmenu](https://user-images.githubusercontent.com/70756447/96868938-0acc0400-146f-11eb-8bc7-4a8f5dec7396.PNG)

fIXED! THANK YOU @AroKol78 FOR YOUR HELP!!! FIXED...AND I ENJOY USING MP

**Comment by AroKol78** [comment]
if everything is ok you can close the problem.
