### ISSUE TITLE
¿Is it tue that 64 bit uses considerably more memory than the 32-bit version?

### ISSUE THREAD

**Issue by jazei-AR** [Feodor2/Mypal#277]
****
From **_Slimjet for 64-bit Windows (What's new?)

NOTE: The 64-bit version uses considerably more memory than the 32-bit version, but offers less jitter and improved performance. It is not recommended for computers with less than 8GB of memory._**
****

I downloaded and I'll try 32 bit version slimjet for replace Cent browser 64 bit because of cent uses a little more memory than MP and backspace does not back the last page visited... and I don`t like chrome

Will the same happen with MP?

I'm using 64 bit version MP on win 7 64 bit PC but I would have no problem switching to the 32-bit version of MP

![screenshot](https://user-images.githubusercontent.com/72522918/96994984-dce4cf00-1503-11eb-8d17-b5d31f1e6f04.jpg)

**Comment by Feodor2** [comment]
Undoubtedly x64 take more memory, while old firefoxes x32 including mypal goes very slow when occupy more than 1gb, if to like many tabs and heavy sites x64 will suits better.

**Comment by jazei-AR** [comment]
what a dilemma!!! I will try 32 bit MP. never mind I´m very happy to know, use and enjoy MP

**Comment by pachuco** [comment]
Speaking of the 1gb, how can I tune browser to work with more?
I've disabled pagefile, and the browser absolutely hates this.

**Comment by Feodor2** [comment]
Actually this is not 1gb limit this is peculiarity, after exceeding 1gb browser become slower and slower then almost freeze.
Also many other things do hate disable pagefile.

**Comment by pachuco** [comment]
Maybe my XP x86 OS and 4gb RAM is shit. When using the browser mostly, it certainly feels that way.(I did cleanup reinstall though)
Or maybe the browser, palemoon is becoming shit and increasingly bloated. When using certain sites, it certainly feels that way.
Or maybe the sites themselves are becoming increasingly bloated(I'm looking at you, discord and youtube). When webdevs are becoming lazy, it certainly feels that way.

So, who is gaslighting me?

As for 1gb memory thing, I am tempted to blame memory management in browser.

**Comment by AroKol78** [comment]
>Maybe my XP x86 OS and 4gb RAM is shit. When using the browser mostly, it certainly feels that way.(I did cleanup reinstall though)
Or maybe the browser, palemoon is becoming shit and increasingly bloated. When using certain sites, it certainly feels that way.
Or maybe the sites themselves are becoming increasingly bloated(I'm looking at you, discord and youtube). When webdevs are becoming lazy, it certainly feels that way.

a bit of everything. i use winxp3sp 2gb - most sites work fine except sites that use Google WebComponents and DRM.
e.g. i play video fine on YouTube - just move the mouse and the cpu usage jumps from 10% to 90%

today, web developers are probably just learning LOGO

**Comment by Feodor2** [comment]
If you have 4gb why not use x64 OS. 

>As for x86 1gb memory thing, I am tempted to blame memory management in browser
It designed to favor low ram usage on low end machines and few tabs, all x86 win os not designed use many ram for its apps at all. Take chrome which designed to use more ram and good with many tabs, but it sucks on weak machine even with one tab opened.


>a bit of everything. i use winxp3sp 2gb - most sites work fine except 

Same me too, most sites fine, but until browser not exceeds 1gb
