### ISSUE TITLE
Cannot access wiki

### ISSUE THREAD

**Issue by shlyakpavel** [Feodor2/Mypal#28]
<img width="1325" alt="image" src="https://user-images.githubusercontent.com/19782228/50984625-6552d500-1513-11e9-92a1-40bdf48ee13c.png">
All my attempts to follow "Building from sources by yourself" result into this. I really hope you can help me

**Comment by Feodor2** [comment]
Sorry, i have made only the table of contents. Was absent form January, this article is actually ready and wait to be put, i hope i can do that upon coming Monday.

**Comment by Feodor2** [comment]
Building from sources is ready. Others articles will be later.

**Comment by shlyakpavel** [comment]
The wiki is now okay. Thanks!
