### ISSUE TITLE
Tutorial: Change brandname "Pale Moon" to "Mypal" in other languages added

### ISSUE THREAD

**Issue by wyxchari** [Feodor2/Mypal#28]
Close Mypal
Open WinRAR and open C:\Documents and Settings\ (user) \ (Datos de programa) \Moonchild Productions\Pale Moon\Profiles\ (profile) .default\extensions\langpack- (es-ES) @palemoon.org.xpi
Change the () by the specifics.
Go in WinRAR to browser\chrome\es-ES\locale\branding and extract brand.dtd . Do not close WinRAR.
Open Notepad and replace "Pale Moon" by "Mypal".
Save and drag to WinRAR.
Close WinRAR and open Mypal.
![screenshot - 26_08_2018 21_13_02](https://user-images.githubusercontent.com/42490583/44632087-71733700-a964-11e8-8958-bea9ccde65c9.jpg)

**Comment by Feodor2** [comment]
Also mypal has new language strings, so you are to add them too into the language pack.
Ma be we should fix all languages?
The new strings are in the shellservice.properties:
PortablemodeTitle=Portable Mode
PortablemodeMessage=By pressing Yes you switch %S into standart non-portable mode, restart will be executed as well.
