### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by silva1001** [Feodor2/Mypal#280]
Hello,

I am trying to install MyPal on my Windows XP 32bit laptop.
I cant seem to access the website using Internet Explorer, so I tried to download the installation .installer file to a USB and install it from that. However it doesn't seem to work (an error sound plays)
How can I install this successfully?

**Comment by AroKol78** [comment]
try to install from the site http://www.mypal-browser.org/download.html

**Comment by jazei-AR** [comment]
> try to install from the site http://www.mypal-browser.org/download.html
adding the URL...  thanks @AroKol78
