### ISSUE TITLE
what's the meaning of "Disp. software" in English (see screensoht)

### ISSUE THREAD

**Issue by jazei-AR** [Feodor2/Mypal#281]
![screen](https://user-images.githubusercontent.com/72522918/97556724-989c7780-19b8-11eb-90e3-abe7a991e280.jpg)
what's the meaning of "Disp. software" in English for understand only
I know how to use that, and i'm using it too, I only want to know what this is "disp. software" 
thank you

**Comment by kitaro1** [comment]
http://prnt.sc/v9c4dp

**Comment by jazei-AR** [comment]
> 
> 
> http://prnt.sc/v9c4dp
thank @kitaro1 
wowww more complex that I thought!!! I thought it means Display Software
@Feodor2 et Al.  why don't you delete "dis.p software" of the U.I. message in spanish could say "Escriba contraseña de seguridad."  because what add "disp. software" to the message?

**Comment by Feodor2** [comment]
There are two Disp. things but in english are same
1. Disp. software de seguridad = Software Security Device
2. Disp. seguridad software (FIPS) = Software Security Device (FIPS)
Do you want to change such as
1. Escriba contraseña maestra de seguridad
2. Escriba contraseña maestra de seguridad (FIPS)

**Comment by jazei-AR** [comment]
> 
> 
> There are two Disp. things but in english are same
> 
>     1. Disp. software de seguridad = Software Security Device
> 
>     2. Disp. seguridad software (FIPS) = Software Security Device (FIPS)
>        Do you want to change such as
> 
>     3. Escriba contraseña maestra de seguridad
> 
>     4. Escriba contraseña maestra de seguridad (FIPS)

3 yes 3!!!! simple and easy to understand for anyone
I´m using mp very happy, enjoyng mp

**Comment by Feodor2** [comment]
Sure, already have updated language in the 28.13 release

**Comment by jazei-AR** [comment]
> 
> 
> Sure, already have updated language in the 28.13 release

so ¿will you change the text of the window to the option 3? to "Escriba contraseña maestra de seguridad"
or not? in next new versions?..
Regards

**Comment by Feodor2** [comment]
Seems i changed all options, point what i forgot. Sure i keep this change in the next versions.
