### ISSUE TITLE
when I do click in loocking for Updates mp upgrades to another bit version different to my choiced version 

### ISSUE THREAD

**Issue by jazei-AR** [Feodor2/Mypal#282]
I choiced 32 bit version for test about poor RAM my PC is 64 bit arquitec..
Upgrading via pop up window alerting me about "new version available...."
mp downloaded and changed to another version.. autodetec  PC version is playing here (this Latest - Automatically detect architecture)
maybe you can alert about it or put links to download options
![screeshot](https://user-images.githubusercontent.com/72522918/97778545-a0921e00-1b56-11eb-9a44-934a43f41648.jpg)

**Comment by Feodor2** [comment]
Do you mean automatic update?

**Comment by jazei-AR** [comment]
> 
> 
> Do you mean automatic update? **Help - check for update**

via pop up window alert me about new version to download doing click there download 64 bit version mp, i`m ussssing for test 32 bit version

**Comment by Feodor2** [comment]
![image](https://user-images.githubusercontent.com/19492771/97781313-80d11900-1b9b-11eb-87a3-fcc36a8a33e2.png)

This?

**Comment by jazei-AR** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/19492771/97781313-80d11900-1b9b-11eb-87a3-fcc36a8a33e2.png)
> 
> This?

yes that window... I think that the add of  a few words tell us that mp will install most suitable mp version using autodetec architec of you PC.. so when I read that words I realize that I should go to manual update... because I remembre that I using for test another version different of mi PC architec need!
never mind I`m learning to use and I will remeber this situation next time to updated my dear mp.
I`m very happy to use MP 
I detected that using in a heavy site 64 bit mp is a little littttle more RAM used that 32 bit mp.. litle. it is a test only and I will test few weeks and the I return or not to the version suitables for PC architecture.
sorry for my poor Englsh! regards
josé

**Comment by Feodor2** [comment]
So this is autoupdate, It does not any autodetec and not intended so.

**Comment by jazei-AR** [comment]
> So this is autoupdate, It does not any autodetec and not intended so.
I don´t use autoupdate... mp told me that there was a new version via a pop up window ( your window showered up (https://user-images.githubusercontent.com/19492771/97781313-80d11900-1b9b-11eb-87a3-fcc36a8a33e2.png) and It uses "automatically detect architecture"
![screeshot](https://user-images.githubusercontent.com/72522918/97786557-24fe9400-1b8b-11eb-9611-7ef6e1270b1d.jpg)
my setting is: looking for updates but ask my if I want to install.  Plus: wrong translation: looking for means "Buscar" not "Comprobar"
![screenshot](https://user-images.githubusercontent.com/72522918/97786587-58d9b980-1b8b-11eb-8360-f6bff9662c37.jpg)

**Comment by Feodor2** [comment]
Not straight automatic is, but belongs to it too, and does the same, what is to update the browser, in this case alert before update if its version is lower than the version of the package on the server site, other things like product machine and language are match strict.
