### ISSUE TITLE
cookie-confirm

### ISSUE THREAD

**Issue by Anbima** [Feodor2/Mypal#283]
Hello,

site: https://www.rockantenne.de/
I cannot confirm the cookie as it is not displayed.

**Comment by kitaro1** [comment]
There is a cookie. Probably hidden on this page, but in ccleaner - cookies options show cookie.
http://prnt.sc/vc043n

**Comment by Anbima** [comment]
I cannot enter the page because the button to confirm the cookies is not displayed.

**Comment by kitaro1** [comment]
You're blocking too much.
http://prnt.sc/vc1z2k

**Comment by Anbima** [comment]
Please scroll down the page.
The button for the cookie confirmation is not displayed.

**Comment by kitaro1** [comment]
Cookies point 3.2 https://www.rockantenne.de/rock-antenne/datenschutz#uc-central-modal-show

**Comment by Anbima** [comment]
Do you can see the Button to confirm the cookies?
I can't see it.

**Comment by jazei-AR** [comment]
@Anbima could you post a screenshot for the button you're looking for using another browser?

**Comment by Anbima** [comment]
The cookie confirmation is no longer displayed on other browsers. Only with MyPal.
