### ISSUE TITLE
add-on warning

### ISSUE THREAD

**Issue by AroKol78** [Feodor2/Mypal#287]
to the future - attempting to disable old add-ons
new format add-ons = tobin protect ?
[ https://forum.palemoon.org/viewtopic.php?f=3&t=25585#p203120 ]
[ https://repo.palemoon.org/MoonchildProductions/UXP/issues/1659 ]
https://msfn.org/board/topic/180462-my-browser-builds-part-2/page/146/?tab=comments#comment-1190176

**Comment by Feodor2** [comment]
We shall able keep old format as keep webextensions in the cenatury.
