### ISSUE TITLE
Would not print web page

### ISSUE THREAD

**Issue by TiredOfWindows** [Feodor2/Mypal#288]
I could not get Mypal to print a web page! It just spits out a blank piece of paper on my printer. I tried the same web page with Firefox 52.9.0 which is the newest version that will run on WinXP and it printed OK. Are my settings in Mypal correct or is this a defect in Mypal? I did not notice any printing issues in the list of issues.

**Comment by Feodor2** [comment]
What page? Printed this page normally now.

**Comment by TiredOfWindows** [comment]
https://www.jw.org/en/library/magazines/watchtower-no2-2020-may-jun/gods-kingdom-what-is-it/

Page won't print from the file menu or the print button at the bottom of the page.

**Comment by npprabhu** [comment]
Nothing wrong in Mypal 28.15.0. Prints thw webpage fine from both the File Menu as well as bottom of the Webpage.
Links attached.

https://prnt.sc/vhud03

https://prnt.sc/vhue68

**Comment by TiredOfWindows** [comment]
Still can't print web pages from WinXP Pro 64 SP2 with Mypal 28.15.0

**Comment by Feodor2** [comment]
Well i not able to check on winxp64, try with clean profile new portable install

**Comment by TiredOfWindows** [comment]
I discovered under "file types" in folder options that MP is using a MS Office file for printing. I have MS Office XP installed which is a 32 bit app and Mypal is 64 bit. Would this combination be causing my printing problem?

**Comment by TiredOfWindows** [comment]
I pursued the 64 bit verses the 32 bit theory a bit further and installed the 32 bit version of Mypal on my WinXP 64 bit computer. If I use the 32 bit browser, web pages will print! If I use the 64 bit browser, web pages will not print! The 32 bit browser is however a little bit slower (about 32 bits slower). Ha! Ha!

**Comment by Feodor2** [comment]
>that MP is using a MS Office file for printing

Office not needed for printing, set to print directly to printer

**Comment by TiredOfWindows** [comment]
MP64 will print web pages when set to print directly to printer, however there is no spooling. I very rarely print more than one job at a time though.

**Comment by Feodor2** [comment]
I print on x64 win8 with print spooler, it is not related with the office it is a system thing.
