### ISSUE TITLE
.

### ISSUE THREAD

**Issue by gitdrug** [Feodor2/Mypal#29]

**Comment by gitdrug** [comment]
oh is it palemoon being assholes???

**Comment by gitdrug** [comment]
or is it feodor2 being assholes i just want the source bruhhhhhhhhhhhhh

**Comment by gitdrug** [comment]
if someone has the source can i have it

**Comment by paluch-stanislaw** [comment]
www.mypal-browser.org/release/

**Comment by AlbusLuna** [comment]
That's not the source code.

If Fedor provides me with the source code, I'll host it. If anybody reading this is in communication with Fedor, pass the message on to him.

Note: He's put source code for a rebased version of MyPal and a new browser online. What I'm interested in hosting is the previous UXP-based version of MyPal.

**Comment by gdl-blue** [comment]
there is a mirror - https://gitee.com/aeiouaeiouaeiouaeiouaeiouaeiou/Mypal

**Comment by AlbusLuna** [comment]
On 2021-09-20 03:33, gdl-888 wrote:
> there is a mirror -

Thanks. I'm hosting the repo on a gitea instance now. For more 
information and tarball links, visit:
https://albusluna.com/mypal/

**Comment by Zoyandium** [comment]
I am making the source code of 29.3.0 from github available from my 4shared account [Mypal-29.3.0.zip](https://www.4shared.com/web/directDownload/NEvikkYXea/B8-gUmU2.4c6e0fcbf2a692f72e683bc837e33099) just in case Manchild Productions goes down.

**Comment by gdl-888** [comment]
yeah. newer firefox uses multiprocesses and have faster JavaScript engine(Centaury and FF52 also supports too but you need to enable them by yourself, and it is still slower than FF92 because the JavaScript engine is slower)

**Comment by rubyFeedback** [comment]
Good idea Zoyandium - who knows when the source code will be gone. The palemoon forum seems to be on a suicide run right now. Guess more people are going to look for browser alternatives soon...

**Comment by gitdrug** [comment]
> Good idea Zoyandium - who knows when the source code will be gone. The palemoon forum seems to be on a suicide run right now. Guess more people are going to look for browser alternatives soon...

why are the pale moon forms so toxic tryna take cool programs down there dumbasss
