### ISSUE TITLE
(Fixed)¿I there any way to get my add-ons (extension) installed in my PC for add them to another user (account of win 7) (me too) at my PC?

### ISSUE THREAD

**Issue by jazei-AR** [Feodor2/Mypal#291]
Fixed: I did it myself: I searched .xpi files and found them ....
I'd like to put my extensions in others users (accounts win 7) of my PC.... due the problems with pm, I would like to get them by myself,  browsing my  PC (deep web LOL)
Thanks, 
Regards.

**Comment by jbclem** [comment]
Could you say exactly how you moved the xpi files into Mypal?  I've moved a couple of them but they don't show up in the Mypal addons page.  I placed them in the mypal\profiles\xxxxxx.default\extensions file.
