### ISSUE TITLE
cleaning

### ISSUE THREAD

**Issue by AroKol78** [Feodor2/Mypal#295]
@Feodor2  - I know this is Your repository, and it is Your decision.
but if You can close (issues) out of date bugs, duplicate the problems.
it is not known - what was done and what was not.
slowly becoming - garbage can (are even from 2018).
I don't want to offend anyone.

**Comment by Feodor2** [comment]
Sure, i do this but not often, sorry but have such a little time, though today shall clean some.

**Comment by AroKol78** [comment]
don't apologize - **You are in charge**
