### ISSUE TITLE
Яндекс музыка

### ISSUE THREAD

**Issue by P1at0nKirov** [Feodor2/Mypal#296]
Пытался прослушивать Яндекс музыку через Mypal на WinXP. Музыкальные треки не проигрывает, но проигрывает подкасты. С подпиской. Можно что-то сделать? Откорректировать настройки?

**Comment by veselcraft** [comment]
пробовал сменить useragent на свежий фуррифокс, например? мб серверу что-то не нравится, либо браузер кодек кое какой не поддерживает

**Comment by Feodor2** [comment]
Включил первое что попалось без подкаста - играет.

**Comment by P1at0nKirov** [comment]
> Включил
Извиняюсь что пишу с задержкой

> сменить useragent на свежий
Добавил general.useragent.override.yandex.ru со значением Mozilla/5.0 (Windows NT 6.1; WOW64; rv:79.0) Gecko/20100101 Firefox/79.0 и музыка заиграла.

Спасибо.
