### ISSUE TITLE
how to install xpi files in Mypal

### ISSUE THREAD

**Issue by jbclem** [Feodor2/Mypal#298]
I'm trying to figure out a way to get some of my favorite addons into Mypal.  I tried moving one of them(Memory Fox) into the Mypal directory (where I have uBlock Origin), but it didn't show up in the addons page.   I also tried HideFixedElements.  And also I tried dragging/dropping the respective icons from Firefox 52.9 ESR to Mypal, but no luck.

Is there a specific procedure to get this to work?

**Comment by npprabhu** [comment]
@jbclem 
Just Drag n Drop the .xpi file in the Mypal open new window. The addon should install if it is compatible with Mypal, else please do post the screen shots of Error you are getting. Hope that you are using a fresh clean profile..

**Comment by jbclem** [comment]
Drag and Drop didn't work for the first two I tried, but it worked for the next five.  It failed on a few others because they were WebExtension types, but the ones I got in will make a big difference for me.  Thanks for the help...
