### ISSUE TITLE
looking for updates is not working

### ISSUE THREAD

**Issue by jazei-AR** [Feodor2/Mypal#299]
I download manually instead
Looking for updates: ![SnapShot_201126_070916](https://user-images.githubusercontent.com/72522918/100337724-86612980-2fb6-11eb-86bc-facce70daa6f.jpg)

There is not Update: ![SnapShot_201126_070212](https://user-images.githubusercontent.com/72522918/100337758-8f51fb00-2fb6-11eb-9d0c-a4cfa905ec93.jpg)

**Comment by AroKol78** [comment]
update will be if it is on https://github.com/Feodor2/Updserv

**Comment by Feodor2** [comment]
Will be later today
