### ISSUE TITLE
Fix the tags

### ISSUE THREAD

**Issue by THEtomaso** [Feodor2/Mypal#30]
If you're gonna have two different browsers in the same repository, you should at least fix the tags.

Currently, the "Centaury" tag only shows Centaury 0.0.1:
https://github.com/Feodor2/Mypal/releases/tag/Centaury/

..and the "Mypal" tag only shows Mypal 28.1.0:
https://github.com/Feodor2/Mypal/releases/tag/Mypal/

**Comment by THEtomaso** [comment]
Why not simply create a separate repository for Centaury (github.com/Feodor2/Centaury)?
This will make it much easier to share links to your browsers.

**Comment by THEtomaso** [comment]
Try asking here:
https://github.com/DandelionSprout/adfilt/issues/7/
It's more like a forum thread, and a good place to get answers for such questions.

**Comment by Feodor2** [comment]
I have copied manually so this is resolved
