### ISSUE TITLE
Is it difficult to add a built-in memory cleaner in mp? Feodor

### ISSUE THREAD

**Issue by jazei-AR** [Feodor2/Mypal#300]
I'd like to use mp with a built-in automatic every 5 minutes Free Memory option.... like Free mem turbo in the pass

**Comment by Feodor2** [comment]
I have no idea how to do this, i suggest restart as i do when memory become low.
Whats wrong with your "Free mem turbo in the pass" then?

**Comment by AroKol78** [comment]
(about:config) set limit page undo page and limit new pages,javascript settings gc,max mem,water mark.
there is still an option **memory.free_dirty_pages**
additional load CPU every 5 minutes

the current mechanism for "Free Memory" **is fine for me**

**Comment by AroKol78** [comment]
"Lull The Tabs - unload inactive tabs to free up browser memory"
https://github.com/JustOff/lull-the-tabs
