### ISSUE TITLE
omni.ja file

### ISSUE THREAD

**Issue by rmmaniac** [Feodor2/Mypal#302]
Starting from version 28.16.0
the original good old omni.ja file has been encrypted, 
Unable to View File Anymore.😰😰😰

**Comment by AroKol78** [comment]
no encrypted
is new compression format [Brotli](https://github.com/google/brotli)

code set in [Mypal_Release](https://github.com/Feodor2/Mypal/commits/Mypal_Release)

-  [Mypal] Apply libjar improvements.
- [packager] Optimize archive accesses.
- Update libjar module.
- Update Brotli lib to 1.0.9.

**Comment by rmmaniac** [comment]
Is it possible to go back to deflate compression?
 brotli compression is not allowed to view omni.ja file Anymore, which is equivalent to encrypted, 
 which is not helpful for an open source code , especially for extension developers

**Comment by AroKol78** [comment]
question to the boss @Feodor2

**Comment by Feodor2** [comment]
You can view this files so don`t tell. Open **resource:///** in the address bar and enjoy viewing.
What extension do you develop by the way?

**Comment by rmmaniac** [comment]
thank BOSS
and what is the url for this file ->mypal\omni.ja

**Comment by Feodor2** [comment]
Don't you able to select files, what file do you look?
