### ISSUE TITLE
¿Is there any way to block (means: non dowload) heavy images from webpage?

### ISSUE THREAD

**Issue by jazei-AR** [Feodor2/Mypal#303]
not all websites are made for webmasters, sometimes home made pages are uploaded for common people (0 zero internet) so they upload heavy pics of 500Kb to 1.5 GB 2000pxX2600px even if they get ultra mega hipper hipper cam that take pics of 5 billions of billions pixels they will take and upload those  pics of infinity Mb..
I'd like to protect me of that heavy content.... I'd like filter those ultra pics...
is it possible?

**Comment by AroKol78** [comment]
add [uBlock-for-firefox-legacy](https://github.com/gorhill/uBlock-for-firefox-legacy) and options [No large media elements](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-large-media-elements)

**Comment by jazei-AR** [comment]
> 
> 
> add [uBlock-for-firefox-legacy](https://github.com/gorhill/uBlock-for-firefox-legacy) and options [No large media elements](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-large-media-elements)
Thanks a lot!!!! you're Jesus!!!! God saves you!!!
and it works toooooo fine!!! Thank you again @https://github.com/AroKol78 you give me the peace to my life!! those heavy pics destroy me!!!
