### ISSUE TITLE
¿is there a Task manager in mypal?

### ISSUE THREAD

**Issue by jazei-AR** [Feodor2/Mypal#304]
I know that ublock origin only uses 7Mb of Ram (genial!!!!!l 6.000.000 people use it) but I'd like to check it here in mypal! is it possible use task manager?

**Comment by AroKol78** [comment]
address bar **about:memory**
press the first button **Measure**
find word **add-ons** check how much memory is used by "uBlock0...."

time 01:05 AM

**Comment by jazei-AR** [comment]
> add-ons

**@AroKol78 guru!!!!!, holy word!!!!!**
