### ISSUE TITLE
where the plugin folder

### ISSUE THREAD

**Issue by Janaue** [Feodor2/Mypal#305]
I use mypal as portable but it's not the structure of portable PM.
For PM I have my sumatra plugin at
XXXX\Palemoon-Portable.win64\Lib\Mozilla\Plugins
so where is it for MP ?

can you adopt the portable structure of Pm for Mypal ?

**Comment by Feodor2** [comment]
Why is to adopt this structure?
If folder does not exist create it, but Plugins only, without Lib\Mozilla which is unecessary redundant.
