### ISSUE TITLE
What version of Firefox is MyPal based on?

### ISSUE THREAD

**Issue by Doxxie** [Feodor2/Mypal#308]
What version of Firefox is MyPal 28 based on?

I changed the value of "general.useragent.override.addons.mozilla.org" and can't install most Firefox addons.

I can't work out the correct version to enter and there are too many different versions when i search with "general.useragent.override".

Thank you for any help.

**Comment by Feodor2** [comment]
52 and do not try to install addons from the addons.mozilla.org they wont work.
I set my own addon page from where you can reach classic addon archive https://github.com/Feodor2/Mypal/issues/145#issuecomment-733012740
