### ISSUE TITLE
Detailed info about Fully portable mode cannot be opened

### ISSUE THREAD

**Issue by sskras** [Feodor2/Mypal#31]
During the setup I press the **(detailed info).** here:

![image](https://user-images.githubusercontent.com/7887758/134051499-89b30a68-0ce4-4a80-a9c5-7f406b293ebc.png)

... and it opens the URL that responds with 404:
https://github.com/Feodor2/Mypal27old/wiki/Portable

I would like to read the related information.

**Comment by Feodor2** [comment]
https://github.com/Feodor2/Mypal/wiki/Portable

**Comment by sskras** [comment]
Thanks. 
Were the install-package sources also in the old repository?

**Comment by Feodor2** [comment]
Yes

**Comment by sskras** [comment]
Umm, I failed to find it using GitHub search:
https://github.com/ManchildProductions/MyPal/search?q=detailed+info

Where can I find this string?

**Comment by Feodor2** [comment]
https://github.com/ManchildProductions/MyPal/commit/f21a39b65004145f4a041ef7123549d8b3d2b8ea

**Comment by sskras** [comment]
Thank you.
