### ISSUE TITLE
Any way to work on Skype web

### ISSUE THREAD

**Issue by TheElf01** [Feodor2/Mypal#310]
https://web.skype.com/

Im working for a customer use skype,  im forced to use 360 browser (chrome based)  any ideas if possible to use in mypal?  i tried chrome user agent, etc no luck

**Comment by TheElf01** [comment]
By the way...  the github editor is not working neither... i want to add a image, or edit my previus post... not working the menus  :)

I just want to add a image withn the skype error


STARTUP_LOAD_ERROR

**Comment by AroKol78** [comment]
> By the way... the github editor is not working neither... i want to add a image, or edit my previus post... not working the menus :)

FIX github ! https://github.com/Feodor2/Mypal/issues/272

I will not help with Skype because I do not use it and I do not know

**Comment by TheElf01** [comment]
> 
> 
> > By the way... the github editor is not working neither... i want to add a image, or edit my previus post... not working the menus :)
> 
> FIX github ! #272
> 
> I will not help with Skype because I do not use it and I do not know


Thanks!! github fixed!! 

About skype no problem, i can use chrome.  I realize how much skype is used in corporated enviroments,  almost every company i do some work, ask me skype chats

wish i can do in mypal and not in a chinesse horrible browser jaja

**Comment by jazei-AR** [comment]
> 
> 
> > > By the way... the github editor is not working neither... i want to add a image, or edit my previus post... not working the menus :)
> > 
> > 
> > FIX github ! #272
> > I will not help with Skype because I do not use it and I do not know
> 
> Thanks!! github fixed!!
> 
> About skype no problem, i can use chrome. I realize how much skype is used in corporated enviroments, almost every company i do some work, ask me skype chats
> 
> wish i can do in mypal and not in a chinesse horrible browser jaja

yeahh i was going to ask you about how you get the installation of 360... it is all in chinesse I could not test 360 because of I installed and uninstalled by memory steps.. a horror

**Comment by AroKol78** [comment]
these repositories are for "Mypal" not "360 ...chinesse"

**Comment by Feodor2** [comment]
Even if it possible to trick skype for accept mypal, no other stuff beside text will be possible.
https://github.com/Feodor2/Mypal/wiki/Vidochat-and-conference-stuff

**Comment by jazei-AR** [comment]
a little help: if you have little RAM try slimjet browser a savings RAM chromium for skype,

**Comment by StefCraps** [comment]
> > > By the way... the github editor is not working neither... i want to add a image, or edit my previus post... not working the menus :)
> > 
> > 
> > FIX github ! #272
> > I will not help with Skype because I do not use it and I do not know
> 
> Thanks!! github fixed!!
> 
> About skype no problem, i can use chrome. I realize how much skype is used in corporated enviroments, almost every company i do some work, ask me skype chats
> 
> wish i can do in mypal and not in a chinesse horrible browser jaja

Use 360 Extreme Explorer i'm writing from it now and works fine

**Comment by StefCraps** [comment]
> > > > By the way... the github editor is not working neither... i want to add a image, or edit my previus post... not working the menus :)
> > > 
> > > 
> > > FIX github ! #272
> > > I will not help with Skype because I do not use it and I do not know
> > 
> > 
> > Thanks!! github fixed!!
> > About skype no problem, i can use chrome. I realize how much skype is used in corporated enviroments, almost every company i do some work, ask me skype chats
> > wish i can do in mypal and not in a chinesse horrible browser jaja
> 
> yeahh i was going to ask you about how you get the installation of 360... it is all in chinesse I could not test 360 because of I installed and uninstalled by memory steps.. a horror

I have english version
