### ISSUE TITLE
Your browser supports WebGL

### ISSUE THREAD

**Issue by kitaro1** [Feodor2/Mypal#312]
OK https://get.webgl.org/
NO https://speed.cloudflare.com/
Why?

**Comment by AroKol78** [comment]
test https://webglreport.com/ (webgl1 for xp, webgl2 not for xp)
I am using `true`
```
webgl.force-enabled
layers.prefer-d3d9
layers.acceleration.enabled
layers.acceleration.force
gfx.direct2d.disabled
```
`https://speed.cloudflare.com/`
error in the code Mypal (not webgl)
should be fixed in the future
```
https://msfn.org/board/topic/180462-my-browser-builds-part-2/page/159/?tab=comments#comment-1192486
https://repo.palemoon.org/MoonchildProductions/UXP/issues/1697
https://repo.palemoon.org/MoonchildProductions/UXP/issues/1698
https://forum.palemoon.org/viewtopic.php?p=205298
```
(only the map displays well)

ps.
my two old comments https://github.com/Feodor2/Mypal/issues/218
