### ISSUE TITLE
collecting PDF.....any help: ¿how do you add different pdf files into 1?

### ISSUE THREAD

**Issue by jazei-AR** [Feodor2/Mypal#314]
asking  for Guru helping: what should I use? I do? collecting PDF.....any help: ¿how do you add different pdf files into 1 pdf file (all in 1)? for example some emails saved as pdf added in 1 pdf like a list:

opening pdf file you will see:
- 1º email pdf

- 2º email pdf

- 3..... pdf

- other pdf file...

Thank you!!!
Regards!!!!

**Comment by Feodor2** [comment]
It is impossible, mypal is not suitable for this. With mypal only can download pdf files then search software in the web. Try "merge pdfs"

**Comment by jazei-AR** [comment]
> 
> 
> It is impossible, mypal is not suitable for this. With mypal only can download pdf files then search software in the web. Try "merge pdfs"
Thank you!!!!!!
