### ISSUE TITLE
History and Bokmark problem

### ISSUE THREAD

**Issue by rocky7717** [Feodor2/Mypal#317]
Using latest MyPal  28.17....WinXP sp3

1)..Notice that under History now that when I go to the History tab at "show all History" it goes to Library section which shows .nothing....Is it possible to get that back again?
2) Under bookmarks I have several sites that I no longer want or use...when I go to "delete" them,nothing happens..they don,t delete...never had this problem on prior versions....How to fix??

Thanks

**Comment by Feodor2** [comment]
Not confirmed, so tell how to reproduce.

**Comment by rocky7717** [comment]
"Not confirmed, so tell how to reproduce."....Well i am not sure what you are saying here....For #1,Under History,The tab "show all history" goes to "library" which shows nothing..

As for #2  it should be self explanatory....I want to delete certain sites from my "bookmarks",but when I try to do that,they DO NOT delete...Has never happened like this before...

**Comment by Feodor2** [comment]
I say that i do not have such issuse - history shows normally, bookmarks deletes too. I ask you how to reproduce.
Or make clean install and check there.

**Comment by rocky7717** [comment]
So I took your advice  and did a "clean" install and everything is now working like it should...obviously something got corrupted along the line of installing newer versions....

Good to go now...Thanks
