### ISSUE TITLE
Can't resume browser after waking up from sleep

### ISSUE THREAD

**Issue by krzysiobal** [Feodor2/Mypal#323]
Hello, thank you for supporting Windows XP SP3 users.  I was using firefox for a dozen of years but when most websites stopped working properly, I found this Mypal as alternative. Some problems were solved, some different started to appear.

Anyway, when I wanted to create github account to report issue, the spinner was displayed and I coudlnt see any verification image/video or whataver. None of other browsers on XP (Firefox, Advanced_Chrome_v54.20.6530.0) worked either. I had to install Windows 7 and newest firefox to sign up to gitgub. What an irony.

Ok going to subject. When I push power button on my laptop to make it go to sleep and then resume after few hours, I can't see the mypal window (it appears on the taskbar, but when I click it, nothing happens). The only way is to kill it using task manager and then rerun. This problem does not appear when computer goes to sleep and is woken up immediatelly. There must be delay of few hours. Maybe something gets stucked when the current hour number before and after wake up are different?

**Comment by AroKol78** [comment]
> Anyway, when I wanted to create github account to report issue, the spinner was displayed and I coudlnt see any verification image/video or whataver. None of other browsers on XP (Firefox, Advanced_Chrome_v54.20.6530.0) worked either. I had to install Windows 7 and newest firefox to sign up to gitgub. What an irony.

install the browser add-on from https://github.com/Feodor2/Mypal/issues/272
or directly
https://github.com/JustOff/github-wc-polyfill/releases

**Comment by jazei-AR** [comment]
save energy!!! not sleep!!! save works and turn off the laptop for hours sleep 
I use "hibernating" from MS Start menu to resume the session 
win 7 PC and my dead by rain drop netbook
