### ISSUE TITLE
WIX.COM - anybody been able to use this dumb service?

### ISSUE THREAD

**Issue by bushy555** [Feodor2/Mypal#324]
No issue, just a rant and a question.

All,
Just a general enquiry to anybody and everybody. Has anyone managed to use WIX.COM with out it whinging its dumb head off about using an old browser?
I wanted to send their contact / support a mouth full, telling them that their website is utter rubbish if Mypal wont run on it. But then there contact support page also didnt open properly for me.
I take it that they also have dumb weird stupid crappy scripts that is simply not generic and universal.

Any site that I find that doesn't work with Mypal now, I try and give them a blast in everyway I can. Its absolute crap that those of us that wish to continue to run XP and run the brilliant Mypal broswer, that we have to put up with programmers laziness and crappy code.  

I want to go back to 2003 era when the internet was fun and great to use!

/dave

**Comment by Feodor2** [comment]
This is a website builder, i would agree it is dumb, all website builders are dumb more or less. Made for ignorant people can make their own dumb site also for greed people who hire cheap ignorants to make them a site with builder. What site do you want?

**Comment by bushy555** [comment]
...just wanted to make something quick, as in 5 minutes, to shove something up. Gave up with wix - the stuff that did work all looked way too hard anyway.  Got a few angelfire sites from years ago, so ended up just finding one of them and shoving in my dead simple html code (written in notepad) straight into another new page hanging off it. 

All good. Please close this support issue.
