### ISSUE TITLE
Add a bookmark setting

### ISSUE THREAD

**Issue by gdl-888** [Feodor2/Mypal#329]
Can you add a setting to add bookmarks to the toolbar by default? It adds to \<unsorted bookmarks\> be default.

**Comment by Feodor2** [comment]
Sorry did not understand what do you want, on the toolbar can add whatever you want,

**Comment by Grishanenko** [comment]
Видимо, ТС хочет чтобы при нажатии на звездочку, закладка появлялась не в "несортированных", а сразу вылазила на панель. Без второго нажатия на звездочку и выбора панели.

**Comment by Feodor2** [comment]
Тогда проще мышой перетащить, ждём ответа ТС.

**Comment by gdl-888** [comment]
> (Translation: Russian to English) Then it's easier to drag with the mouse, wait for the TS response. 

How can I drag it to the toolbar?(I know with Organize Bookmarks, but I can't drag the star or something)

**Comment by Feodor2** [comment]
Сlick and hold wanted tab in the tab bar then you can drag it.
