### ISSUE TITLE
29.0 New Version Released at Palemoon

### ISSUE THREAD

**Issue by ByRodrigoSoares** [Feodor2/Mypal#331]
Any prediction for the release of this update on MyPal

**Comment by ByRodrigoSoares** [comment]
Are these Palemoon updates applicable on Mypal ??

**Comment by Feodor2** [comment]
Sure, there usual not significant updates, i am going to publish new release before week end.

**Comment by Feodor2** [comment]
This is no point to publish 29 release, because 29.0.1 is released, so i shall update and publish later.

**Comment by ByRodrigoSoares** [comment]
Thanks for the effort

**Comment by ByRodrigoSoares** [comment]
I see that in this new update they updated something on youtube studio

**Comment by ByRodrigoSoares** [comment]
Will they be able to remove that message? Your browser is no longer compatible with YouTube

**Comment by Feodor2** [comment]
Look now
