### ISSUE TITLE
Mypal 29.0.1.

### ISSUE THREAD

**Issue by Fran515** [Feodor2/Mypal#336]
Kann not Login to Protonmail.com.

**Comment by Feodor2** [comment]
Login works normally, so tell how to reproduce, what the error etc

**Comment by Fran515** [comment]
Web Konsole:
Successfully compiled asm.js code (total compilation time 4ms; unable to cache asm.js in synchronous scripts; try loading asm.js via <script async> or createElement('script'))  
vendors~index.ce39737a.chunk.js
TypeError: asm.js link error: bad typed array constructor  
vendors~index.ce39737a.chunk.js:109:122078
TypeError: asm.js type error: Disabled by 'asmjs' runtime option  
vendors~index.ce39737a.chunk.js
Successfully compiled asm.js code (total compilation time 1ms; not stored in cache (too small to benefit))  
ed153fd0-8013-4fe5-9748-4da6c3ce2da5
Successfully compiled asm.js code (total compilation time 2ms; stored in cache) 
ed153fd0-8013-4fe5-9748-4da6c3ce2da5
Content Security Policy: Die Bericht-URI (about:blank) sollte eine HTTP- oder HTTPS-URI sein.  
(unbekannt)
Content Security Policy: Die Seiteneinstellungen haben das Laden einer Ressource auf blob:https://account.protonmail.com/63a29af4-3297-4c1e-b2ed-0f44125cdc90 festgestellt ("worker-src 'none'"). Ein CSP-Bericht wird gesendet.  
(unbekannt)
Successfully compiled asm.js code (total compilation time 6ms; not stored in cache (too small to benefit))  
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (total compilation time 9ms; not stored in cache (too small to benefit)) 
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (loaded from cache in 5ms)  
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (loaded from cache in 4ms)  
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (loaded from cache in 12ms)  
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (total compilation time 18ms; not stored in cache (too small to benefit))  
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (total compilation time 22ms; not stored in cache (too small to benefit))  
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (loaded from cache in 20ms)  
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (total compilation time 16ms; not stored in cache (too small to benefit))  
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (loaded from cache in 20ms)  
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (total compilation time 23ms; not stored in cache (too small to benefit))  
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (total compilation time 25ms; not stored in cache (too small to benefit))  
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (loaded from cache in 12ms)  
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (loaded from cache in 6ms)  
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (total compilation time 22ms; not stored in cache (too small to benefit))  
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (loaded from cache in 4ms)  
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (total compilation time 27ms; not stored in cache (too small to benefit))  
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (loaded from cache in 3ms)  
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (total compilation time 25ms; not stored in cache (too small to benefit))  
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (loaded from cache in 3ms)  
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (loaded from cache in 4ms)  
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (total compilation time 30ms; not stored in cache (too small to benefit))  
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (loaded from cache in 4ms)  
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (loaded from cache in 5ms)  
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (total compilation time 33ms; not stored in cache (too small to benefit))  
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (loaded from cache in 5ms)  
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (total compilation time 13ms; not stored in cache (too small to benefit))  
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (total compilation time 15ms; not stored in cache (too small to benefit))  
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (total compilation time 16ms; not stored in cache (too small to benefit))  
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (loaded from cache in 22ms)  
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (loaded from cache in 23ms) 
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (loaded from cache in 22ms)  
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (loaded from cache in 23ms)  
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (loaded from cache in 22ms) 
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (loaded from cache in 19ms)  
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (loaded from cache in 18ms) 
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (loaded from cache in 7ms) 
63a29af4-3297-4c1e-b2ed-0f44125cdc90
Successfully compiled asm.js code (loaded from cache in 6ms) 
63a29af4-3297-4c1e-b2ed-0f44125cdc90
TypeError: asm.js link error: bad typed array constructor  
ed153fd0-8013-4fe5-9748-4da6c3ce2da5:2:59509
TypeError: asm.js type error: Disabled by 'asmjs' runtime option  
ed153fd0-8013-4fe5-9748-4da6c3ce2da5
TypeError: asm.js link error: bad typed array constructor  
ed153fd0-8013-4fe5-9748-4da6c3ce2da5:2:40467
TypeError: asm.js type error: Disabled by 'asmjs' runtime option  
ed153fd0-8013-4fe5-9748-4da6c3ce2da5

**Comment by Fran515** [comment]
Sorry, it is the beta.protonmail.com.
Normal Protonmail is OK.
I have send the Web Konsole to Protonmail as a Issue.
