### ISSUE TITLE
Issues with latest Mypal version for discover.com & computershare.com websites

### ISSUE THREAD

**Issue by joeturnes** [Feodor2/Mypal#339]
1.  Just typing   computershare.com/investor in the latest or prior vers of Mypal ,  i get a popup 
"Your browser is not supported - To get the most out of Investor Centre, we recommend you use the latest version of Chrome, Firefox, Internet Explorer, Microsoft Edge or Safari" 
lol   
However i AM able to close the popup & sign in! Is there a cause for concern here?

2.  With discover.com ,  i can bring up the home page, but  when i try to sign in, it won't let me. 
& says 
"Your account cannot currently be accessed. Outdated browsers can expose your computer to security risks. To get the best experience on discover.com, you may need to updated your browser to the latest version."
Ironically, i 1st saw this after i updated to the latest version  29.0.1 
lol
If i go back to the prior version of Mypal (28.16.0  32 bit), i CAN sign in to discover & do stuff.
Go figure.

In the latest vers of Mypal i tried going into about:config & added 
general.useragent.override.computershare.com
Mozilla/5.0 (Windows NT 5.1; rv:52.0) Gecko/20100101 Firefox/52.0
&
general.useragent.override.discover.com
Mozilla/5.0 (Windows NT 5.1; rv:52.0) Gecko/20100101 Firefox/52.0
Made no difference.

**Comment by AroKol78** [comment]
switch to `true`
`general.useragent.compatMode.gecko`
`general.useragent.compatMode.firefox`

try it out (pretend win8) `Mozilla/5.0 (Windows NT 6.3; rv:68.0) Gecko/20100101 Firefox/68.0`
or increase the numbers **68** > **78** > **84**

**Comment by Feodor2** [comment]
computershare satisfied with
**Mozilla/5.0 (Windows NT 5.1; rv:78.0) Gecko/20100101 Firefox/78.0**
but cant check the second one , try it with this override it may help too

**Comment by joeturnes** [comment]
Feodor2,  your suggested change also works for discover.com

AroKol78, general.useragent.compatMode.gecko & general.useragent.compatMode.firefox
were already set to true.
I made a note of your other suggested change & may try that in the future on other sites, if nec.

Thanks, guys.
