### ISSUE TITLE
Как настроить Mypal

### ISSUE THREAD

**Issue by alexusv** [Feodor2/Mypal#34]
Приветствую Федор. Я люблю WinXP Хочу освоить Mypal
1) Загрузил в расширение  пакет языка ру, а язык не меняется, как изменить язык?
2) Есть хорошее приложение для скрытия IP адреса (secure vpn proxy) как настроить?
3) Есть 100% блокировщик рекламы, можно установить?
4) Есть приложение "Загрузчик видео" любого формата или захвата любого видео с экрана web player?

**Comment by Feodor2** [comment]
1. Да так можно, и делается точно так же как в оригинале но лучше не надо потому для моих майпаловских функций там нет перевода и будут ошибки. Пробуйте мою русскую сборку с руборда: http://forum.ru-board.com/topic.cgi?forum=5&bm=1&topic=49744&start=840#10
28.4 будет на следующей неделе
2-4. Всё настраивать так же как и лису старую 38-45 или оригинал Palemoon, никаких отличий. 
Мои предпочтения: тор, ублок и сейвфромнет.

**Comment by alexusv** [comment]
Горячо Приветствую Фёдор, качнул русскую сборку mypal2840ru.exe, а уже стояла англо! версия с настройками, запускаю mypal2840ru распаковка портэйбл, а открывается только англо версия, как ни крути. Видима идёт пересечение и что то надо удалить из версий?
            Вопрос 2 : Возникла задача с ПК ответить в личку (директ ) Инстаграм и залить видик...,  в браузере хроме для ХР в коде есть функция "эмулятор смартфона андроид" и даже фотки заливает,  но не может ответить в личку (директ ) и залить видео. Пытался ставить эмулятор BlueStacks для ХР очень громоздкий(300мб) и требовательный к ресурсам и железу, в конце установки ругнулся на видеокарту и прервал установку. Я Стал в бр-е хроме искать расширения(директ инста.) они есть, но не работают. Кстати в Mypal инстаграм не открывается,  пустая страница. Думаю может по ветке Лисы есть стоящие расширения(директ инста.) есть соображения???

**Comment by alexusv** [comment]
Я на другом ПК открыл mypal2840ru.exe он же пельмень,, если это портэйбл то как обновлять? Новый загружать и делать настройки заново?

**Comment by Feodor2** [comment]
>mypal2840ru распаковка портэйбл, а открывается только англо версия, как ни крути. Видима идёт >пересечение и что то надо удалить из версий?

mypal2840ru не должно пересекаться ничем, это странно. Я проверю.

>в браузере хроме для ХР в коде есть функция "эмулятор смартфона андроид"

Не подскажу, не знаю. Возможно если такое есть для лисы можно будет попробовать подделать на пельмень

>Кстати в Mypal инстаграм не открывается, пустая страница.

Да, похоже это проблема совместимости с лисой, нужно переключить настройку **совместимость** Useragent на _**Собственный**_




**Как обновить и сохранить настройки.** 
_Предположим браузер записан на C:\mypal_
1. Переименовать C:\mypal в C:\mypal.old если mypal.old уже есть то сначала удалить его
2. Распаковать новый mypal***ru.exe в C:\mypal
3. Удалить C:\mypal\profile
4. Скопировать C:\mypal.old\profile в C:\mypal

**Comment by alexusv** [comment]
Приветствую Федор. Спасибо за доходчивый расклад обновления, но это касательно инсталляции. У меня скачен с Руборда по твоей ссылке mypal2840ru.exe портэйбл! установки я не видел русской.
У меня установлен англ. mypal но я не вижу там ...mypal\profile где такая папка или файл?

**Comment by Feodor2** [comment]
В обычной установке, профиль отдельно от програмных файлов в appdata\mypal, обновлять можно только программные файлы, но рекомендую делать запасную копию профиля.

**Comment by alexusv** [comment]
Приветствую Федор,  обновил mypal-28.6.1.win32 поставил расширение uBlock Origin 1.6.6  В расширениях uBlock появился и включен, а на панели значка нет и как им управлять не понятно, что не так? А в mypal-28.6.1ru портэйбл есть значок на панели.
Насчёт "...Мои предпочтения: тор, ублок и сейвфромнет...." Хотел установить SaveFrom.net на Win XP в браузер Google Chromе и в mypal-28.6.1    Есть сайт: http://savefrom.download-windows.org/windows-xp 
 Есть сайт: https://savefromnet-ru.ru/
Есть сайт: https://ru.savefrom.net/userjs-for-google-chrome.php У всех свои пакеты установки и инструкции КОМУ ВЕРИТЬ, что ставить и что будет работать??? Я запутался подскажи пожалуйста

**Comment by alexusv** [comment]
Приветствую Федор, обновил mypal-28.6.1.win32 поставил расширение uBlock Origin 1.6.6 В расширениях uBlock появился и включен, а на панели значка нет и как им управлять не понятно, что не так? А в mypal-28.6.1ru портэйбл есть значок на панели uBlock Origin 1.1.6.4.
Насчёт "...Мои предпочтения: тор, ублок ...."  "тор" это цельный браузер надо ставить для скрытия IP адреса (secure vpn proxy)???

**Comment by Feodor2** [comment]
Значёк обычно сам должен появляться, но может быть не совместимость с другими дополнениями. Выведи значёк вручную, после перезапуска он должен оставаться на месте.

Тор отделно скачать и запускать можно, ищи по expert bundle. В настройках пельменя нужно указать прокси и в агенте что это торброузер, и запертить флеш, потому что он идёт в обход прокси и засветить реальный айпи.

**Comment by alexusv** [comment]
Горячо приветствую Фёдор. Обновился до mypal_portable_ru 28.7.2  распаковал в папку, вставил туда profile. А когда выйдет новая версия я могу распаковать нвый архив в эту папку с заменой файлов да?
Фёдор почему когда я указываю https://yandex.ru/ браузер меняет адрес на домен https://yandex.ua/???  Кстати в инглишь версии браузер не меняет домен и как я заметил быстрей открывает страницы.

**Comment by Feodor2** [comment]
Да, но не заменять prefs.js и другие файлы настроек, типа ini json и т.д. - бо они настройки собьются.

В русской сборке дополнение вкомфорте оно для украины только, и последнее время хуже страницы открывает, если нет необходимости удалите или отключите.

**Comment by alexusv** [comment]
Фёдор мне всё равно не понятно почему если я указываю конкретный адрес и домен RU  то mypal_portable_ru  самовольно меняет на  UA так он может меня отсылать бог знает куда и почему именно https://yandex.ua??  Или mypal_portable_ru и по другим адресам косячит??? Вбиваешь одно, а показывает другое. Почему инглишь версия работает корректно и не отсылает меня на Домен .UK (Англия).
В исходном коде или в сис. настройках я могу убрать этот доменный косяк???
    И второе можно ли к обоим сборкам прицепить переводчик как в хроме кликая правой кнопкой на поле страницы вызвать в контексте "перевод страницы"??? Очень удобная функция

**Comment by alexusv** [comment]
.......если нет необходимости удалите или отключите.

Originally posted by @Feodor2 in #34 (comment)

Что удалить или отключить mypal ru или кусок кода или файл?

**Comment by alexusv** [comment]
Фёдор мне всё равно не понятно почему если я указываю конкретный адрес и домен RU то mypal_portable_ru самовольно меняет на UA так он может меня отсылать бог знает куда и почему именно https://yandex.ua?? Или mypal_portable_ru и по другим адресам косячит??? Вбиваешь одно, а показывает другое. Почему инглишь версия работает корректно и не отсылает меня на Домен .UK (Англия).
В исходном коде или в сис. настройках я могу убрать этот доменный косяк???
И второе можно ли к обоим сборкам прицепить переводчик как в хроме кликая правой кнопкой на поле страницы вызвать в контексте "перевод страницы"??? Очень удобная функция

**Comment by Feodor2** [comment]
>Фёдор мне всё равно не понятно почему

дополнение вкомфорте

>прицепить переводчик

искать в дополнениях, например https://addons.palemoon.org/addon/translatethis/
и в старых дополнениях #112

**Comment by alexusv** [comment]
Непривычный формат переписки здесь,, я здесь не могу удалить свою красноту "закрыто"? 

ПРИВЕТСТВУЮ Федор.
Хочу обновить инглишь Mypal установку забыл где профиль?
Выше писалось; "В обычной установке, профиль отдельно от програмных файлов в appdata\mypal, обновлять можно только программные файлы, но рекомендую делать запасную копию профиля."
Нашлось:
C:\Documents and Settings\.....\Local Settings\Application Data\Mypal\Profiles  и C:\Documents and Settings\....\Application Data\Mypal\Profiles где что?
И ещё можно перекидывать Profile из портэйбл рус в инглишь установку и обратно???

**Comment by Feodor2** [comment]
C:\Documents and Settings.....\Local Settings\ не нужно

> И ещё можно перекидывать Profile из портэйбл рус в инглишь установку и обратно???

Из моей не надо, там все языки кроме русского удалены, а так да.

**Comment by Shestoperd** [comment]
Возможно ли как-то настроить синхронизацию закладок между MyPal и FF?
Раньше было неплохое дополнение XMarks, но к сожалению оно уже не работает.
Может есть что-то подобное? Нужна синхронизация только закладок, но если будет еще и история/вкладки, то тоже неплохо.

**Comment by Feodor2** [comment]
Могу попробовать починить дополнение.

**Comment by Shestoperd** [comment]
> Могу попробовать починить дополнение.

Сервис XMarks уже закрыт :( 
Нужен какой-то альтернативный путь или дополнение, которое будет работать и на новых FF и на MyPal. 
Вручную можно без проблем черезе бекап закладок синхронизировать, но это быстро надоест. Или как-то через облачный сервис настроить.
Наверняка кто-то уже задавался такой целью, но поиск ничего путного не дает.

**Comment by Feodor2** [comment]
Идея поднять сервис локально, потом на облако переделать что-ли.
Я вот задаюсь синх сделать без сервисов.

**Comment by Shestoperd** [comment]
> Идея поднять сервис локально, потом на облако переделать что-ли.

Если бы на XP работали GoogleDrive или Dropbox, то можно было бы попробовать настроить синхронизацию папок с бекапами. Может можно использовать эти сервисы без установки официального приложения? В андроидных приложениях я встречал возможность бекапов в облака dropbox-a и/или googledriv-a, т.е. существует api позволяющее приложениям это делать без необходимости установки оф.приложения. 


> Я вот задаюсь синх сделать без сервисов.

Нужно чтобы оба браузера были запущены одновременно, или все равно придется использовать временное хранилище где-то в облаке.

**Comment by irafat** [comment]
Я использую MyPal в LiveUSB с загрузкой полгностью в оперативную память, потому что меня устраивает достаточно маленький размер этого браузера (изначально ~150 Мб). Но в процессе работы его разиер раздувается свыше 450 Мб за счет того, что в папку Profile\cache2\entries пишется огромное количество каких-то файлов, причем, если их удалить, то на работе браузера это никак не сказывается (по крайней мере, у меня). Можно ли вообще запретить MyPal писать файлы в папку Profile\cache2\entries?

**Comment by irafat** [comment]
PS. Используется портативная версия MyPal с загрузкой в оперативную память.

**Comment by Shestoperd** [comment]
> Можно ли вообще запретить MyPal писать файлы в папку Profile\cache2\entries?

Попробуй отключить в настройках автоматическое управление кешем и уменьшить размер вручную.
Настройки/ Дополнительно/ Сеть/ Кешированное веб-содержимое.

**Comment by alexusv** [comment]
Приветствую  Фёдор. Подскажи пожалуйста блокировщик рекламмы что сейчас актуально и работает для англ. майпал 28.15

**Comment by alexusv** [comment]
мне попался uBlock0_1.16.4.26.firefox-legacy.xpi

**Comment by Shestoperd** [comment]
Я пользуюсь uBlock Origin 1.16.4.26 https://github.com/gorhill/uBlock-for-firefox-legacy
Работает хорошо, проблем нет.
Еще пробовал в пару к нему NoScript, но часто возникали проблемы на некотрых сайтах, где есть зависимости от внешних скриптов и нужно все разрешить, чтобы эти сайты нормально работали, потому пока отключил, uBlock справляется.

**Comment by alexusv** [comment]
И второй вопрос по майпал 28.15. В бр-е хроме в строке поисковика всегда появляется микрофон-голосовые команды, в майпал 28.15 микрофон исчез, если надо включить то где???

**Comment by alexusv** [comment]
Поставил расширение Google Translate и запарился: тупит и каждый раз предлагает выбирать в длиннющем списке языков с какого на какой переводить, запомнить не может и в настройке убогой толком не могу чётко указать постоянную комбинацию, как быть???
В б-р хроме в контексте в два клика и страница или текст переведены

**Comment by Feodor2** [comment]
>микрофон исчез, если надо включить то где

Я почти изначально делал сборки без этой функции, она была раньше в оригинале, не знаю даже работало ли или нет, разработчики оригинала решили удалить как ненужный хлам. Так что её нет и в оригнале уже тоже, имхо таки ненужный хлам.

>Поставил расширение Google Translate

Поискать другое расширение, не гуглом едины...


Извините, но вообще мне плевать как там что-то в хроме я на него не равнялся и не буду.

**Comment by Shestoperd** [comment]
Про Google Translate, я использую плагин Open in Google™ Translate 0.1.2 из комплекта Classic Add-ons Archive, работает именно так как мне нужно.

**Comment by Vseslav3** [comment]
Дорогой Федор! Мне нравится ваша программа и я ее использую как на работе (WinXP), так и дома (Win10 x64). На Win10 x64 не видны заголовки меню, они белые, но при нажатии на них выпадают меню с темным текстом.
Подскажите. пож-та, как поменять в заголовках менюшек шрифт на темный. 
И второй вопрос. Часто пропадает курсор мыши при редактировании сообщений на сайте, но мышь при этом работает.
Пробую сейчас менять скорость реагирования мыши, чтобы устранить проблему.
Может и вы что подскажете

**Comment by Feodor2** [comment]
Нет win10, вообще не пользуем эту дрянь, но есть идея как помочь. Нужно уточнить где менять цвет - сделайте принтскрин.

**Comment by Vseslav3** [comment]
если щелкаю мышью вне окна mypal, менюшки видны
[url=https://radikal.ru][img]https://b.radikal.ru/b09/2011/28/a66a77a73c86.jpg[/img][/url]
если щелкаю мышью в окнt mypal, менюшки не видны
[url=https://radikal.ru][img]https://c.radikal.ru/c20/2011/60/d26692e83875.jpg[/img][/url]
А Windows 10 был вынужден поставить на новое железо, никакая другая система не ставилась

**Comment by Vseslav3** [comment]
если щелкаю мышью вне окна mypal, менюшки видны
Image1
[img]https://b.radikal.ru/b09/2011/28/a66a77a73c86.jpg[/img]
если щелкаю мышью в окнt mypal, менюшки не видны
Image2
[img]https://c.radikal.ru/c20/2011/60/d26692e83875.jpg[/img]
А Windows 10 был вынужден поставить на новое железо, никакая другая система не ставилась

**Comment by Vseslav3** [comment]
Не получается вставить картинки. Попробую так

если щелкаю мышью вне окна mypal, менюшки видны
Image1
https://b.radikal.ru/b09/2011/28/a66a77a73c86.jpg
если щелкаю мышью в окнt mypal, менюшки не видны
Image2
https://c.radikal.ru/c20/2011/60/d26692e83875.jpg
А Windows 10 был вынужден поставить на новое железо, никакая другая система не ставилась

**Comment by Feodor2** [comment]
Мда намудрили с рисунками, посмотреть можно только самый последний, но по нему ничего непонятно.
В рисунке отметте элемент где нужно изменить цвет скопируйте рисунок и вставте прямо сюда в сообщение гитхаба.

**Comment by Vseslav3** [comment]
Пытаюсь прикрепить  картинку на которой менюшки видны 
если щелкаю мышью вне окна mypal, менюшки видны и обведены красным
если щелкаю мышью в окне mypal, менюшки не видны

**Comment by Vseslav3** [comment]
Вот  ссылка на картинку
https://ibb.co/ZJCCsb1

**Comment by Feodor2** [comment]
Откройте профиль, там откройте chrome и там переименуйте файл userChrome-example.css на userChrome.css. Потом в этот файл добавте текст ниже, перезапустите браузер.
```
menubar{
  background-color: white !important;
  color: black !important;
}
```

**Comment by Vseslav3** [comment]
у меня такой файл отсутствует. Я его создал в папке C:\Users\...\AppData\Roaming\Mypal\Profiles\28vc0vat.default\storage\permanent\chrome\userChrome.css с вашим текстом, но ничего не изменилось

**Comment by Feodor2** [comment]
> у меня такой файл отсутствует

Правильно шо это за "storage\permanent\" я разве писал этот путь,
chrome должен быть в C:\Users...\AppData\Roaming\Mypal\Profiles\28vc0vat.default\,  и в нём файл userChrome.css.
[userChrome.css.zip](https://github.com/Feodor2/Mypal/files/5630146/userChrome.css.zip) вот уже готовый файл в зипе.

**Comment by Vseslav3** [comment]
добавил ваш файл куда вы написали, но результата нет

**Comment by AroKol78** [comment]
распаковать zip

**Comment by Vseslav3** [comment]
конечно распаковал

**Comment by AroKol78** [comment]
на xp это работает (ты забыл о **\chrome**)
**C:\Users...\AppData\Roaming\Mypal\Profiles\28vc0vat.default\chrome**

**Comment by Vseslav3** [comment]
Сработало!!!  Спасибо!!! Создал папку Chrome, которой не было и вставил ваш файл.

**Comment by Vseslav3** [comment]
Осталась более мелкая проблема. При написании постов на форуме https://www.twirpx.com/ регулярно пропадает курсор мыши. Мышь при этом работает с невидимым курсором. В адресной строке мышь есть. Достаточно мышью щелкнуть в адресной строке и курсор появляется на время и в редактиремых строках. Причем этот эффект есть как для версии x32 так и для x64.

**Comment by Feodor2** [comment]
Мне нужно это воспроизвести у себя, где там писать посты?

**Comment by Vseslav3** [comment]
можно выложить какую-нибудь книгу, которой там нет, хотя это не всегда просто, или написать коментарий к какой-нибудь книге

**Comment by Vseslav3** [comment]
раздражают всплывающие окна рекламы. adguard, ublock origin не справляются. Сейчас пробую этот рецепт
https://amitegolive.blogspot.com/2019/10/pale-moon.html
По-моему, действует

**Comment by vmikhaylov097** [comment]
Привет. Когда разбирался в Mypal случайно где то включил режим запускать всегда в режиме инкогнито.
И теперь не могу включить в настройках включить сохранение паролей, и стартовать с последних страниц...
уже и браузер удалял и заново устанавливал, а настройки остаются эти неактивны
![photo_2020-12-17_00-19-32](https://user-images.githubusercontent.com/68975878/102407726-9b513b80-3ffd-11eb-8b47-af34c410e8ed.jpg)
![photo_2020-12-17_00-19-37](https://user-images.githubusercontent.com/68975878/102407739-a1471c80-3ffd-11eb-8c23-68bdb6caf6c9.jpg)
подскажите как сделать эти функции рабочими?

**Comment by vmikhaylov097** [comment]
@Feodor2 
Случайно где то включил "запускать всегда в режиме инкогнито", и теперь опции сохранять пароли и запускать с последними открытыми страницами Неактивны. Не могу найти где выключить это и вернуть работоспособность паролей.
![photo_2020-12-17_00-19-32](https://user-images.githubusercontent.com/68975878/102411731-7364d680-4003-11eb-97fa-ad1de05bd927.jpg)

**Comment by Feodor2** [comment]
@Vseslav3
Непонятно пока, почему пропадает курсор, но если нажиамть "Хочу обратить внимание" то он появляеться.
@vmikhaylov097 
![image](https://user-images.githubusercontent.com/19492771/102544750-f0548680-40bd-11eb-91fe-abd488c73709.png)

**Comment by Vseslav3** [comment]
Дорогой Федор! У меня гугл переводчик перестал переводить web страницы. Это особенность  гугл переводчика или mypal?

**Comment by Vseslav3** [comment]
Работает с гуглом по переаоду web-страниц вот эта ссылка
http://free-website-translation.com/?ru

**Comment by marc49twen** [comment]
Можно ли подключить расширение Browsec VPN ?
И, если можно, то как?

**Comment by Shestoperd** [comment]
> Можно ли подключить расширение Browsec VPN ?
> И, если можно, то как?

Попробуй скачать [Classic Add-ons Archive](https://github.com/JustOff/ca-archive/releases), там есть нужный плагин последняя версия 3.16.16, будет ли он работать не знаю, не проверял.

**Comment by Vseslav3** [comment]
Попробуйте этот Browsec. 
https://www.upload.ee/files/11132691/browsec-2.0.7.1_unofficial.xpi.html
у меня работает.
На ru-board был еще browsec pm-fixed, основанный на 2.0.7 но сходу не нашел. Найдете - киньте ссылку

**Comment by Feodor2** [comment]
3я версия формата webext и не будет работать, возможно  в васильке только будет.

**Comment by marc49twen** [comment]
https://www.upload.ee/files/11132691/browsec-2.0.7.1_unofficial.xpi.html  -  работает
Но при попытке зайти на yandex.ru автоматом сбрасывает на yandex.ua 
это так задумано и не исправляется?

**Comment by marc49twen** [comment]
Кроме того, нельзя сменить страну, т.к. "жестко" вбиты Нидерланды.

**Comment by Feodor2** [comment]
> yandex.ru автоматом сбрасывает на yandex.ua

думаю это к яндексу, то есть еслия захочу yandex.ua то и так введу, а если хочу ru какого художника перекидывать на ua.

>Кроме того, нельзя сменить страну, т.к. "жестко" вбиты Нидерланды.

В бесплатном варианте да

**Comment by justperson622** [comment]
Здравствуйте! Большое спасибо за браузер, только им и спасаюсь при работе в XP. Появился вопрос - как полностью скопировать профиль для переноса в другого пользователя? Желательно с историей, закладками, данными автозаполнения.win xp. mypal последней версии.

**Comment by Shestoperd** [comment]
> как полностью скопировать профиль для переноса в другого пользователя? Желательно с историей, закладками, данными автозаполнения.

Меню "Справка"/"Решение проблем" там "Папка профиля" - "открыть профиль". Копируй всю папку.

**Comment by kawadik55** [comment]
Здравствуйте! На алиэкспрессе не сохраняются автоматически данные для входа. Можно ли как то руками вписать нужное в "Сохраненные логины"? 29.2.0 (32-bit)

**Comment by Feodor2** [comment]
Попробуйте скопировать файлы паролей из новой лисы, с этим сохранённым паролем.

**Comment by kawadik55** [comment]
У меня старая лиса, там только key3, 4-го нету...

 
 
 -----Original Message-----
