### ISSUE TITLE
Feodor2 didn't break MPL.

### ISSUE THREAD

**Issue by glowiak** [Feodor2/Mypal#34]
Put Mypal files in password-protected directory (of course, password would be on the website) on some web disk. The files should be marked as private, so nobody could have something to that.

BTW™ palemoon devs should reject their words. Feodor2 didn't break MPL. Source code of Mypal is distributed (or at least was, before palemoon devs deleted that) via 'GitHub' button on the website ( http://mypal-browser.org ).

To agressive palemoon devs: reject your words and stop shutting down Mypal btw™

Source: my comment on reddit ( https://www.reddit.com/r/windowsxp/comments/pwmb1f/i_think_i_can_resolve_the_problem_details_in/ )

**Comment by AlbusLuna** [comment]
On the other hand, ironically, Matt Tobin has broken MPL himself and in a conscious and egregious manner. If somebody would like to initiate legal actions against Matt, I'll help to pay for it. For more information, see the following page:
[https://albusluna.com/mypal/](https://albusluna.com/mypal/)

Look for a picture of an iron and you'll find an explanation of Matt's own license violations. The UXP Mypal source code is distributed in 4 different ways on the same page. Enjoy.

**Comment by highbaser** [comment]
@Feodor2, please bring back Mypal into development.

**Comment by Feodor2** [comment]
> Put Mypal files in password-protected directory (of course, password would be on the website) on some web disk

You may use mypal-browser.org free, why password-protected is necessary? Duplicate if you want, but do care about malware, сheck and also put md-sha codes, and put link to the source too.

> To agressive palemoon devs: reject your words and stop shutting down Mypal

Leave them be, it was their goal fence themselves off and make that only one trustworthy can use their stuff.

> please bring back Mypal into development.

Had to stop development only with palemoon code, i continue development with another code.

**Comment by Anbima** [comment]
@Feodor2
Which browser gets the basis?
This is the right decision because Palemoon makes many problems on new pages.

**Comment by Feodor2** [comment]
i found old things preserved
https://web.archive.org/web/20201107144358/https://github.com/Feodor2/Mypal/issues?page=6&q=is%3Aissue+is%3Aclosed
when i had made all sources in one repo and in the had not put direct links to code in centaury since why tobin left satisfied thats i thought its okey.

you may look also
https://web.archive.org/web/20201107144358/https://github.com/Feodor2/Mypal/issues/30
