### ISSUE TITLE
Error 0x80004005 (NS_ERROR_FAILURE)  using javascript with Mypal and the german language pack

### ISSUE THREAD

**Issue by RainerB57** [Feodor2/Mypal#340]
Error shown in error console, but the error does not appear when I use no language pack:

Fehler: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIStringBundle.GetStringFromName]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: XStringBundle :: getString :: line 22"  data: no]

The error appears as the only error in all my html files that include javascript.
I could ignore the error, but it is annoying when I look for errors in my php-files, that do automatic refresh of the page. So the error appears multiple times.

My example html document: (also attached as js_test.html)
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<title> Test </title>
		<script language="JavaScript">
			function TestFunction() {}
		</script>
	</head>
	<body onload="TestFunction()">
		Just a test. 
	</body>
</html>

**Comment by RainerB57** [comment]
Error shown in error console, but the error does not appear when I use no language pack:

Fehler: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIStringBundle.GetStringFromName]" nsresult: "0x80004005 (NS_ERROR_FAILURE)" location: "JS frame :: XStringBundle :: getString :: line 22" data: no]

The error appears as the only error in all my html files that include javascript.
I could ignore the error, but it is annoying when I look for errors in my php-files, that do automatic refresh of the page. So the error appears multiple times.

My example html document: (attached as js_test.txt)

**Comment by RainerB57** [comment]
Error shown in error console, but the error does not appear when I use no language pack:

Fehler: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIStringBundle.GetStringFromName]" nsresult: "0x80004005 (NS_ERROR_FAILURE)" location: "JS frame :: XStringBundle :: getString :: line 22" data: no]

The error appears as the only error in all my html files that include javascript.
I could ignore the error, but it is annoying when I look for errors in my php-files, that do automatic refresh of the page. So the error appears multiple times.

My example html document: (attached as js_test.txt)

**Comment by RainerB57** [comment]
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<title> Test </title>
		<script language="JavaScript">
			function TestFunction() {}
		</script>
	</head>
	<body onload="TestFunction()">
		Just a test.
	</body>
</html>

**Comment by RainerB57** [comment]
<html><br>
	<head><br>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"><br>
		<title> Test </title><br>
		<script language="JavaScript"><br>
			function TestFunction() {}<br>
		</script><br>
	</head><br>
	<body onload="TestFunction()"><br>
		Just a test.<br>
	</body><br>
</html><br>

**Comment by RainerB57** [comment]
[js_test.txt](https://github.com/Feodor2/Mypal/files/6077660/js_test.txt)
This is the simple test file, but saved as a .txt instead of .html.
I could not send it with Pale Monn or Mypal, but I did with MS Edge.
The eroor is written in my 1st Message.
It also exists in Pale Moon.

**Comment by Feodor2** [comment]
I get the error with empty page too, hope i can fix it upon new version.

**Comment by Feodor2** [comment]
In the browser open plugins language section and delete language pack.
Go to the github mypal 29 release download and install fixed language pack.
Restart the browser and error must gone.

**Comment by RainerB57** [comment]
Thank you,

this is fine now,
the error messages do not appear anymore.
