### ISSUE TITLE
RegEx101.com does not work with Mypal

### ISSUE THREAD

**Issue by RainerB57** [Feodor2/Mypal#347]
I get the message:

Unfortunately it seems your browser does not meed the criteria to properly render and utilize this website.
Please upgrade your browser and come back

I tried with 
general.useragent.override.regex101.com
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0

but it did not help.

**Comment by ghost** [comment]
"RegEx101.com does not work..."
It's a lie. The page is displayed correctly on a fraction of a second in mypal, then covering. Watches and Link Upgrade Browser.
The address of this link is http://browsehappy.com/ and this is the well-known malware browsehappy.com.
Firefox 87 - Displays the page correctly, but with redirection to buysellads.com. You need to block.

**Comment by RainerB57** [comment]
> It's a lie. The page is displayed correctly on a fraction of a second in mypal, then covering. Watches and Link Upgrade Browser.
> The address of this link is http://browsehappy.com/ and this is the well-known malware browsehappy.com.
> Firefox 87 - Displays the page correctly, but with redirection to buysellads.com. You need to block.

What do I need to block?
I tried http://browsehappy.com/ and buysellads.com.
They are blocked now, but RegEx101.com is still only shown for a second and then the message.

**Comment by ghost** [comment]
I was looking for a solution. I set the rendering of mypal - gfx.color_management.mode; 1
@Feodor2 is a specialist here and can say something specific.

**Comment by AroKol78** [comment]
> `@Fedor2 is a specialist ...`

`@Feodor2` > Mypal
`@Fedor2` > ?

**Comment by Feodor2** [comment]
Don't know why, there are no errors in the console, colors stuff wont help, may ask why do they block mypal, also if you say they use malware send them walk pedestrian. There are plenty similar sites.

**Comment by Feodor2** [comment]
Well i have asked
https://github.com/firasdib/Regex101/issues/1537

**Comment by working-name** [comment]
> The address of this link is http://browsehappy.com/ and this is the well-known malware browsehappy.com.

Well-known by who, @kitaro1 ? My adblockers don't signal me, pihole doesn't have that in the default lists.
![browsehappy](https://user-images.githubusercontent.com/16505052/111870885-9635bc80-895d-11eb-98ef-ed170c581a3f.png)

**Comment by ghost** [comment]
Will browsehappy create a problem? Sorry, but that's what I understood. 
https://answers.microsoft.com/en-us/edge/forum/all/repeatedly-got-update-browser-msg-from-numerous/a7e66f5b-ab4d-4da7-a777-8ae0a51d25df

**Comment by working-name** [comment]
It's just a presentation site for the major currently maintained browsers. If it doesn't offer anything for you to download and run, doesn't display ads, doesn't do anything malicious why would it be a problem? It's also apparently made by the wordpress organization not known for malicious activity. The only threat to your privacy is the fact that they employ Google's analytics and typekit.com for fonts. That could track you across sites, but otherwise I don't see anything weird.

The link you posted is just filled with reports about Microsoft Edge in 2018 (old version, not the Chrome based one of today) bumping into issues with sites that didn't recognize it or deemed it to be outdated.

**Comment by ghost** [comment]
First of all -  shows   SSL v3 is required Netcraft,
Secondly, Nectraft has partial reservations, 
https://www.fotosik.pl/zdjecie/650e8073103bb1bf
Netcraft is a trusted blocker.

**Comment by working-name** [comment]
@kitaro1 Nothing wrong with being alert on the internet, kudos for putting time into your own security - that's your responsibility. But jumping from not understanding what SSLv3 or Threat Level 1/10 means to making accusations that it is a "well-known malware site" is irresponsible.

Again, I'm not trying to discourage you about being vigilant and safeguarding your privacy/security. On the contrary, I'm urging you to understand what it is that browser add-on is actually saying. You are interpreting the information 100% incorrectly.

SSLv3 is deprecated, it should *not* be active.
1/10 is a low risk.

https://sitereport.netcraft.com/?url=https%3A%2F%2Fbrowsehappy.com

I apologize to @Feodor2 and @RainerB57 for highjacking the issue to educate @kitaro1 - this is my last reply for this purpose. Please mark the back and forth as off-topic.

**Comment by grof017** [comment]
![untitled](https://user-images.githubusercontent.com/81296923/112288416-9996b400-8c8d-11eb-97fc-68c766dd7a21.png)
Try only to check this, nothing else.  It work for me.

**Comment by RainerB57** [comment]
@grof017: Thank you. Your Tip did it for me:
Tools - Preferences - Content - JavaScript Enable WebAssembly checked.

Also thanks to all the others who helped especially to @Feodor2  for his work with this  fantastic browser.

**Comment by JeanPaulLucien** [comment]
App initialized  
Loaded initial state  
Store configured  
This browser does not have lookbehind support for the javascript flavor  
This browser does not have named group support for the javascript flavor

**Comment by JeanPaulLucien** [comment]
Actual issue on 29.0.1x32. I see:
Unfortunately it seems your browser does not meed the criteria to properly render and utilize this website. You need a browser with support for web workers and Web Assembly.
Please upgrade your browser and come back

**Comment by RainerB57** [comment]
It works with the browser.
As written above:
Tools - Preferences - Content - JavaScript Enable WebAssembly checked. 
And then it works. 
That is why I closed the issue and renamed it ending with solved.

![Einstellungen](https://user-images.githubusercontent.com/37036093/116788181-8820a300-aaa8-11eb-8548-7fb9dd135ea8.jpg)
