### ISSUE TITLE
Source code is not provided

### ISSUE THREAD

**Issue by mattatobin** [Feodor2/Mypal#35]
I don't see the `Source Code Form` as defined by the MPL 2.0.

```
Section 1.13
means the form of the work preferred for making modifications.
```

```
Section 3.2 (a)
such Covered Software must also be made available in Source Code Form,
as described in Section 3.1, and You must inform recipients of the
Executable Form how they can obtain a copy of such Source Code
Form by reasonable means in a timely manner, at a charge no more
than the cost of distribution to the recipient;
```

**Comment by dinkc64** [comment]
Source code is provided, look at the download links for the latest release:
https://github.com/Feodor2/Mypal/releases/tag/28.4.0

**Comment by mattatobin** [comment]
That isn't source code. Those are patch files. You are obligated under the MPL Section 3.2 to provide the `Source Code Form` which is defined under Section 1.13 to mean "the form of the work preferred for making modifications.

THUS, you are not following the Mozilla Public License 2.0. I want the source code.

**Comment by dinkc64** [comment]
good enough for me

**Comment by dinkc64** [comment]
so fork it, apply the patches and post a link

**Comment by mattatobin** [comment]
Why would I do that. Also, irrelevant to the requirements of the Mozilla Public License 2.0.

**Comment by dinkc64** [comment]
It's better to be part of the solution instead of being part of the problem.  The problem with the world is nitpickers like you that do nothing to help the situation.

**Comment by dinkc64** [comment]
google how to apply patches

**Comment by mattatobin** [comment]
I dunno what stake you even have in this.. So butt out, thanks!

**Comment by Feodor2** [comment]
Don't worry and be happy i shall begin upload the full code.

**Comment by mattatobin** [comment]
Well that is a different story. I shall wait.

**Comment by dinkc64** [comment]
yay!

**Comment by mattatobin** [comment]
Any progress on this?

**Comment by Feodor2** [comment]
uploading basic full code.... this takes for a while
then shall apply patches, 
suppose all will be done upon this week

**Comment by mattatobin** [comment]
How does it take a while? Shouldn't take you but a few hours at most.

**Comment by Feodor2** [comment]
i hope i shall done mypal source today and centaury tomorrow, if i could spend more time at the project the things where much better...
