### ISSUE TITLE
Google Shopping not rendering properly

### ISSUE THREAD

**Issue by synaeus888** [Feodor2/Mypal#35]
Google Shopping no longer renders properly on current Mypal, Centaury, nor Firefox 52.9.0 ESR. Using any browser on any Linux LiveCD, Google Shopping appears exactly as it always has...no blank spaces, all prices showing, every item clickable, etc.

**Comment by ROBERT-MCDOWELL** [comment]
corpofascism trashing internet development history.

**Comment by ROBERT-MCDOWELL** [comment]
btw it's better to not use google anymore

**Comment by synaeus888** [comment]
I would agree, yet when it comes to comparison pricing (and bargain hunting), Google Shopping has no viable equal...no one even comes close. I guess LilBro forcing me use a Linux LiveCD to access his Google Shopping is a good thing for my privacy, yet I cannot see how it would serve his corporate interest. Perhaps Pichai is hoping such a prod will move XP users on to Win 10? Silly Sundar!

**Comment by ROBERT-MCDOWELL** [comment]
what you see as CEO on screen is always a puppet... google killed all competition on internet since 25 years, getting free $$$ from FED. and people using google because it's free or less expensive dont' realize that the product is them.

**Comment by synaeus888** [comment]
I'm well aware Pichai is just a figurehead, but the real question is whether Sergei Brin and Larry Page are really anything more than just another sort of nominal one? Howard Hughes lost control of his empire long before his death. Will the true puppetmaster ever be unmasked? 



Google is not the only one to have made the enduser the product...I'm not even sure if it was the first to pioneer the idea. M$ was definitely in the running for that credit, but who knows? It has long since become a very popular marketing ploy....free yet not free. Just the sort of complexity to confound the sheeple.

**Comment by ROBERT-MCDOWELL** [comment]
well, follow where big money with big masses control are, and you're done.

**Comment by synaeus888** [comment]
It appears the issue with Mypal, Firefox, and Centaury not rendering 'Google Shopping' properly has disappeared. All three now work as they previously did, so I no longer have to use K-Meleon for price-comparison...while it worked on Google Shopping, it was constantly crashing. While the mystery of who or what was to blame remains, the problem does not, so issue closed.
