### ISSUE TITLE
Google links - requires verification to see if it is a bug.

### ISSUE THREAD

**Issue by bushy555** [Feodor2/Mypal#351]
Hi All,

Just wondering if the following is a bug or not. It may just be me. (Mypal v29.1.0)
Google anything. Open up the first, second , third, fourth, fifth, sixth, seventh ... tenth link in a new tab.
Usually at least one of those links will not go directly to the URL. It does not resolve the URL correctly and will come up as www.google.com/with-lots-of-stuff/then/finally/the-web-site-in-here  ... but does not ever resolve, nor go to the website.

One simple example.  Google "z80 asm"
1st, and 2nd link resolves ok.
Third link down goes here and spins forever. It is a valid website. 
https://www.google.com.au/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjBjrnzodrvAhXuzjgGHRhDCtEQFjARegQIHBAD&url=http%3A%2F%2Fwww.z80.info%2Fz80sdt.htm&usg=AOvVaw19mKmmlGOPt57QeaX0iAh2
Anything to do with certificates?

I come across this issue nearly on a daily basis. Perhaps it is just my useless internet connection and internet provider?
In all of the ~24 years using Netscape and Firefox prior to using MyPal, I have never come across this before.
As I mentioned, just wanted verification if it was me or not.
cheers,

**Comment by Feodor2** [comment]
I stooped use google very long time ago, but i can suggest an addon.
http://myapl.eu3.biz/exts/google_search_link_fix-1.6.10.1.xpi

**Comment by bushy555** [comment]
Copy that; thanks heaps. Thats awesomeo - Tis working like a bought one.
This kinda needs to go into an overall Mypal FAQ for others, along with all the other little tidbits to make Mypal really sing.
Cheers.
