### ISSUE TITLE
Twitter !!!

### ISSUE THREAD

**Issue by Furgon2** [Feodor2/Mypal#356]
Twitter stopped opening, opens in another browser -borealis navigator

**Comment by hue4** [comment]
I am sick.   Nothing but:  "Something went wrong, but don’t fret — let’s give it another shot."

This is like a Twilight Zone.

**Comment by Furgon2** [comment]
in your first message you were advised to do the following: 
 AroKol78 commented Apr 3, 2021

try to modify it - maybe it will help
url bar about:config
find general.useragent.override.twitter.com
set Mozilla/5.0 (Windows NT 6.1; WOW64; rv:68.0) Gecko/20100101 Firefox/68.0
(68 or 78)

you tried to do it?

**Comment by Feodor2** [comment]
No need to make duplicate
