### ISSUE TITLE
怎么了，出什么事情了，为什么找不到哪里下载了？

### ISSUE THREAD

**Issue by oMhuAaN** [Feodor2/Mypal#36]
谁能给我个下载链接？

**Comment by LD-531** [comment]
“沧月”团队认为mypal破坏开源协议，剥夺了作者上游代码访问权。

https://mypal-browser.org

**Comment by jbmt** [comment]
我在palemoon论坛和这里完整观看了整个事件，基本上palemoon的人对外非常苛刻，几乎想把所有基于PaleMoon代码的衍生浏览器赶紧杀绝，这个给xp系统编译的作者，先是被迫改名myPal，现在连代码都不给他了。除了这位作者，PaleMoon还有一个给Mac系统做适配的作者也被迫出走。
PaleMoon还出现过屏蔽衍生浏览器访问他自己的服务器的事情，如果说服务器资源和PaleMoon商标还可以说，这次直接不让用代码做的就太过分了。
PM的话事人叫做Tobin，此人就是开源软件流氓。根本不是为了开源精神。
