### ISSUE TITLE
Problems with certain websites.

### ISSUE THREAD

**Issue by Sniktbub** [Feodor2/Mypal#361]
Hello,

This is my first post here.

First of all - thank you, Feodor2, for creating Mypal and keeping it up-to-date. Amazing job.

--
On-topic --- I've been having some issues with certain websites.

Facebook (including its messenger) - can barely use it; loads too slow, gives me script errors and major lag.

Mewe - "browser not supported" error. They updated their site last week.

ClickMeeting (webinar webcam transmissions site) - can't see/hear transmissions. That site is browser-based, so I'm pretty sure it's fixable (it works on 360 Extreme Browser just fine).

That's it for now. I'm no technician, but I hope something can be done about that in the future. Thank you in advance.

**Comment by Feodor2** [comment]
Welcome.
Facebook - #279
Mewe - #357
ClickMeeting - https://github.com/Feodor2/Mypal/wiki/Vidochat-and-conference-stuff
