### ISSUE TITLE
Does anybody here listen to Pandora?

### ISSUE THREAD

**Issue by hue4** [Feodor2/Mypal#367]
Is it working for you?   And how?

**Comment by Feodor2** [comment]
I do not know what is it, but can try for you what is to do?

**Comment by hue4** [comment]
pandora.com (music).   unstable logon.

**Comment by Feodor2** [comment]
Uh.. Pandora isn't available in this country right now...

**Comment by Atavic** [comment]
Discussion also here: https://github.com/Feodor2/Mypal/issues/362
