### ISSUE TITLE
Legal help.

### ISSUE THREAD

**Issue by Ernst2020** [Feodor2/Mypal#37]
Feodor2, 

If you still would like to continue to “fight” against the idiots of Palemoon, I am willing to fund the first phase of a case against them to a maximum of USD 2.500,- which will be enough to find a copyright lawyer to open a case.

Please get in contact.

Regards,

Ernst

**Comment by ROBERT-MCDOWELL** [comment]
I think it would be much worth to donate this money to feodor2 and refresh the project with a robust browser and code.

**Comment by Ernst2020** [comment]
> I think it would be much worth to donate this money to feodor2 and refresh the project with a robust browser and code.

I don’t know the personal situation of feodor2. He could be rich for what I know. The funds I mentioned (out of my pocket) should be spend to the open source cause. He was bullied by some idiots that could have worked out a solution to the benefit of the community but instead - probably out of jealousy - decided to kill his work. Which is totally out of the realm of what the open source world is about.

I hope he reacts. Here in The Netherlands there is an excellent legal party knowledgeable about copyright law in the open source community. I think they could be of value in this case.

**Comment by Anbima** [comment]
Palemoon is no longer able to properly present new websites. It is therefore nonsensical to further develop here.
The still existing browsers for XP come here to their limits.
Feodor2, do you have an idea on what basis you could continue? Maybe a newer Firefox ESR?

**Comment by Feodor2** [comment]
I do not get a goal for fight to? Do you want spent some moneyt for make a punish upon them, and do you think it will worth?
I think they already have made punish upon themselves for free, let leave them be.

**Comment by andika207** [comment]
@Anbima I think he said the upcoming project might be based on waterfox classic.

**Comment by Anbima** [comment]
@andika207 Where did you get this information?

**Comment by andika207** [comment]
@Anbima I can't remember where it was posted, maybe @Feodor2 has deleted his post..
here is someone mentioning something related to waterfox. https://github.com/Feodor2/Centaury/issues/47
