### ISSUE TITLE
Twitter does not open

### ISSUE THREAD

**Issue by sirrooster** [Feodor2/Mypal#374]
https://twitter.com/ 
does not open.
"Something went wrong, but don’t fret — let’s give it another shot."

No chance. Also not in Safe Mode.

**Comment by Culexamaxa** [comment]
I see this in version 29.1.0 x64 version.  I have seen that on version 28 that it does not give this issue.

I don't view twitter, except occasionally when there is embedded content linking to that service.

**Comment by sirrooster** [comment]
Yes, same for me. In older version there was not such problem.

**Comment by grof017** [comment]
Try to override 
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:68.0) Gecko/20100101 Goanna/4.8 Firefox/68.0 Mypal/29.0.1
It work for me on 29.1.1 x86 version.

**Comment by ByRodrigoSoares** [comment]
**Solution** 
general.useragent.override.twitter.com

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87) Gecko/20100101 Firefox/87

**Comment by Feodor2** [comment]
look #354
