### ISSUE TITLE
Taking screenshots

### ISSUE THREAD

**Issue by ctbrown4** [Feodor2/Mypal#375]
How to take screenshots using the browser?Is there any screenshot addon/extension?

**Comment by bushy555** [comment]
As a work around, try <Ctrl> <PrintScreen>. 
This has always been native to the Windows Environment since around Windows 98 era.

**Comment by bushy555** [comment]
Wow . Dumb HTML!!   
Try again :  [CTRL] and  [PrintScreen] buttons.
I had these in normal greater than / less than signs , and dopey HTML took these away in the above comment.

**Comment by kitaro1** [comment]
Download the zip or the installation program 643 KB MWSnap 3. All about the program here: 
http://www.mirekw.com/winfreeware/mwsnap.html
I will add that it is a safe program and it is flawless even on windows 10 in windows 8 compatibility mode - replace high resolution DPI scaling - application.
MWSnap dumps the marked places in the system on the screen and in everyone's browsers, and also takes screenshots of the entire screen. 
[URL=https://www.fotosik.pl/zdjecie/2c72278ac27641dc][IMG]https://images92.fotosik.pl/497/2c72278ac27641dcgen.png[/IMG][/URL]
