### ISSUE TITLE
Palemoon 29.2.0 released on 27.04.2021

### ISSUE THREAD

**Issue by spectatorBH** [Feodor2/Mypal#376]
https://repo.palemoon.org/MoonchildProductions/Pale-Moon/commits/tag/29.2.0_Release

1) Any ETA for Mypal update? 

2) Will you keep support for legacy Fx extensions with non-PM GUID? PM has [dropped it](https://repo.palemoon.org/MoonchildProductions/Pale-Moon/commit/86e5b48c5f32626e923e069bdcbe3f492e322399) from now on.

**Comment by iyutr** [comment]
This code was changed:
https://repo.palemoon.org/MoonchildProductions/Pale-Moon/commit/86e5b48c5f32626e923e069bdcbe3f492e322399

**Comment by Feodor2** [comment]
1. Next week i plan to do regular update, but mingw will be before this weekend
2. Yes i do keep
