### ISSUE TITLE
Can't SignIn on Github using MyPal 29.0.1x32

### ISSUE THREAD

**Issue by JeanPaulLucien** [Feodor2/Mypal#377]
I don't visit GH a long time. So, GH required to reset a password. On page where GH asks for e-mail address there is a Captcha. MyPal can't load this Captcha.

**Comment by JeanPaulLucien** [comment]
Unable to edit the previous message. So, link to check issue: https://github.com/password_reset

**Comment by RainerB57** [comment]
I get the Captcha, but I had to turn off UBlock Origin or accept a lot. 
![Github](https://user-images.githubusercontent.com/37036093/116789014-07b07100-aaad-11eb-860e-6f495d0e26f3.jpg)
Maybe you also have a AdBlocker active.

**Comment by Feodor2** [comment]
github polyfil addon may be required too, look corresponding issue.

**Comment by bushy555** [comment]
https://github.com/JustOff/github-wc-polyfill/releases
