### ISSUE TITLE
Use alternative to Github

### ISSUE THREAD

**Issue by JeanPaulLucien** [Feodor2/Mypal#378]
MyPal 29.0.1x32 There are problems with some functions of GitHub. For this reason, I would suggest using other, additional funds for information from users. Since already one 100% barrier to participate in the project for users a browser has been detected. 

You may use simplest thing - IRC channel or e-mail (while it has not broken for Windows XP).

**Comment by AroKol78** [comment]
first do the updates mypal (last 29.1.1)
> problems with some functions of GitHub

will add an add-on "github-wc-polyfill" (info https://github.com/Feodor2/Mypal/issues/272)
https://github.com/JustOff/github-wc-polyfill/releases

"_Captcha_" works well in my country

**Comment by IP-CAM** [comment]
Github bright/dark View change does no longer work with MyPal v.29.1.1 either.

**Comment by AroKol78** [comment]
in a future version (29.2) this should be the case
`https://github.com/MoonchildProductions/UXP/commit/e946ca91fb032149131087ce24fbba886c53ee18`
0 = feature disabled 1 = default: light theme preferred 2 = dark theme preferred
browser.display.prefers_color_scheme 1

**Comment by Feodor2** [comment]
>Github bright/dark View 

This is set by the browser, there is an addon is for dark view.
So does the new setting is do something other, i think for now it is useless same as captive portal and do not apply it to mypal.

**Comment by bushy555** [comment]
Can confirm : Polyfill add-on fixes Github scripts for MyPal v29.1.1
Works a treat.
https://github.com/JustOff/github-wc-polyfill/releases

**Comment by IP-CAM** [comment]
One needs to completely remove the Cookies, related with the Github Site, to partially make the latest Github Changes work with latest MyPal Version.

**Comment by L3P3** [comment]
Will stick with GitHub as it works perfectly for me. Please close.
