### ISSUE TITLE
virustotal.com

### ISSUE THREAD

**Issue by JeanPaulLucien** [Feodor2/Mypal#379]
Works strange. I tried Analyze the file that VT does not know. After choice nothing gone.

**Comment by Feodor2** [comment]
Indeed it became strange long ago, i avoid it, look for alternatives.

**Comment by MaxMaximus** [comment]
It is not a browser bug, but site bug. I see same behavior with brand new (never analyzed before) files in FireFox and Chrome too, not just in MyPal. 
Uploading of such files actually works, but with minor glitch - after selecting files just click "file" tab again and there will be a button "confirm upload" to start actual uploading and analyzing of file . This button should be shown instantly after selecting file, but it does not load properly.

**Comment by JeanPaulLucien** [comment]
> 
> 
> It is not a browser bug, but site bug. I see same behavior with brand new (never analyzed before) files in FireFox and Chrome too, not just in MyPal.
> Uploading of such files actually works, but with minor glitch - after selecting files just click "file" tab again and there will be a button "confirm upload" to start actual uploading and analyzing of file . This button should be shown instantly after selecting file, but it does not load properly.

https://wiki.mozilla.org/Evangelism/WebsiteCompatibilityInternational
