### ISSUE TITLE
цвет фона

### ISSUE THREAD

**Issue by iyuter** [Feodor2/Mypal#38]
Это сообщение отменено
==============================
Во-первых, просьба сделать переносную 28.4.0, (как в 28.2.2), чтобы можно было оценить изменения.
Фёдор, две досадных ошибки в твоих сборках, сможешь ли исправить?
1) поиск F3 не работает как должно, прекращается на первом найденном.
2) цвет фона не выставляется: использовать системные цвета.
Приходится кидаться в крайности: переключаться "заменять цвета указанные страницей": всегда/высококонтрастный/никогда, а потом назад, неудобно.

Я так понимаю, что ты зависишь от https://o.rths.cf/palemoon/ , берешь его код и минимально изменяешь, причина этих ошибок в его коде. Но всё-же, можно ли исправить? Благодарю за "Пельмень", хоть он недоделаный, но самый выносливый браузер у меня.

**Comment by Feodor2** [comment]
>Недочеты не исправляются
Не обращались с этим никогда

>просьба сделать переносную 28.4.0, (как в 28.2.2)
Давно сделана, что не так?

>поиск F3 не работает как должно
работает точно таже как и раньше, прекращается на первом найденном так и должно по моему, 
а как должно по твоему?


>цвет фона не выставляется
тоже подробнее: чиего фона не выставляется?

> то ты зависишь от https://o.rths.cf/palemoon/ , берешь его код
Нет, я беру код c https://github.com/MoonchildProductions/UXP - оригинальный код Palemoon

**Comment by iyuter** [comment]
Я ошибся. Ссылку на 28.4.0 я нашел:
http://gallery.ru-board.com/topic.cgi?forum=5&bm=1&topic=49744&start=840#10

тут поиск по F3 в этой сборке срабатывает правильно у меня. 

а с указанием цвета та же неисправность осталась. Наверное это во всех Палмунах.
Палмун 28 соотносится с Фаерфоксом 52, но в любом фаерфоксе, включая 52, цвет выставляется правильно. Так и будет.

Прошу стереть это обсуждение.

**Comment by Feodor2** [comment]
Что не правильно с выставлением цвета?

**Comment by iyuter** [comment]
у меня системный белый цвет выставлен серым, чтобы не напрягать глаза.
Палмун не реагирует на изменение цвета, хоть в надстройке Prefbar (которая во всём работает отлично), хоть в настройках, эта та же функция.
![01](https://user-images.githubusercontent.com/47095941/54882244-a6932980-4e60-11e9-8210-676867a4eeb8.PNG)
![02](https://user-images.githubusercontent.com/47095941/54882245-a6932980-4e60-11e9-9765-c2d14828a60d.PNG)

**Comment by Feodor2** [comment]
Уверен я смогу это исправить, возможно в следующем выпуске.

**Comment by iyuter** [comment]
насчет поиска на странице я разобрался: мешал плагин FindBar Tweak, он не полностью совместимый с Палмуном.

**Comment by Feodor2** [comment]
А я с цветами тоже...
Там ещё ниже есть список выпадающий, где стоит "только с высоким контрастом" нужно выбрать "всегда", так и было задумано по моему, исправлять ничего не нужно.

**Comment by iyuter** [comment]
Вот пример отличия, когда в Палмуне выбрать "всегда".

![03](https://user-images.githubusercontent.com/47095941/55202513-60c3c180-51d0-11e9-900d-02182b3b77c9.PNG)

**Comment by iyuter** [comment]
но как вам угодно, это лишь пожелание, сделать чтобы работало как у фаерфокса.
browser.display.document_color_use
browser.display.use_document_colors

**Comment by Feodor2** [comment]
Не понимаю каких блоков, цвет кнопки? То есть не всех элементов менялся цвет?
 А Высоконтрастный будет работать только если в системе тоже высокий контраст.
у меня так
<a target="_blank" href="https://fastpic.ru"><img src="https://i109.fastpic.ru/big/2019/0329/1c/52636d779363e53dfb0c6209af16321c.png" border="0"></a>

**Comment by iyuter** [comment]
я предлагал сделать поведение как в фаерфоксе, но ладно. Закрываем тему?
