### ISSUE TITLE
Ebay scripting (links within ebay)

### ISSUE THREAD

**Issue by bushy555** [Feodor2/Mypal#385]
Hi everyone,
Might just be my dumb XP install, however, have just noticed that the EBAY invoice link now no longer works natively (v 29.1.1). This is on an XP/Mypal install with no add-ons.

I ran the following, and, now the Invoice link works.
https://github.com/JustOff/github-wc-polyfill/releases

Just wanting to let people know that Polyfill might nearly have to be a required install for more and more websites to work properly. Github, Ebay etc.

(this can be closed)

**Comment by Feodor2** [comment]
Are you sure? The extension mentioned is nothing to do with ebay.
Also discuss it in #337 further please.
