### ISSUE TITLE
releases answers

### ISSUE THREAD

**Issue by AroKol78** [Feodor2/Mypal#386]
> No video format options in preferences, **i think that overload preferences with not important things not needed at all**, do you want all about:config stuff put into preferences?

I fully agree 👍 
another redundant option that doesn't work anyway 
![aazi1](https://user-images.githubusercontent.com/70756447/117153740-8b26d680-adbb-11eb-8f2e-af9c132bf996.PNG)
**HPKP** `security.cert_pinning.hpkp.enabled` i don't see support in the code, but there are some tests
is no longer supported https://developer.mozilla.org/en-US/docs/Web/HTTP/Public_Key_Pinning

> New setting about supposedly set dark theme on the github not applied, i think this is useless thing as the captive portal.

some modern sites use the css key light/dark to display the color model ("Serpent" support this css key)

**Comment by Feodor2** [comment]
This particular security setting was removed as i remember, so did they forget to remove from the preferences. I think i shall remove it then.

Next about modern sites with this css key, for now i do not get the purpose of this, i set light or dark theme by myself regardless of the key. So i played with new setting on the original palemoon - set dark theme and launched several sites - no difference...

**Comment by AroKol78** [comment]
test on "Serpent" **without logging** in - automatically sets the color
`browser.display.prefers_color_scheme` **1**
![blackMy01](https://user-images.githubusercontent.com/70756447/117691196-ef7ed700-b1bb-11eb-8562-d349b622be95.PNG)
`browser.display.prefers_color_scheme` **2**
![blackMy02](https://user-images.githubusercontent.com/70756447/117691224-f4438b00-b1bb-11eb-852f-f510c2c2cd11.PNG)

**Comment by Feodor2** [comment]
Yea github works are there other site? I shall add the thing if find 10 great sites where it works.
For now advanced night mode works everywhere.

**Comment by AroKol78** [comment]
there is no need to search by force - there will be more and more such websites
especially since there isn't much code to add
`https://github.com/MoonchildProductions/UXP/commit/e946ca91fb032149131087ce24fbba886c53ee18`

**Comment by AroKol78** [comment]
Thanks 👍
