### ISSUE TITLE
MyPal deletes ALL passwords after upgrading to 29.2.0

### ISSUE THREAD

**Issue by n4mwd** [Feodor2/Mypal#389]
I recently upgraded to 29.2.0 (32 bit) and ALL my passwords for everything I access is gone.

New passwords are not being saved either and don't appear in the password list or populate when revisiting the site.

Will going back to the previous version restore them or are they gone forever?

**Comment by IP-CAM** [comment]
I had to remove all MyPal-related Cookies, to make everything work as before again.

**Comment by n4mwd** [comment]
I deleted all cookies and history and the passwords are still gone and it wont save new ones even when it asks you if you want to save a password and you click yes.  The password list is totally empty.  I have to go back to the previous version.  I can't have this like that.  May come back to this version when they get this bug fixed.  I simply cant use mypal in this condition.

**Comment by bushy555** [comment]
Updated to 29.2.0 yesterday on to two XP sp3 computers. All passwords were wiped on one, but kept on the other. ( lucky? )
I'm one of those persons that doesn't care if passwords are or are not wiped. Once entered in, passwords are saving ok for me on both computers.  
Maybe a silly intermittent random bug during install?

**Comment by kitaro1** [comment]
Now passwords are key4.db and logins.json. 
Delete key3.db - This is the only solution to Mypal remember and keep log in.

**Comment by n4mwd** [comment]
I tried copying key3.db to key4.db and no luck.  I reinstalled 28.13.0 and all the passwords came back and everything seems fine now.

**Comment by AroKol78** [comment]
as far as I remember, the last one to support the old format was version 28.17.0
I do updates regularly and I didn't have such a problem - version 29.0.1 myself changed the save format
you may have made a huge leap between versions
