### ISSUE TITLE
Mypal error in the morning

### ISSUE THREAD

**Issue by kitaro1** [Feodor2/Mypal#39]
After starting the system and browser, I have the following message:
"Mypal is already running, but is not responding. To open a new window, you must first close the existing Mypal process, or restart your system".
I am removing the message and mypal 28.4.0 normally opens websites.
Yesterday was a bug mypal and today. Which determines?

**Comment by kitaro1** [comment]
The adguard folder - the remainder in the profile after the extension has been removed - did mypal startup errors once the computer was turned on.
Why is removing extensions like adguard or downthemall - leaving the folders of these deleted extensions in the browser profile?

**Comment by Feodor2** [comment]
The first error is about browser in strict portable has been not shutdown, check in the task manager.
About extensions i can guess that browser simply do not monitor them if they make additional folders, remove all that is the particular extension job.

**Comment by kitaro1** [comment]
After cleaning the adguard residue, the problem did not return.
