### ISSUE TITLE
Paypal login blocked

### ISSUE THREAD

**Issue by Anbima** [Feodor2/Mypal#390]
When logging from PayPal comes with the Captcha query of the following errors:
================
Blocked by Content Security Policy
This page has a content security policy that prevents it from being embedded in this way.
Mypal prevented this page from loading in this way because the page has a content security policy that disallows it.
================
How can I fix that

**Comment by Anbima** [comment]
security.csp.enable to false dont fix.

**Comment by Feodor2** [comment]
It is googled.
As you may know i avoid google, and did not encounter sites with capcha long ago, thought the capchta madness have gone - no way.  I shall search for the page of the capchta test and give a link, if it fails there nothing to do, use another browser.

**Comment by Anbima** [comment]
With centaury it works.
The captcha was displayed.

**Comment by Anbima** [comment]
From Console:
Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified  
(unknown)
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src 'nonce-PYjuuRH/RFYPcGs0+AK7T9BPvS30t' https://www.paypal.com https://*.paypal.com https://*.paypalobjects.com https://www.recaptcha.net https://www.gstatic.com 'unsafe-inline'”). Source: onfocusin attribute on DIV element.  
signin
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.

**Comment by Feodor2** [comment]
How to reproduce and what version of the mypal?
I tried with latest mypal and captcha works.

**Comment by Anbima** [comment]
Mypal 29.2.0
On other pages the captcha works.

**Comment by Feodor2** [comment]
So how to reproduce?
You told that with centaury it works, what about previous version of mypal

>Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified

Palemoon developers poked this recently and i applied the patch, can you check with the newest palemoon?

**Comment by Anbima** [comment]
With MyPal 29.1.1 don't work.
I can't use Palemoon.

**Comment by Anbima** [comment]
You can just try it yourself.
Open https://www.paypal.com/de/signin
Name and password you just use something (e.g. abcd)

**Comment by Feodor2** [comment]
I do not ever have paypla account, but when doing signup i have this and its works
![image](https://user-images.githubusercontent.com/19492771/120625184-f910fd00-c450-11eb-9f60-46e289af7cc1.png)

**Comment by Anbima** [comment]
For me, not the Captcha query is displayed, but the error message listed above.

I have mypal 29.2.0 (32 bit).
Do you have a specific setting or another version?
I have tried Security.csp.enable to false, but that does not work.

What can I do?

**Comment by Anbima** [comment]
The problem was general.useragent.override
I have change to default and it works.
