### ISSUE TITLE
is there localised version？

### ISSUE THREAD

**Issue by youxiaojie** [Feodor2/Mypal#392]
is there localised version？

**Comment by AroKol78** [comment]
https://github.com/Feodor2/Mypal/wiki/Languages

**Comment by youxiaojie** [comment]
Great! is the version equals to palemoon? each time it update mypal will update too? and palemoon 29 does not support xp, how about mypal?
Thanks!!

**Comment by youxiaojie** [comment]
and sync function is out of work, where is the fault? does sync function sync addons?
Thanks! great browser open sourced for xp!!

**Comment by Feodor2** [comment]
Yes, the version is equals usually. Though i do not run sync service, very little people need it.
