### ISSUE TITLE
don´t forget the button "upload Image from clipboard"

### ISSUE THREAD

**Issue by jazei-AR** [Feodor2/Mypal#395]
don´t forget the button "upload Image from clipboard" you promised to see that button Feodor, with that button we can upload an image without using paint for save the image and then go to new image  for upload... that button skips that steep and upload from clipboard
Regards, jose

**Comment by Feodor2** [comment]
You may write to the original issue, and not to do duplicate.

**Comment by jazei-AR** [comment]
> 
> 
> You may write to the original issue, and not to do duplicate.

 I apologise, you're right
