### ISSUE TITLE
aliexpress search won't work

### ISSUE THREAD

**Issue by RiNoWaR** [Feodor2/Mypal#396]
hi. some sites work incorrect in mypal, but it's fine in palemoon.
Example: https://aliexpress.ru/popular/leather-punch-puncher.html
any search in aliexpress

**Comment by JeanPaulLucien** [comment]
I checked. What is wrong?

**Comment by RiNoWaR** [comment]
> I checked. What is wrong?

so you opened a link and it's fine?

in mypal it's looks like this(all downloads finished):
![mypal](https://user-images.githubusercontent.com/33617286/122684997-fd436580-d219-11eb-9041-96a9144259cb.png)


in palemoon:
![palemoon](https://user-images.githubusercontent.com/33617286/122684847-0849c600-d219-11eb-899a-82a864fc620a.png)

looks like some scripts or someone else wont work in mypal

**Comment by Feodor2** [comment]
Not confirmed too, certainly the error on you side, try safe mode or clean profile.

**Comment by RiNoWaR** [comment]
thanks, clearing the profile was helpful
