### ISSUE TITLE
XP support for goanna4?

### ISSUE THREAD

**Issue by roytam1** [Feodor2/Mypal#4]
They started forking Firefox55 into their new goanna 4 engine.
https://github.com/MoonchildProductions/moebius

**Comment by Feodor2** [comment]
It is rather early to do anything with that. I shall see when it will be finished. I do not like newer mozilla there inside too many redundant useless code. Palemoon already has taken many of that too.

**Comment by Feodor2** [comment]
Moving toward 52 is good, i shell begin prepare for building new mypal or basil whatever
