### ISSUE TITLE
29.3.0 language packs

### ISSUE THREAD

**Issue by win98se** [Feodor2/Mypal#40]
Sadly I only see language packs for 29.0.1 in https://www.mypal-browser.org/release/langpack/.

I do see language packs for 29.3.0 in https://web.archive.org/web/20210815103613if_/https://github.com/Feodor2/Mypal/releases, but clicking on them return errors, so I can't download them from there.

Do you mind sharing them again if you still have them? Thank you.

**Comment by AroKol78** [comment]
You will find in https://github.com/Feodor2/Mypal/issues/11

**Comment by win98se** [comment]
> You will find in #11

Found 'em, thank you.

Exact link - https://github.com/Feodor2/Mypal/issues/11#issuecomment-919076599
