### ISSUE TITLE
GameBanana.com technical issues

### ISSUE THREAD

**Issue by ShadowMan44** [Feodor2/Mypal#404]
GameBanana is a site for game mods and everything between. There is an issue with the information bar on the right side of the screen (showing you things like the mod creator, contributors and that sort of thing) being completely gone. I've let the GameBanana team know, and so far I don't think they've been able to fix it.

**Comment by Feodor2** [comment]
The site may be corrupt, i have checked https://validator.w3.org/nu/?doc=https%3A%2F%2Fgamebanana.com%2Fmods%2F38891 
many errors, the question why it would work at all.

**Comment by ShadowMan44** [comment]
So this is a hard limit?

**Comment by ShadowMan44** [comment]
Well, looks like this newest update has fixed it. Thanks!
