### ISSUE TITLE
Problems Mypal28.4.1.

### ISSUE THREAD

**Issue by kitaro1** [Feodor2/Mypal#41]
Why does Mypal28.4.1 run for 3 - 4 seconds longer than Mypal28.4.0? In the Mypal28.4.1 settings, the application window is empty, even in the safe mode.
Same profile content.
I only have portable versions with profiles in the location folder

**Comment by Ranippl** [comment]
Why version 28.4.1 does not open magnet links although inserting the command network.protocol-handler.expose.magnet;false (boolean).  Message appears: adresss not understood. In the version 28.4.0 this is working normally.

**Comment by Feodor2** [comment]
I measured launch with AppTimer  - AMD dualcore 2400hz and RAM 2gb
**28.4.0**    **28.4.1**
3.7650         3.8119
3.8296         3.8181
3.7495         3.7810

Yet i did not found anything useful about messed application settings which is impacts magnet links too. I have that error on one machine but not have on another.

**Comment by kitaro1** [comment]
Mypal28.4.0 http://prnt.sc/n8r8jv - Good. Intel, dualcore, 2.5GB RAM - 4s
Mypal28.4.1 http://prnt.sc/n8r8jv - incomplete modules. 5 - 7 s
Such miracles ;)

**Comment by Ranippl** [comment]
I went back to using the previous version 28.4.0 that is working perfectly with magnet links for torrents and will wait for a new release, ok.

**Comment by Vangelis66** [comment]
@Ranippl & @Feodor2: 

About the magnet protocol issue in **MyPal 28.4.1** (on WinXP), perhaps the following is relevant: 

 https://msfn.org/board/topic/177125-my-build-of-new-moon-temp-name-aka-pale-moon-for-xp/?do=findComment&comment=1161440

So you probably _should_ revert UXP commit **[3c02dba](https://github.com/MoonchildProductions/UXP/commit/3c02dba)** , which is https://github.com/Feodor2/Mypal/commit/8bf3f3b in your forked tree !  😉

Best regards
(PS: I'm not using MyPal myself - I am on Vista SP2 with **New Moon 28.5.0a1**... )
