### ISSUE TITLE
Chaturbate freezing the entire browser since last week

### ISSUE THREAD

**Issue by Leifman27** [Feodor2/Mypal#410]
So yeah, chaturbate changed something script wise that when you open it with any mypal (and i suppose palemoon too) it just freezes the browser/starts eating memory and u have to end the process manually.

Figured i'd report it in case there is some 'workaround' for it

**Comment by Leifman27** [comment]
@Feodor2 please ;_____; there has to be some kinda fix

**Comment by Feodor2** [comment]
Again why do not provide the link
So let me guess yes chaturbate.com/
look there https://github.com/Feodor2/Mypal/wiki/Vidochat-and-conference-stuff

**Comment by Leifman27** [comment]
Well... ur other browser (that is a fork of Basilisk?) has the same issue :'(
