### ISSUE TITLE
Direct Fork from newer Mozilla Firefox Code

### ISSUE THREAD

**Issue by PLudkovski** [Feodor2/Mypal#416]
Many if not most websites no longer work (properly) with Palemoon and subsequently with Mypal.
Palemoon development progress is slow or even no longer existent.
Feodor2, you once said that you could possibly fork directly from newer Mozilla Firefox Code.

Is there any chance, you are able to create a Win2003/XP-compatible Browser forked from newer Mozilla Firefox Code?
(v0.78 or newer)

If not, what is the main reason preventing from directly forking from newer Code? (Rust-compiler should be no issue)

**Comment by Feodor2** [comment]
Do not duplicate, write on the already existing topic,
Уes i still did not get rust for xp
