### ISSUE TITLE
Mypal 28.4.1 and magnet links

### ISSUE THREAD

**Issue by Ranippl** [Feodor2/Mypal#42]
Why version 28.4.1 does not open magnet links although inserting the command network.protocol-handler.expose.magnet;false (boolean). Message appears: adresss not understood. In the version 28.4.0 this is working normally.

**Comment by Ranippl** [comment]
I went back to using the previous version 28.4.0 that is working perfectly with magnet links for torrents and will wait for a new release, ok.

**Comment by ByRodrigoSoares** [comment]
thanks for correcting the problem of the magnetic links in version 28.5.0
