### ISSUE TITLE
My icon suggestion

### ISSUE THREAD

**Issue by bongur** [Feodor2/Mypal#425]
Hello. I've been thinking for some time that it would be nice if Mypal had a bit of a nicer icon, as the current photo of the raccoon does not look very nice in my opinion... I've come up with some ideas and I would like to hear people's thoughts on them. 
What I have right now are only sketches, but if people like the design I will go ahead and make an actual vector icon (I am quite skilled with vector software so you can rest assured it'll be well done :) ). 
I'm imagining the icon should resemble the style of the [Firefox icon from 2004 to 2009](https://www.waebo.com/wp-content/uploads/2009/06/firefox-logo-2009.jpg), as I feel that would make the most sense in the context of Windows XP-era design.
![sketch](https://user-images.githubusercontent.com/88982855/129493240-1a729c29-ccf0-4d7f-bab0-8e892231925c.png)
The large one on the left is the final design I've come up with. I've also included some smaller preliminary sketches in case people like them better. I'm also prepared to go in a totally different direction if need be... I can understand if the similarity to the Firefox icon is not desirable, I've just designed it in that way as I feel it's logical to reference the browser's nature as a fork of a fork of Firefox, while also still referencing the current raccoon icon. 
I hope that I'm not imposing myself too much with this proposal, I simply wish to lend my skills and help out the project :) 

Please let me know what you think.

**Comment by Feodor2** [comment]
look #22
