### ISSUE TITLE
The procedure entry point EncodePointer could not be located in the dynamic link library KERNEL32.dll

### ISSUE THREAD

**Issue by aeiouaeiouaeiouaeiouaeiouaeiou** [Feodor2/Mypal#426]
Launching Mypal in a VM with XP RTM/SP1 results in this error:

![image](https://user-images.githubusercontent.com/69355938/129892678-e48c245a-d4d3-44a9-8276-7bdf6d3cd265.png)

`EncodePointer` function has only been added to the system [since XP SP2](https://docs.microsoft.com/en-us/previous-versions/bb432254(v=vs.85)). To fix this you need to [reverse the commit](https://bugzilla.mozilla.org/show_bug.cgi?id=1372849) or just [add to documentation](https://github.com/Feodor2/Mypal/wiki) that browser works only with the latest service pack (because NSS library [uses the `DecodePointer`](https://github.com/Feodor2/Mypal/blob/master/security/nss/lib/util/quickder.c#L405), which is also not supported).

Related issue: #309

**Comment by Feodor2** [comment]
Added note to readme
