### ISSUE TITLE
WebGL Support

### ISSUE THREAD

**Issue by Nikolas-500** [Feodor2/Mypal#427]
Can you add WebGL support that will be a lot of usefull and you will be able to connect to more websites

**Comment by Feodor2** [comment]
webgl support is present, you may be missed something or do not have a vidocard.

**Comment by Nikolas-500** [comment]
i have a videocard but you have a point i think that i don't have drivers installed for it because i using mypal on my old computer which the hard disk died and i using a windows 7 pe so i installed mypal because it can be portable

**Comment by Feodor2** [comment]
sure webgl wont work without drivers
