### ISSUE TITLE
Email link command in File menu not working in Mypal 28.4.1

### ISSUE THREAD

**Issue by BAW30s** [Feodor2/Mypal#45]
Hi, after installing Mypal 28.4.1 yesterday, I found that the useful "Email link" command in the File menu no longer worked.
My default email program, this being XP, is Outlook Express.
I have tried re-installing Mypal and confirming OE as default in "Set Access and defaults" in Add or Remove programs in the Control Panel.
The command still works in Pale Moon 27.
Is there any of re-setting the command, or should I try going back to 28.4.0, or waiting for 28.4.2?
Thanks!

**Comment by Feodor2** [comment]
Watch that (**issue**)[https://github.com/Feodor2/Mypal/issues/41]. If you need the email feature back to use 28.4.0

**Comment by BAW30s** [comment]
Thank you, Feodor2, for your quick reply and all the much appreciated work on Mypal, a very useful program.
I have gone back to 28.4.0 and the email feature works again. I'll look out for future developments.
