### ISSUE TITLE
Angle / WebGL

### ISSUE THREAD

**Issue by Anbima** [Feodor2/Mypal#45]
On MyPal 29.3.0 WebGL-1 and WebGL-2 are present.
But https://browserleaks.com/webgl say "ANGLE=False".

How can I activate that?

**Comment by syncguy** [comment]
Посмотрите ошибки в разделе Graphics about:support

FireFox (MyPal) очень щепетилен к версиям драйверов на видео-карту, но можно поиграться webgl параметрами в about:config, самые важные вот эти:
webgl.force-enabled
webgl.msaa-force

Если не поможет, то вы всегда можете забить на аппаратный и перейти на софтовый рендер. У меня были проблемы на допотопных XP и видео-картах старше 15 лет и в виртуальных средах с подключением по RDP, решились все проблемы именно переходом на https://www.mesa3d.org/

**Comment by NEO-SPECTRUMAN** [comment]
а за что отвечает webgl.webgl2-compat-mode ???
