### ISSUE TITLE
has the development of the new mypal begun

### ISSUE THREAD

**Issue by sastofficial** [Feodor2/Mypal#49]
theres no source code here and the archive is the old version.

**Comment by JeanPaulLucien** [comment]
@sastofficial look in my profile.

**Comment by sastofficial** [comment]
> @sastofficial look in my profile.

I meant the new version made with rust that is mention in the readme

**Comment by Anbima** [comment]
@Feodor2
Do you work on a new version, or do we have to say goodbye to Windows XP?
If so, when will it give a first release?

**Comment by E-System33** [comment]
> @Feodor2 Do you work on a new version, or do we have to say goodbye to Windows XP? If so, when will it give a first release?

![image](https://user-images.githubusercontent.com/89921808/149669200-7e007847-08c0-4131-bcc6-8729cfacc3b4.png)

**Comment by Anbima** [comment]
I have read this, but Feodor2 has not written anything since then. Maybe it does not work, just as he thought. Therefore my demand.

**Comment by Feodor2** [comment]
I going begin actual development in upon next week.

Primary goals
1. Make it just work on XP
2. Disble and remove telemetry and such other shit (tor patch)
3. Resotore directx9 support
4. Make my portable scheme

Secondary goals (i think i wont make it, for sure without help)
1. XUL extensions
2. NPAP plugins

**Comment by ROBERT-MCDOWELL** [comment]
@Feodor2 
Great!!! could you explain a bit more about the issue to solve for XUL and NPAPI?

**Comment by Feodor2** [comment]
@ROBERT-MCDOWELL
Those really not  necessary for me, so not going spend time which is short

**Comment by ROBERT-MCDOWELL** [comment]
@Feodor2 
ok, but I just wanted to know what are the issues to help me and maybe other to investigate on it.

**Comment by Anbima** [comment]
@Feodor2
XUL Extensions and NPAP plugins are not necessary.
The German language pack would be important :-)
I am available for Alpha and Beta tests.

**Comment by ROBERT-MCDOWELL** [comment]
@Anbima 
NPAPI can be useful to run Flash legacy applications.... :)))

**Comment by Anbima** [comment]
@ROBERT-MCDOWELL
Flash is almost no longer used. It is important first that everything else works. If the basic browser Flash has no longer, then I can understand that it is very expensive to retrofit this.

**Comment by NEO-SPECTRUMAN** [comment]
>Flash is almost no longer used.
lol wut?
many old sites still use Flash
not everyone will change own site for each ZOG's M$'s whim

**Comment by NEO-SPECTRUMAN** [comment]
>Disble and remove telemetry and such other shit (tor patch)

и не забыть обязательно выпилить новомодную блокировку http картинок с https сайтов :)

**Comment by Feodor2** [comment]
@ROBERT-MCDOWELL
> what are the issues to help me and maybe other to investigate on it

No issue if you can undesrtand programming and have spare time for it, or fundrise money and hire a programmer.

@NEO-SPECTRUMAN
> блокировку http картинок на https сайтах

вроде на стороне сервера это блокируется, а есть примеры я проверю

**Comment by NEO-SPECTRUMAN** [comment]
так я с mypal-а прекрасно вижу
а вот пользователи вин15 и фф100500 уже жалуютсо

**Comment by NEO-SPECTRUMAN** [comment]
вот тут в первом посте есть такая картинка
https://zx-pk.ru/threads/34060-novaya-versiya-zvukovoj-kartochki-turbo-sound-fm-pro.html
запостивший ее сам не видит :)

**Comment by NEO-SPECTRUMAN** [comment]
на другом форуме вообще заявили
что будут удалять ссылки на http
тк видителе ZOG сказало что не безопасно для ваших банковских счетов

**Comment by E-System33** [comment]
Is it possible to make an interface adapted to the Windows XP UI?😅

Or the Firefox qm engine is not compatible?🙂

**Comment by E-System33** [comment]
> > Je vais commencer le développement réel la semaine prochaine.
> > Objectifs principaux
> > ```
> > 1. Faites-le fonctionner sur XP
> > 
> > 2. Désactivez et supprimez la télémétrie et toute autre merde (tor patch)
> > 
> > 3. Resotore directx9 support
> > 
> > 4. Faire mon schéma portable
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Objectifs secondaires (je pense que je n'y arriverai pas, c'est sûr sans aide)
> > ```
> > 1. Extensions XUL
> > 
> > 2. Plugins NPAP
> > ```
> 
> Is it possible to make an interface adapted to the Windows XP UI?😅
> 
> Or the Firefox qm engine is not compatible?🙂

Sorry for the translation of the quote. bruh

**Comment by Anbima** [comment]
Now let Feodor2 first bring the new version to run and if it's going on, we can talk about extensions.

**Comment by Feodor2** [comment]
I have launched my first quantum under xp, it works great and much faster than 360

@NEO-SPECTRUMAN
> вот тут в первом посте есть такая картинка

работает лиса 91

**Comment by Anbima** [comment]
@Feodor2
that's excellent! 
Where can we download it?

**Comment by Feodor2** [comment]
I shall make new page here on github

**Comment by Anbima** [comment]
Perfect.
Do you have the German language?

**Comment by temp10min** [comment]
> I shall make new page here on github

не забудьте билд за SSE проць, пожалуйста :)

---

don't forget to make a build for SSE-only processors too, please

**Comment by roytam1** [comment]
> I have launched my first quantum under xp, it works great and much faster than 360

great! I wonder if these efforts can be ported into 56 and 60esr.

**Comment by gdl-888** [comment]
> I have launched my first quantum under xp, it works great and much faster than 360


can you post a screenshot please?

**Comment by ghost** [comment]
I look forward to the link so I can download and test it on my XP.
The new foxes are not very good (Proton). A 68-78 is better.

**Comment by SampeiNihira** [comment]
@Feodor2

Hi,
Is the new browser written entirely in Rust or in a mixed language?

**Comment by StevenKal** [comment]
Very cool to see guys trying to make work Firefox well under XP, I run the ESR on XP since no higher version available, but I also has MyPal as replacement for websites with problems, because it handle a bit more than ESR (videos playing, some non-blank pages, etc.). I can just not add modules on it (does not work), but I wait for improved version of MyPal in order to definitively stick with it & drop FireFox.
Right now the best for XP is 360 Chrome, but I have problem with images not displaying on some websites, & I do not like much Chrome neither trust much this browser. So I hope you will release a good MyPal update fully workable under XP, will be magic! Keep up good work & thanks again for your effort at helping old XP users!

**Comment by ghost** [comment]
> I do not like much Chrome neither trust much this browser

You can add [these domains](https://pastebin.com/raw/durEfBaL) to the hosts file. This blocks almost all third-party requests from the 360EE browser.
[Read more](https://github.com/artenaki/Mypal).

**Comment by andika207** [comment]
>  I have launched my first quantum under xp, it works great and much faster than 360 

which one ? the 360 browser developed buy a man from USA is incredibily fast in comparison to either ''elchupacabra'' fork or the original 360EE
as you know bookface is a heavy load website but I am rather impressed how smooth it runs with that 360 browser. @NEO-SPECTRUMAN

**Comment by andika207** [comment]
> You can add [these domains](https://pastebin.com/raw/durEfBaL) to the hosts file. 

@ghost why 127.0.0.2  and not 127.0.0.1 ?

**Comment by gdl-blue** [comment]
I also don't use 127.0.0.1, There may be some reasons like you are hosting a web server on 127.0.0.1:80

**Comment by andika207** [comment]
@gdl-888 is that your personal list ? there are some domains I have never came across.
I had already shared my personal hosts list for this browser https://github.com/Feodor2/Mypal/issues/32#issuecomment-955702050

**Comment by andika207** [comment]
@gdl-888 I would like to know the reason why can't I block some domains related to software utilities installed on my PC
I use either 0.0.0.0. or 127.0.0.1 or the full domain address
apart from **Wireshark 1.12.13** I also use **CrowdInspect 1.7.0**
https://www.crowdstrike.com/resources/community-tools/crowdinspect-tool/
