### ISSUE TITLE
Download is broken

### ISSUE THREAD

**Issue by thehandyman1957** [Feodor2/Mypal#5]
I have tried to download your latest 32 bit version for a friend and it gives me a failed download.

It seems like it's downloading it to my computer but does not say where.
Then when it's finished it will ask me where to put it.  I tried to put it on my desktop and 
Pale Moon says it failed to download.  It also gave me the same problem with my 
Internet Download Accelerator.

**Comment by Feodor2** [comment]
I checked it now, no error. So this is on your side, and yes mega.nz site is intricate, but free and reliable, download software most likely failing with it. Do not use it with that site.

**Comment by Feodor2** [comment]
Now its new host for binary provided by Moonchild

**Comment by thehandyman1957** [comment]
I followed that thread and thank you for the great work.
