### ISSUE TITLE
Warn if several tabs are closed

### ISSUE THREAD

**Issue by Anbima** [Feodor2/Mypal#50]
Hello,

when "Warn if several tabs are closed" is active and one Tab is "Pin the tab" and another tab is a normal tag then Mypal is closed without the warn coming.
BR
Andreas

**Comment by Feodor2** [comment]
Pined tab does not count, and with one tab there is no warn by default, but you can set in the about:config
**browser.showQuitWarning;true**

**Comment by Anbima** [comment]
Thanks
