### ISSUE TITLE
give support to Feodor2 in this dangerous time

### ISSUE THREAD

**Issue by yongsu101** [Feodor2/Mypal#55]
hey @feodor2 long time no see
i wanted to say that with situation in ukraine i hope you and your country will be ok
it would suck if you have to fight in stupid war caused by some sob
i don't care about politics but war is wrong, period
that sob putin has gone too far to say ukraine is all wrong and shouldn't exist
bad version of another mini stalin who said your browser is all wrong and shouldn't exist
screw all these little men who cause so much problems for everyone
and bs with a straight face and twist justice to suit their stupid agenda
we all look forward to your new browser but there are more important things
stay safe brother and  god bless you and your family

**Comment by ROBERT-MCDOWELL** [comment]
well, I advice you to get out from your country's corrupted mainstream media and investigate yourself directly to what both sides are saying without filter... you will see easily that you have been deceit since you are born....

**Comment by yongsu101** [comment]
@ROBERT-MCDOWELL you don't know my country so why start this talk?
i said i don't care about politics if you didn't see
but you don't say the other country is worth nothing and threaten war
doesn't matter how right you think you are
my point is it sucks if there's a war and i hope @Feodor2 can stay safe
if you wish different then honestly gtfo
man needs to be alive to work on the browser you know

**Comment by NEO-SPECTRUMAN** [comment]
> to say ukraine is all wrong and shouldn't exist

+1


>you don't know my country so why start this talk?

but we can see that you were washed brains...

**Comment by ROBERT-MCDOWELL** [comment]
"you don't know my country so why start this talk?"
because in a world of freedom anyone has the right to talk of any subject.
calm down your ego and try at least to understand how this rigged system is working rather than to accuse my little person...
I don't talk about your country (I don't care which), I talk about mafias infilitrated in each government who are most of them mentally sick (psychopathy). But I even don't blame of those sickos, I blame to the masses who believe in their total illusion crap and causing damage on freedom and peace.....

**Comment by yongsu101** [comment]
i admit my fault for waking up these great intellectuals
so great that they totally transcend the point of this thread
you care so much about being right that you can't even say a little thing like
yes @Feodor2 stay safe
then after that give all your superior understanding?
@NEO-SPECTRUMAN
washed or not at least i have it
so i don't start talking bs about other posters
in a thread meant to support @Feodor2
if you're putin's or stalin's son then my bad mentioning your daddy here
otherwise get over it
@ROBERT-MCDOWELL you talk about my ego after you say "your country"
if you mean something in general then don't exclude yourself like you're so special
congratulations that you're free of all illusion unlike everyone else
frankly i don't give a damn about that ass putin
he can talk bs forever if he doesn't start killing people for his fantasy
of course media and elites everywhere bs all the time
beats me why you feel you need to lecture me about that
but putin made recording himself where he personally talks a lot of nonsense to justify
really not a problem with my understanding like you try to make it
i sure as hell will not argue about politics here any more
sorry @Feodor2 that it turned into this
all i really wanted was to wish you well

**Comment by NEO-SPECTRUMAN** [comment]
> otherwise get over it

You doesn't know anything about ex-ussr
expect that shown on bourgeois idiot box...

**Comment by yongsu101** [comment]
@NEO-SPECTRUMAN
today it sure looks like i know enough
well i guess you got your wish now
better mark your ass with a red flag
otherwise your great idol might accidentally shoot a missile there
but seriously even if you don't care about your country
and the lives of your countrymen
i think everyone deserves to live and live in peace
i'm willing to make an exception to the likes of madman putin
but you and @Feodor2 and everyone else in ukraine
i really hope you can stay safe and come through this mess

**Comment by E-System33** [comment]
> @NEO-SPECTRUMAN aujourd'hui, il semble que j'en sache assez bien, je suppose que vous avez obtenu votre souhait maintenant mieux marquer votre cul avec un drapeau rouge sinon votre grande idole pourrait accidentellement tirer un missile là-bas mais sérieusement même si vous ne vous souciez pas de votre pays et la vie de vos compatriotes je pense que tout le monde mérite de vivre et de vivre en paix je suis prêt à faire une exception aux goûts du fou putin mais vous et @ Feodor2 et tout le monde en ukraine j'espère vraiment que vous pouvez rester en sécurité et passer ce gâchis

Apparently it just started

**Comment by ROBERT-MCDOWELL** [comment]
I think github is not done to talk about politics. so if you'd like to continue this topic please use the right forums.
btw, here what's happening in donetsk now
https://odysee.com/@Velyaminov:a/Donetsk-rejoices-at-Russia's-decision:b

**Comment by NEO-SPECTRUMAN** [comment]
> well i guess you got your wish now

We waited for him 8 years ago
but he betrayed us at that moment

**Comment by ROBERT-MCDOWELL** [comment]
woowww, indeed war started 
https://t.me/TheHardTruthToSwollow/10597

**Comment by yongsu101** [comment]
damn i hate to go back on my word but this is too ridiculous

> im from fcknukraine
> and ukraine ocupied our teritory

nice logic, not ukrainian but colorado man
could have told that from the beginning so i wouldn't waste my time
suitcase, railway station, russia
do you know this concept?
russia is a vast country and has lots of room you know
you can have everything you love without anyone dying

> at same time their language is much primitive
> and not suitable for industry and science at all

lol yeah but ru-board is in russian, no?
if it wasn't cyrillic you could understand more than 50% posts in browser topics
without translation because all terminology is straight from english
don't flatter yourselves about primitive
you have a personal bourgeois idiot box don't you?
because for sure you aren't using old soviet rubin tv set
then you drive your bourgeois german car because russian cars suck
even your marxist ideas were created by bourgeois from germany
but you proudly yell about we can repeat
i can see you can repeat german invasion of ukraine
and you'll also end up the same way

i detest that jerk matt tobin but maybe i was too harsh on him
because looks like we have even more paranoid and deluded on xp side
i though he was lying about death threats from eastern europe
but there's some very bloodthirsty people here for sure

but i still repeat what i said before
i don't want anyone to die from this so stay safe everyone over there

**Comment by NEO-SPECTRUMAN** [comment]
> suitcase, railway station, russia
> do you know this concept?

where the ass in the warm
there is the Motherland now?

**Comment by Feodor2** [comment]
Аh good bye, witness real world war begins, best wishes for all and be safe.

**Comment by ROBERT-MCDOWELL** [comment]
https://crowdbunker.com/v/ipDPuQh5Gg
