### ISSUE TITLE
Multiprocess Windows

### ISSUE THREAD

**Issue by Anbima** [Feodor2/Mypal#57]
How can I enable "Multiprocess Windows"?

**Comment by Feodor2** [comment]
In mypal or palemoon is no any "Multiprocess Windows", what if you mean this like in the new firefox, then no and not desired on at all.

**Comment by Anbima** [comment]
But in about:support it will displayed.

**Comment by Feodor2** [comment]
Uh, this is a leftover, i shall remove it for not to provoke confusion.

**Comment by Feodor2** [comment]
Done
