### ISSUE TITLE
Feodor2 выкладуй ужо шонибудь пока не пришла повестка!

### ISSUE THREAD

**Issue by NEO-SPECTRUMAN** [Feodor2/Mypal#57]
собственно сабж... 
(хотел прицепить смайлик но передумал)

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
Выкладывать лучше на notabug.org, так как GitHub может в любой момент удалить все аккаунты (как это сделали с пользователями из Ирана).

**Comment by NEO-SPECTRUMAN** [comment]
а еще лучшо передать ссорцы roytam1-у

**Comment by Feodor2** [comment]
В ближайшее время не выйдет, да и смсысл, у меня подозрения что скоро нам не нужны будут браузеры вообще, будет неначем и нечего , могу только обещать что если после войны я выживу и будет ещё существовать интернет то выложу

**Comment by NEO-SPECTRUMAN** [comment]
> если после войны

M$ дистанционно взорвет все компы с вин15
и останутсо только компы с православной ХРю :rofl:

**Comment by ROBERT-MCDOWELL** [comment]
Я пропоную від душі детоксикувати тим, кому промивали мізки, слухаючи цього справжнього незалежного журналіста, який дуже добре пояснює, що стоїть за завісою... Божого благословення всіх вас
benjaminfulford.net

**Comment by NEO-SPECTRUMAN** [comment]
что примечательно
ХРю фобы уже выпиливают ХРю из virtualbox-а
:rofl:

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
Напоминаю что бэкапы находятся здесь:
https://gitee.com/aeiouaeiouaeiouaeiouaeiouaeiou/Mypal
https://notabug.org/aeiouaeiouaeiouaeiouaeiouaeiou/Mypal

**Comment by Feodor2** [comment]
Выложил - смотри первую страницу.

**Comment by NEO-SPECTRUMAN** [comment]
не гуглодрайв и тут пока не побежден :)
![2022-04-06_173332](https://user-images.githubusercontent.com/88002487/161996759-a7e1a018-4c17-4fbf-ade3-9bccff9e66ba.png)

**Comment by NEO-SPECTRUMAN** [comment]
так жо новый mypal дико плодитсо
![2022-04-06_174921](https://user-images.githubusercontent.com/88002487/161999800-b8f9e47f-d73a-4fba-b968-a4d0299aa82f.png)
(один из них старый mypal)

интересно в 68 фаирфоксе этто еще отключаетсо

**Comment by NEO-SPECTRUMAN** [comment]
а новомодные дополненя тут будут интересно работать?

**Comment by NEO-SPECTRUMAN** [comment]
ЛОЛ
бразер можот находитсо в состоянии суперпозиции
он вроде бы упал
![2022-04-06_193140](https://user-images.githubusercontent.com/88002487/162021194-d87be0ef-09ba-44a0-acd0-7830799a777a.png)
и в тоже время не упал :rofl:
![2022-04-06_193157](https://user-images.githubusercontent.com/88002487/162021239-4718d624-8cb2-4e0f-a7a0-6faee9e61cdb.png)

**Comment by NEO-SPECTRUMAN** [comment]
...
вот бы еще кто нить новый QT подправил...
