### ISSUE TITLE
Off topic InterLink

### ISSUE THREAD

**Issue by nord899** [Feodor2/Mypal#59]
Would really love it if you did for Interlink what you did for PaleMoon. As Thunderbird drifts away from XUL, XP users would love to be able to use InterLink just like Windows 7 users.

Thanks for listening.

**Comment by Feodor2** [comment]
In the theory it is easy to build it, as it only application on the same uxp platform. However it is not open source and not free, people gathered money to pay Tobin, who is the developer of the InterLink. So you may try convince Tobin with good sum of dollars.
