### ISSUE TITLE
Conflicting duplicate entries in about:config

### ISSUE THREAD

**Issue by letmeindude** [Feodor2/Mypal#6]
Go to about:config, search for "general.useragent.compatMode.firefox" and you will see 2 conflicting entries:
general.useragent.compatMode.firefox	True
general.useragent.compatmode.firefox	False

Same when searching for "general.useragent.compatMode.gecko":
general.useragent.compatMode.gecko	True
general.useragent.compatmode.gecko	False

Is this a problem, or we can ignore it?
https://postimg.cc/image/3tqvcgysr/
https://postimg.cc/image/fvm96mfqz/

**Comment by Feodor2** [comment]
Thanks for the report. This is a bug indeed, i consider this not so critical, i shall fix it on the next release, before that you can ignore i think.

**Comment by Feodor2** [comment]
fixed
