### ISSUE TITLE
Slow download in Pale Moon 27.6.2 - Why?

### ISSUE THREAD

**Issue by kitaro1** [Feodor2/Mypal#6]
Speed Test Firefox 51.0: http://prntscr.com/hi17au
http://www.wklejto.pl/314071
Speed Test Pale Moon 27.6.2 (Fedor2) http://prntscr.com/hi17tg
http://www.wklejto.pl/314070
Firefox and Pale Moon equally set - No proxy.
Firefox and Pale Moon equally extend.
Why?
Now it is difficult for Pale Moon 27.6.2
Pale Moon is already running, but is not responding. To open a new window, you must first close the existing Pale Moon process, or restart your system.

**Comment by Feodor2** [comment]
For speed i try find some one with that speed and ask check. There where no major changes since version 27.6 as well.

For **Pale Moon is already running** specify the type of the installation you had choosen. If portable wether is **default browser disabled** feature has been enabled.

**Comment by kitaro1** [comment]
The newmoon 27.6.1 installation version http://prntscr.com/hj42pc
Palemoon 27.7 portable http://prntscr.com/hj44y9
Basilisk nightly FF55 portable http://prntscr.com/hj45me

Reason for free upload - you need to add newmoon, palemoon and basilisk to XP firewall.
Basilisk browser is the fastest.
It's a good job with internet browsers.
Thank you.
