### ISSUE TITLE
MyPal are dead? The last version are 29.3.0. There have been no updates for several months

### ISSUE THREAD

**Issue by FuerteFalox** [Feodor2/Mypal#62]
There was talk in February of a new version of mypal but there is no trace. 
The current version released on the new web is 29.3.0. 
Do you know anything about it? Many sites are starting to fail and need to be upgraded

**Comment by AroKol78** [comment]
as far as I know **Feodor2** is from 🇺🇦 and is probably in the war right now.
hopefully he will come back safe and healthy.

**Comment by NEO-SPECTRUMAN** [comment]
yes mypal is dead...

**Comment by FuerteFalox** [comment]
alternative browser work on windows xp with last update?

**Comment by AroKol78** [comment]
`https://rtfreesoft.blogspot.com/search/label/browser`
a forum about these browsers `https://msfn.org/board/topic/182647-my-browser-builds-part-3/`

**Comment by NEO-SPECTRUMAN** [comment]
Yes roytam's browsers is the last bastion of web browsing on XP...

**Comment by Feodor2** [comment]
Try new 68 version.
