### ISSUE TITLE
Language Pack don't Work in version 28.5.2 

### ISSUE THREAD

**Issue by FuerteFalox** [Feodor2/Mypal#65]
Hello, the Italian language worked until version 28.5.1. After installing version 28.5.2 and having installed again the pack again restarted Mypal, the interface remains in English. I saw that the last language update is June 2nd 2019 while this version came out later so, i assume there is an incompatibility or am I wrong?

**Comment by Feodor2** [comment]
Yes, now own language packs are using, Italian language i shall add upon next release.
Pleas read and watch #40

**Comment by Feodor2** [comment]
done
