### ISSUE TITLE
master password

### ISSUE THREAD

**Issue by Anbima** [Feodor2/Mypal#71]
When I have acitvated "Use a master paddword" and then calls the stored passwords, it takes a minute for the passwords to be displayed. If I deactivate the master password, they will be displayed immediately.

I changed the master password as described in palemoon, but the problem still exists.

**Comment by Feodor2** [comment]
Palemoon developers adjusted encryptions of master passwords for better security, and it turned to make hard it for regular machine. Do you always use master password?

May want to read https://forum.palemoon.org/viewtopic.php?f=3&t=22434
They told its fixed now, so when i will be making next release i take the fix too.

**Comment by Anbima** [comment]
Yes, I use always master password.
It is OK, when you fix with the next release.
