### ISSUE TITLE
Stuck in CloudFlare "please allow up to 5 seconds..."

### ISSUE THREAD

**Issue by gdl-blue** [Feodor2/Mypal#72]
When I visit pages that use CloudFlare, I stuck in "please allow up to 5 seconds... / DDoS protection by cloudflare". This does not happen in New Moon by roytam1. Any fix for it?

**Comment by NEO-SPECTRUMAN** [comment]
the same thing on mypal 29.3.0
several reload the page usualy redirecting on desired page

**Comment by IP-CAM** [comment]
The DOWNLOAD Function does not work, all Downloads add ZERO BIT Zips, again and again, and in the Browser Admin Section,, Downloads cannot be deleted/removed either. Every time, the Browser starts, those empty ZIP's are downloaded again.

**Comment by gdl-blue** [comment]
In New Moon it reloads about 0-2 times and just redirects to the desired page, but in Mypal it just reloads infinitely.

**Comment by foxtrot-99** [comment]
#Feodor2/Mypal/72 does not seem to work in Mypal 28/29

**Comment by foxtrot-99** [comment]
Feodor2/Mypal/#72 does not seem to work in Mypal 28/29

**Comment by foxtrot-99** [comment]
Feodor2/Mypal68/#64 does not seem to work in Mypal 28/29

**Comment by gdl-blue** [comment]
Feodor2/Mypal68#64 ( https://www.ghacks.net/2022/05/05/fix-pale-moon-browser-not-passing-cloudflares-checking-your-browser-verification/ ) 

does not seem to work in Mypal 28/29

**Comment by NEO-SPECTRUMAN** [comment]
it doesn't works at all

also mypal 29 more...
to keep using "old" firefox you must migrate to roytam's browsers
http://rtfreesoft.blogspot.com/

**Comment by NEO-SPECTRUMAN** [comment]
да
CF планку хоть наверно и понизило
но с поддельным useragent-ом "пройти" не получается
только с дефолтным

**Comment by NEO-SPECTRUMAN** [comment]
теперь проходит и с поддельным
теперь можно притворятсо 100-м фаирфоксомм по дефолту

**Comment by gdl-blue** [comment]
**general.useragent.override;Mozilla/5.0 (Windows NT 6.1l rv:100.0) Firefox/100.0 Gecko/20170101** worked for me
- Mypal 28.14.2 (32-bit) -Windows XP ia32
- Mypal 29.3.0 (64-bit) - Windows 10 x64
