### ISSUE TITLE
Language Pack Continue Not Work on 28.6

### ISSUE THREAD

**Issue by FuerteFalox** [Feodor2/Mypal#72]
Despite the promises of resolution in the new version, have installed the 28.6 from 28.5.2 and reinstalled the Italian language package and the " Pale Moon Locale Switcher". I see the switch from "en-US" to "it" in about: config, next asks for a reboot of Mypal but on reboot the language remains in English!. 
Return to about: config and i see that the value is automatically returned to en-US.

Language Pack don't workalso in this version!. I remember that everything worked perfectly until before the release 28.5.2.
I tried to put the Spanish language but nothing changes, everything remains in English

**Comment by Anbima** [comment]
Uninstall "Pale Moon Locale Switcher" -> is not required
Restart Mypal
Open: about:config
Search: general.useragent.locale (if not available, create)
content: it-IT
Restart Mypal

**Comment by FuerteFalox** [comment]
I had already done this procedure and, I repeated it even now but when I restart Mypal the value (although I set it with it-IT, it returns again with en-US).... Other Solution??

**Comment by Anbima** [comment]
Can you install german language package an test with "de-DE"?

**Comment by FuerteFalox** [comment]
I also tried the German language. It seems that the binary value is "not saved", when I restart the mypal browser, everything returns as before with the "en-US" setting, despite the language is correctly installed

**Comment by wyxchari** [comment]
Spanish language work ok for me in 28.6.0.

**Comment by Feodor2** [comment]
**FuerteFalox**  did you actually took mypal language pack, palemoon packs will never match then, do not try them.
![изображение](https://user-images.githubusercontent.com/19492771/61212008-acf82a80-a709-11e9-9b40-dcffa233d94f.png)
By the way please check **about:rights** strings to be right.

**Comment by FuerteFalox** [comment]
I had downloaded the package of languages ​​from the palemoon website also because, i don't find them on mypal site but if you tell me that they are no longer compatible, then you explain why they don't work.

You have the link for the italian package of github work with mypal?

**Comment by Anbima** [comment]
https://github.com/Feodor2/Mypal/releases

**Comment by Anbima** [comment]
> Assets

**Comment by FuerteFalox** [comment]
Now work!! Thank You
As from an old habit, I had installed the palemoon language package but now, after installing the correct ones, the language works perfectly! Thanks 1000. 
Topic closed
