### ISSUE TITLE
Download Function does not work

### ISSUE THREAD

**Issue by IP-CAM** [Feodor2/Mypal#73]
The DOWNLOAD Function in latest Version MyPal does not work, all Downloads add ZERO BIT Zips, again and again, and in the Browser Admin Section,, Downloads cannot be deleted/removed either. Every time, the Browser starts, those empty ZIP's are downloaded again.

**Comment by NEO-SPECTRUMAN** [comment]
@Feodor2 а как палёмуновцы детектят браузер на своих сайтеках с плагинами?

есть способ обойти ихний "only on palemoon"?

**Comment by E-System33** [comment]
Try with the new Mypal to see if the problem is solved

https://github.com/Feodor2/Mypal68/releases/tag/68.12.2b

**Comment by IP-CAM** [comment]
By Use of the latest Release, Downloads work well now.
