### ISSUE TITLE
The page isn’t redirecting properly / xp sp3

### ISSUE THREAD

**Issue by rereser** [Feodor2/Mypal#77]
redirect and login errors.
see latest post.
SOLVED.

**Comment by Feodor2** [comment]
I suspect the site treats mypal as old firefox, try set compatibility mode to native.

**Comment by rereser** [comment]
thanks for the quick reply.
tested , same problem.

**Comment by Feodor2** [comment]
Well, next look and compare entries in the error console.

**Comment by rereser** [comment]
found the error console but you lost me there.
never used that , so what info do you need from there?
error , warnings ?
