### ISSUE TITLE
Site specific error / xp3

### ISSUE THREAD

**Issue by rereser** [Feodor2/Mypal#78]
https://www.viabovag.nl/
popular used car sale site.
search selections can be made but are invisible.
only works with chrome 49 for xp.

mypal 28.6.0 win32 error console
Warning: Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
Warning: Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Warning: Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Warning: Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified

palemoon 28.7.0a1 win32 error xonsole
Warning: Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively
Warning: Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Warning: Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Warning: Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified

both with a new profile.
useragent overrides - no effect.
compatibility mode - no effect.
seamonkey 2.49.4 and firefox 52.9.0 esr - same issue.
tried on win 10 test pc - same issue.

**Comment by Feodor2** [comment]
This about one thing that newer browsers ignored **opacity: 0** i do not understand why. Then why that thing has been put there at all. Evil constructor possible.
https://www.viabovag.nl/css/viabovag.min.css line 4030

However you can fix yourself. Go to your profile directory and create file the **chrome\UserContent.css** Next paste the line below and restart the browser.

`@-moz-document domain("www.viabovag.nl") {
.input-select option {opacity: 1 !important; }
}`

**Comment by rereser** [comment]
thanks Feodor2 for a solution and the browser update.
Mypal is the best.
had a quick look at the css , still have to find line 4030 ...
will study this some more just to understand.
thanks again.
