### ISSUE TITLE
Whatsapp Web didn't working.

### ISSUE THREAD

**Issue by vkshaw0807** [Feodor2/Mypal#78]
Whatsapp Web is not opening or scanning in latest update of Whatsapp i.e. without keeping your phone online.
how to get rid of this problem..

**Comment by E-System33** [comment]
Try to open it with the new Mypal68

https://github.com/Feodor2/Mypal68/releases/tag/68.12.2b

**Comment by vkshaw0807** [comment]
Thanks for your update. But Whatsapp Web cannot open in this new Mypal68.
It shows "UPDATE MOZILLA FIREFOX".

**Comment by vkshaw0807** [comment]
Thanks for your update. But Whatsapp Web cannot open in this new Mypal68.
It shows "UPDATE MOZILLA FIREFOX".

**Comment by gdl-blue** [comment]
try in about:config **general.useragent.override;Mozilla/5.0 (Windows NT 6.1; rv:100.0) Firefox/100.0 Gecko/20170101**

**Comment by vkshaw0807** [comment]
Thanks but it cannot solve the problem.
Actually main problem is that Whatsapp Web opens in Mypal 29.3.0 version. But it keeps loading in first screen. QR Code not showing.
While the latest "new unstable version - 68.12.3" is showing the message "UPDATE MOZILLA FIREFOX".

**Comment by vkshaw0807** [comment]
> try in about:config **general.useragent.override;Mozilla/5.0 (Windows NT 6.1; rv:100.0) Firefox/100.0 Gecko/20170101**

Not working.. 😔

**Comment by szabota** [comment]
Заработало так:
1. Заходите в:
`C:\Documents and Settings\USERNAME\Application Data\Mypal68\Profiles\XXXXYYYY.default-default`
3. В файл "**prefs.js**" добавляете такую строку:
`user_pref("general.useragent.override", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:60.0) Gecko/20100101 Firefox/60.0");`
4. Вуаля, WhatsApp Web теперь работает в mypal !
