### ISSUE TITLE
Troubleshooting Information bugs mypal

### ISSUE THREAD

**Issue by kitaro1** [Feodor2/Mypal#79]
Mypal 28.6.0
Mypal 28.6.1
http://prnt.sc/omw3r4
Problem - polish language pack.
The Polish language pack works, but it does not work Troubleshooting Information.
The disabled language language pack - Troubleshooting Information is good.
http://prnt.sc/omw8j4
The new build did not fix the problem.

**Comment by Feodor2** [comment]
Fixed, please reinstall https://github.com/Feodor2/Mypal/releases/download/28.6.0/mypal-lang-pl-28.6.0.xpi
