### ISSUE TITLE
Can you keep download URLs to older builds online?

### ISSUE THREAD

**Issue by JoachimHenze** [Feodor2/Mypal#8]
Hello it would be nice, if you could keep the download URLs to outdated versions of MyPal online when you release a newer version.

read https://jira.reactos.org/browse/CORE-15049?focusedCommentId=107632&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-107632 to understand, why this is important for us.

Currently ReactOS is not compatible to your newest build (which is most likely a problem of ReactOS and not MyPal).

So you could help us with keeping links to your old versions, or as a second option:
Would you allow us to host a copy of mypal-27.9.4.win32.installer.exe ourselves, Feodor2?

(If we had the choice we would prefer you keeping stable URLs to outdated builds)

**Comment by wyxchari** [comment]
https://github.com/Feodor2/Mypal27old/releases

**Comment by JoachimHenze** [comment]
Thank you for sharing the link to the old versions. I just updated our rapps-link accordingly. Ticket is resolved. Thx!
