### ISSUE TITLE
Mypal

### ISSUE THREAD

**Issue by Houfino** [Feodor2/Mypal#81]
Hi..I have Windows XP..I want to change it to Czech..I don't know how..Thanks

Tools - Preferences - Content - languages - choose - add czech...I added Czech and nothing ...

**Comment by gdl-blue** [comment]
install the language pack and change the locale

**Comment by Houfino** [comment]
Ok :-)...Thank you :-)

**Comment by gdl-blue** [comment]
https://github.com/Feodor2/Mypal/files/7161611/mypal-lang-cs-29.3.0.zip
is this the one you want?

**Comment by Houfino** [comment]
> [https://github.com/Feodor2/Mypal/files/7161611/mypal-lang-cs-29.3.0.zip ](https://github.com/Feodor2/Mypal/files/7161611/mypal-lang-cs-29.3.0.zip) je to ten, co chceš?

yes...I found this :-)

https://github.com/Feodor2/Mypal/issues/11#issuecomment-1126743467
