### ISSUE TITLE
Web page links that don't work w/any recent MYPAL, but do work w/way outdated Google Chrome for XP

### ISSUE THREAD

**Issue by joeturnes** [Feodor2/Mypal#81]
1. if i want to renew my NJ DMV(figures lol) registration, 
http://www.state.nj.us/mvc/online-services.html  works
but when i click on Renew Vehicle Registration(& some, but not all, of the other links) in the above link, i get
   Secure Connection Failed
   An error occurred during a connection to emvc.state.nj.us.
   Cannot communicate securely with peer: no common encryption algorithm(s).
  (Error code: SSL_ERROR_NO_CYPHER_OVERLAP)
   The page you are trying to view cannot be shown because the authenticity of the received      
   data could not be verified.
   Please contact the website owners to inform them of this problem.
I contacted NJ DMV months ago to look into this, but i don't expect them to fix it - & they haven't. Oddly, google chrome works to renew registr, but when was that browser last updated!!?? Can MYPAL be "massaged" to fix this? I don't like typing in a credit card # using Chrome!

**Comment by rereser** [comment]
tested some other browsers.
working : seamonkey 2.49.4 , firefox 52.9.0 esr.
not working : mypal 28.6.1 , palemoon 28.7.0a1.

**Comment by rereser** [comment]
that site has weak ciphers. (insecure)
in about:config - two changes to make it work.
security.ssl3.rsa_rc4_128_md5  /  set to true.
security.tls.insecure_fallback_hosts  /  add this url - emvc.state.nj.us
restart browser.

**Comment by joeturnes** [comment]
> 
> 
> tested some other browsers.
> working : seamonkey 2.49.4 , firefox 52.9.0 esr.
> not working : mypal 28.6.1 , palemoon 28.7.0a1.

**Comment by joeturnes** [comment]
> 
> 
> that site has weak ciphers. (insecure)
> in about:config - two changes to make it work.
> security.ssl3.rsa_rc4_128_md5 / set to true.
> security.tls.insecure_fallback_hosts / add this url - emvc.state.nj.us
> restart browser.

Thank you!!

**Comment by rereser** [comment]
no problem.
good to see you got it working.
am learning a bit day by day about this great browser.
99% chance the page is at fault , not mypal.
so stay with it.
regards.
