### ISSUE TITLE
CCleaner not recognizing Mypal

### ISSUE THREAD

**Issue by joeturnes** [Feodor2/Mypal#82]
The way to tell for sure is to run CCleaner & then run its Custom Clean while Mypal is running. 
One should get a popup saying "Mypal(or Firefox) needs to be closed to clean ...".
In CCleaner/Custom Clean, clicking Application tab, i do see an entry for Firefox & i have all boxes checked off, except Session, Site Preferences, & Saved Form Information.
I tried doing what's in here
http://www.ccleaner.com/docs/ccleaner/advanced-usage/ccleaner-ini-files/how-to-clean-user-data-from-non-standard-mozilla-browsers
but no luck.
The folder path i used i got from 
Mypal/help/troubleshooting information/profile folder/open folder

Specifically, i periodically want to delete all cookies EASILY,
EXCEPT for important ones(approx 30) i specify in CCleaner/options/cookies/cookies to KEEP.
In Mypal/Tools/Preferences/Privacy/History  i am using Custom Settings for HIstory,
with only    Remember search and form history   &    Allow sites to store cookies and data
checked off.   Accept third-party cookies and site data - Never.
& Keep until - they expire  picked.
I DO want to TEMPORARILY store cookies for ALL sites, since the sites might not work if i don't.
But i do want to easily get rid of MOST of  them periodically, BUT STILL KEEP THE IMPORTANT COOKIES(like for my email site, github, etc.).
I could click the Show Cookies box periodically & manually delete cookies i don't need, but that could take quite a long time! lol

I do not see any mention of  Mypal being ignored in the CCleaner forum.

Anybody get CCleaner to work on Mypal?

**Comment by rereser** [comment]
no idea about ccleaner.
however , this small addon will do exactly what you want.
CookieKeeper 1.9.3.1
http://legacycollector.org/firefox-addons/481410/index.html
this will let you protect cookies and delete the unwanted one's with one click.
add to the toolbar and manage from there , very useful.
do not use the mypal "clear recent history" cookies setting.
that will override and delete all , even the "protected"one's.

**Comment by joeturnes** [comment]
The above addons are not what i want. 
But i just found EXACTLY the addon extension i want! 
Very very similar to CCleaner's cookie manager. 
The addon is  --->  selectivecookiedelete
http://legacycollector.org/firefox-addons/11044/index.html
In options for it, i have cked off    
    Whitelist   (of cookies not to delete)
    Show this window again ....  
    Automatically remove cookies
If you hide the status bar, this extension has a duplicate symbol you can customize drag to 1 of your other toolbars.
Perfect.
