### ISSUE TITLE
One more security update released when Mypal v28.7.1 becomes available

### ISSUE THREAD

**Issue by ByRodrigoSoares** [Feodor2/Mypal#89]
The Question I do all updates entered in Palemoon browser will be available to Mypal users

**Comment by ByRodrigoSoares** [comment]
The Question I do all updates entered in Palemoon browser will be available to Mypal users

**Comment by Feodor2** [comment]
Sorry i did not understood, elaborate in other words

**Comment by ByRodrigoSoares** [comment]
> 
> 
> Sorry i did not understood, elaborate in other words

**Comment by ByRodrigoSoares** [comment]
What I meant is if the same updates made in palemoon are the same for MyPal

**Comment by Feodor2** [comment]
Mostly yes, though sometimes update is not compatible with winxp and i do not include it, there where few for today,  i can point to commits if you want.
