### ISSUE TITLE
WebGL2 support?

### ISSUE THREAD

**Issue by pthfdr-42** [Feodor2/Mypal#9]
When I open get.webgl.org, it says WebGL is supported but the spinning cube is not shown.
I opened about:support and found that "WebGL2 Renderer" says "WebGL creation failed: Error during ANGLE OpenGL init.". In other words, WebGL2 is not usable.
WebGL1 is supported, though.

**Comment by Feodor2** [comment]
This is not fixed yet, but will be eventually
