### ISSUE TITLE
Version 28.7.1

### ISSUE THREAD

**Issue by rocky7717** [Feodor2/Mypal#90]
Hi there,

When you say "this is the plain update"..what specifically does this mean....is there a list or link where one can see the new changes that have been made to the browser??

Thank you....Very appreciative for your program...

**Comment by ByRodrigoSoares** [comment]
I believe if you use the updated Palemoon browser base these are the fixes and updates of this new version

**Comment by ByRodrigoSoares** [comment]
What I can say about this browser is just thank the developers, because it's loading the pages so quickly congratulations

**Comment by Feodor2** [comment]
"plain update" means i do not describe same changes from palemoons's release, if you want to know what exactly was updated look on the palemoon page.

**Comment by rocky7717** [comment]
Thank you for replies...Understood!
