### ISSUE TITLE
How to silent install Mypal?

### ISSUE THREAD

**Issue by AnErrupTion** [Feodor2/Mypal#94]
Hey guys, I was wondering how to silently install Mypal since I'm making a Windows XP mod using nLite (I know how to integrate the programs).
I need how to do it since I want my mod's install to be automated and not a big window popping up saying "Hey, do you want to install Mypal?", I think you see what I talk about.

Sincerely,
~ AnErrupTion

**Comment by Feodor2** [comment]
I suppose this is the same as for firefox so try.

**Comment by SSJ9899TDylan** [comment]
You can make nLite addons using SFXMaker, though I should send a link for it to help you!



Sent from myMail for iOS


Sunday, 6 October 2019, 7:06 am +1100 from notifications@github.com  <notifications@github.com>:

**Comment by AnErrupTion** [comment]
I tried the same for Pale Moon and it worked, and I already have got an app that can make nLite addons so I'm good! Thanks for replying anyway!
