### ISSUE TITLE
dollartree.com aborts mypal

### ISSUE THREAD

**Issue by joeturnes** [Feodor2/Mypal#96]
the home page that is.
oddly though, if, for ex, you google dollartree aspirin & click on link, mypal does not abort & you're in

**Comment by Feodor2** [comment]
Access Denied for https://www.dollartree.com/bulk/Aspirin, do not know why, i shall be try on chrome when be at machine with it, is it possible that site blocks all beside google slaves?

**Comment by joeturnes** [comment]
Seems to be fixed with latest release 28.7.2(32bit)
