### ISSUE TITLE
Please update automatically Mypal

### ISSUE THREAD

**Issue by maximecool** [Feodor2/Mypal#99]
Hello from France,
Mypal has replaced my firefox and I'm happy but I ask you to set up a system of automatic verification and update like was firefox

I hope you will consider my comment

**Comment by Feodor2** [comment]
I asked most users do not want automatic update. But if others many will write a request here, i shall try do it.

**Comment by ByRodrigoSoares** [comment]
I particularly do not like automatic updates prefer manually

**Comment by zRioziin** [comment]
> 
> 
> I asked most users do not want automatic update. But if others many will write a request here, i shall try do it.

If the most of the users don't want automatic updates enabled, why not implement it, but by default unchecked? Then, users who want automatic updates just need to go to the options and enable it.

**Comment by maximecool** [comment]
Ok other not want but why add in tool mypal inbox for check update? Is user choice si want or not!

**Comment by Feodor2** [comment]
I shall try setup autoupdate through github.

**Comment by maximecool** [comment]
very nice is you add
i find  2 little  bug in 28.7.1 =>
- same mypal freeze using gmail siteweb.
- facebook is slow (i have fast core 2 duo)

Sorry for my english i'm am french
